#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#


(in-package :clyc)

;; (defun inference-atomic-term-p (object) ...) -- commented declareFunction, no body

(defun inference-collection? (object &optional mt)
  (or (and (fort-p object)
           (collection? object))
      (and (possibly-naut-p object)
           (isa? object #$Collection mt))))

(defun inference-predicate-p (object)
  (and (fort-p object)
       (predicate? object)))

(defun inference-commutative-relation? (relation)
  (commutative-relation-p relation))

(defun inference-symmetric-predicate? (predicate)
  (symmetric-binary-predicate-p predicate))

(defun inference-commutative-predicate-p (predicate)
  (commutative-predicate-p predicate))

(defun-memoized inference-partially-commutative-predicate-p (predicate) (:test eq)
  (partially-commutative-predicate-p predicate))

(defun inference-at-least-partially-commutative-predicate-p (predicate)
  (or (inference-commutative-predicate-p predicate)
      (inference-partially-commutative-predicate-p predicate)))

;; (defun inference-asymmetric-predicate? (predicate) ...) -- commented declareFunction, no body

(defun inference-transitive-predicate? (predicate)
  (transitive-binary-predicate-p predicate))

(defun inference-evaluatable-predicate? (predicate)
  (evaluatable-predicate? predicate))

(defun inference-reflexive-predicate? (predicate)
  (reflexive-binary-predicate-p predicate))

(defun inference-irreflexive-predicate? (predicate)
  (irreflexive-binary-predicate-p predicate))

(defun inference-indeterminate-term? (value)
  (cond ((fort-p value)
         (indeterminate-term-p value))
        ((possibly-naut-p value)
         (or (common-non-skolem-indeterminate-term-denoting-function?
              (formula-operator value))
             (memoized-inference-indeterminate-term? value)))
        (t nil)))

;; indeterminate-term-p is a globally cached function (defun-cached pattern).
;; clear-indeterminate-term-p is generated by defun-cached.
;; register-hl-store-cache-clear-callback is called via :clear-when :hl-store-modified.
(defun-cached indeterminate-term-p (fort) (:test eq :clear-when :hl-store-modified)
  (quoted-isa-in-any-mt? fort #$IndeterminateTerm))

;; (defun remove-indeterminate-term-p (fort) ...) -- commented declareFunction, no body

(defun-memoized memoized-inference-indeterminate-term? (value) (:test equal)
  (quoted-isa-in-any-mt? value #$IndeterminateTerm))

(defun inference-some-genl-pred-or-inverse? (pred)
  (let ((ans nil))
    (let ((*suspend-sbhl-type-checking?* t))
      (setf ans (some-genl-pred-or-inverse? pred nil)))
    ans))

(defun inference-some-spec-pred-or-inverse? (pred)
  (when (some-spec-predicate-or-inverse-somewhere? pred)
    (let ((ans nil))
      (let ((*suspend-sbhl-type-checking?* t))
        (setf ans (some-spec-pred-or-inverse? pred nil)))
      ans)))

;; (defun inference-some-negation-pred-or-inverse? (pred) ...) -- commented declareFunction, no body
;; (defun inference-all-genl-predicates-internal (predicate) ...) -- commented declareFunction, no body
;; (defun inference-all-genl-predicates (predicate) ...) -- commented declareFunction, no body

(defun inference-all-spec-predicates (predicate)
  (if (some-spec-predicate-or-inverse-somewhere? predicate)
      (inference-all-spec-predicates-int predicate)
      (list predicate)))

(defun-memoized inference-all-spec-predicates-int (predicate) (:test eq)
  (all-spec-predicates predicate nil))

;; (defun inference-all-genl-inverses-internal (predicate) ...) -- commented declareFunction, no body
;; (defun inference-all-genl-inverses (predicate) ...) -- commented declareFunction, no body

(defun inference-all-spec-inverses (predicate)
  (if (some-spec-predicate-or-inverse-somewhere? predicate)
      (inference-all-spec-inverses-int predicate)
      nil))

(defun-memoized inference-all-spec-inverses-int (predicate) (:test eq)
  (all-spec-inverses predicate nil))

;; (defun inference-all-proper-genl-predicates-with-axiom-index-internal (pred sense) ...) -- commented declareFunction, no body
;; (defun inference-all-proper-genl-predicates-with-axiom-index (pred sense) ...) -- commented declareFunction, no body

(defun inference-all-proper-spec-predicates-with-axiom-index (pred sense)
  (if (some-spec-predicate-or-inverse-somewhere? pred)
      (inference-all-proper-spec-predicates-with-axiom-index-int pred sense)
      (values nil 0)))

;; This function has a Javadoc:
;; @return 0 listp; a list of all proper specPreds of PRED with a relevant predicate rule index
;;   wrt sense SENSE.
;; @return 1 integerp; the total accumulated number of rules indexed via
;;   the axiom index for all proper specPreds of PRED.
;;
;; The body is an inline expansion of an SBHL backward search over #$genlPreds,
;; collecting spec-preds that have a relevant predicate rule index. It's ported
;; as a direct translation of the expanded Java.
(defun inference-all-proper-spec-predicates-with-axiom-index-int-internal (pred sense)
  "[Cyc] Return two values: a list of all proper specPreds of PRED with a relevant
predicate rule index wrt sense SENSE, and the total accumulated number of rules
indexed via the axiom index for all proper specPreds of PRED."
  (let ((result nil)
        (cost 0)
        (node-var pred)
        (deck-type :queue)
        (recur-deck (create-deck deck-type))
        (node-and-predicate-mode nil))
    (let ((*sbhl-space* (get-sbhl-marking-space)))
      (let ((tv-var nil))
        (let ((*sbhl-tv* (if tv-var tv-var (get-sbhl-true-tv)))
              (*relevant-sbhl-tv-function* (if tv-var
                                               #'relevant-sbhl-tv-is-general-tv
                                               *relevant-sbhl-tv-function*)))
          (when tv-var
            (when (sbhl-object-type-checking-p)
              (unless (sbhl-true-tv-p tv-var)
                (let ((pcase-var *sbhl-type-error-action*))
                  (cond ((eql pcase-var :error)
                         (sbhl-error 1 "~A is not a ~A" tv-var 'sbhl-true-tv-p))
                        ((eql pcase-var :cerror)
                         (missing-larkc 2122))
                        ((eql pcase-var :warn)
                         (warn "~A is not a ~A" tv-var 'sbhl-true-tv-p))
                        (t
                         (warn "~A is not a valid *sbhl-type-error-action* value"
                               *sbhl-type-error-action*)
                         (cerror "continue anyway" "~A is not a ~A"
                                 tv-var 'sbhl-true-tv-p)))))))
          (let ((*sbhl-search-module* (get-sbhl-module #$genlPreds))
                (*sbhl-search-module-type* (get-sbhl-module-type
                                            (get-sbhl-module #$genlPreds)))
                (*sbhl-add-node-to-result-test* (get-sbhl-add-node-to-result-test
                                                 (get-sbhl-module #$genlPreds)))
                (*genl-inverse-mode-p* nil)
                (*sbhl-module* (get-sbhl-module #$genlPreds)))
            (if (or (suspend-sbhl-type-checking?)
                    (apply-sbhl-module-type-test pred (get-sbhl-module)))
                (let ((*sbhl-search-direction* (get-sbhl-backward-search-direction))
                      (*sbhl-link-direction* (sbhl-search-direction-to-link-direction
                                              (get-sbhl-backward-search-direction)
                                              (get-sbhl-module #$genlPreds)))
                      (*genl-inverse-mode-p* nil))
                  (sbhl-mark-node-marked node-var)
                  (setf node-and-predicate-mode
                        (list pred (genl-inverse-mode-p)))
                  (loop while node-and-predicate-mode do
                    (let* ((node-var-25 (first node-and-predicate-mode))
                           (predicate-mode (second node-and-predicate-mode))
                           (spec-pred node-var-25))
                      (let ((*genl-inverse-mode-p* predicate-mode))
                        (when (apply-sbhl-add-node-test
                               (get-sbhl-search-add-node-test) node-var-25)
                          (when (not (eq spec-pred pred))
                            (let ((num (relevant-num-predicate-rule-index
                                        spec-pred sense)))
                              (when (plusp num)
                                (push spec-pred result)
                                (incf cost num)))))
                        (let ((accessible-modules
                                (get-sbhl-accessible-modules
                                 (get-sbhl-module #$genlPreds))))
                          (dolist (module-var accessible-modules)
                            (let ((*sbhl-module* module-var)
                                  (*genl-inverse-mode-p*
                                    (if (flip-genl-inverse-mode?)
                                        (not *genl-inverse-mode-p*)
                                        *genl-inverse-mode-p*)))
                              (let ((node (naut-to-nart node-var-25)))
                                (if (sbhl-node-object-p node)
                                    (let ((d-link (get-sbhl-graph-link
                                                   node (get-sbhl-module))))
                                      (if d-link
                                          (let ((mt-links
                                                  (get-sbhl-mt-links
                                                   d-link
                                                   (get-sbhl-link-direction)
                                                   (get-sbhl-module))))
                                            (when mt-links
                                              (let ((iteration-state
                                                      (do-dictionary-contents-state
                                                       (dictionary-contents mt-links))))
                                                (loop until (do-dictionary-contents-done?
                                                             iteration-state) do
                                                  (multiple-value-bind (mt tv-links)
                                                      (do-dictionary-contents-key-value
                                                       iteration-state)
                                                    (when (relevant-mt? mt)
                                                      (let ((*sbhl-link-mt* mt))
                                                        (let ((iteration-state-30
                                                                (do-dictionary-contents-state
                                                                 (dictionary-contents tv-links))))
                                                          (loop until (do-dictionary-contents-done?
                                                                       iteration-state-30) do
                                                            (multiple-value-bind (tv link-nodes)
                                                                (do-dictionary-contents-key-value
                                                                 iteration-state-30)
                                                              (when (relevant-sbhl-tv? tv)
                                                                (let ((*sbhl-link-tv* tv))
                                                                  (let ((new-list
                                                                          (if (sbhl-randomize-lists-p)
                                                                              (missing-larkc 9259)
                                                                              link-nodes)))
                                                                    (dolist (node-vars-link-node new-list)
                                                                      (unless (sbhl-search-path-termination-p
                                                                               node-vars-link-node)
                                                                        (sbhl-mark-node-marked
                                                                         node-vars-link-node)
                                                                        (deck-push
                                                                         (list node-vars-link-node
                                                                               (genl-inverse-mode-p))
                                                                         recur-deck))))))
                                                              (setf iteration-state-30
                                                                    (do-dictionary-contents-next
                                                                     iteration-state-30))))
                                                          (do-dictionary-contents-finalize
                                                           iteration-state-30))))
                                                    (setf iteration-state
                                                          (do-dictionary-contents-next
                                                           iteration-state))))
                                                (do-dictionary-contents-finalize
                                                 iteration-state))))
                                          (sbhl-error 5 "attempting to bind direction link variable, to NIL. macro body not executed.")))
                                    (when (cnat-p node)
                                      (let ((new-list
                                              (if (sbhl-randomize-lists-p)
                                                  (missing-larkc 9260)
                                                  (missing-larkc 2569))))
                                        (dolist (generating-fn new-list)
                                          (let ((*sbhl-link-generator* generating-fn))
                                            (let ((link-nodes (funcall generating-fn node)))
                                              (let ((new-list-35
                                                      (if (sbhl-randomize-lists-p)
                                                          (missing-larkc 9261)
                                                          link-nodes)))
                                                (dolist (node-vars-link-node new-list-35)
                                                  (unless (sbhl-search-path-termination-p
                                                           node-vars-link-node)
                                                    (sbhl-mark-node-marked node-vars-link-node)
                                                    (deck-push
                                                     (list node-vars-link-node
                                                           (genl-inverse-mode-p))
                                                     recur-deck)))))))))))))))
                    (setf node-and-predicate-mode (deck-pop recur-deck))))
                (sbhl-warn 2 "Node ~a does not pass sbhl-type-test ~a~%"
                           pred (get-sbhl-type-test (get-sbhl-module))))))))
      (free-sbhl-marking-space *sbhl-space*))
    (values (nreverse result) cost)))

(defun-memoized inference-all-proper-spec-predicates-with-axiom-index-int
    (pred sense) (:test eql)
  (inference-all-proper-spec-predicates-with-axiom-index-int-internal pred sense))

;; (defun inference-all-negation-predicates-with-axiom-index-internal (pred sense) ...) -- commented declareFunction, no body
;; (defun inference-all-negation-predicates-with-axiom-index (pred sense) ...) -- commented declareFunction, no body

(defun inference-some-max-floor-mts (mts)
  (setf mts (remove-duplicates mts :test #'hlmt-equal))
  (setf mts (minimize-mts-wrt-core mts))
  (some-max-floor-mts?-cached mts))

;; some-max-floor-mts?-cached is a globally cached function (defun-cached pattern).
;; clear-some-max-floor-mts?-cached is generated by defun-cached.
;; register-mt-dependent-cache-clear-callback is called via the setup phase,
;; but defun-cached :clear-when only supports :hl-store-modified. We handle this
;; manually by registering the mt-dependent callback in a toplevel form.
(defvar *some-max-floor-mts?-cached-caching-state* nil)

(defun clear-some-max-floor-mts?-cached ()
  (let ((cs *some-max-floor-mts?-cached-caching-state*))
    (when cs (caching-state-clear cs)))
  nil)

(defun some-max-floor-mts?-cached (mts)
  (let ((cs *some-max-floor-mts?-cached-caching-state*))
    (when (null cs)
      (setf cs (create-global-caching-state-for-name
                'some-max-floor-mts?-cached
                '*some-max-floor-mts?-cached-caching-state*
                256 'equal 1 0))
      (register-mt-dependent-cache-clear-callback 'clear-some-max-floor-mts?-cached))
    (let ((results (caching-state-lookup cs mts :&memoized-item-not-found&)))
      (when (eq results :&memoized-item-not-found&)
        (setf results (multiple-value-list (some-max-floor-mts? mts)))
        (caching-state-put cs mts results))
      (caching-results results))))

(toplevel
  (note-globally-cached-function 'some-max-floor-mts?-cached))

(defun inference-max-floor-mts-with-cycles-pruned (mts &optional candidates)
  (setf mts (remove-duplicates mts :test #'hlmt-equal))
  (setf mts (minimize-mts-wrt-core mts))
  (if candidates
      (max-floor-mts-with-cycles-pruned mts candidates)
      (inference-max-floor-mts-with-cycles-pruned-cached mts)))

;; inference-max-floor-mts-with-cycles-pruned-cached is a globally cached function.
;; Same manual expansion as some-max-floor-mts?-cached because it uses
;; register-mt-dependent-cache-clear-callback (not :hl-store-modified).
(defvar *inference-max-floor-mts-with-cycles-pruned-cached-caching-state* nil)

(defun clear-inference-max-floor-mts-with-cycles-pruned-cached ()
  (let ((cs *inference-max-floor-mts-with-cycles-pruned-cached-caching-state*))
    (when cs (caching-state-clear cs)))
  nil)

(defun inference-max-floor-mts-with-cycles-pruned-cached (mts)
  (let ((cs *inference-max-floor-mts-with-cycles-pruned-cached-caching-state*))
    (when (null cs)
      (setf cs (create-global-caching-state-for-name
                'inference-max-floor-mts-with-cycles-pruned-cached
                '*inference-max-floor-mts-with-cycles-pruned-cached-caching-state*
                256 'equal 1 0))
      (register-mt-dependent-cache-clear-callback
       'clear-inference-max-floor-mts-with-cycles-pruned-cached))
    (let ((results (caching-state-lookup cs mts :&memoized-item-not-found&)))
      (when (eq results :&memoized-item-not-found&)
        (setf results (multiple-value-list
                       (max-floor-mts-with-cycles-pruned mts)))
        (caching-state-put cs mts results))
      (caching-results results))))

(toplevel
  (note-globally-cached-function 'inference-max-floor-mts-with-cycles-pruned-cached))

;; (defun remove-some-max-floor-mts?-cached (mts) ...) -- commented declareFunction, no body
;; (defun remove-inference-max-floor-mts-with-cycles-pruned-cached (mts) ...) -- commented declareFunction, no body
;; (defun inference-max-floor-mts-of-nat-internal (nat) ...) -- commented declareFunction, no body
;; (defun inference-max-floor-mts-of-nat (nat) ...) -- commented declareFunction, no body

(defun some-max-floor-mts? (mts)
  (and (max-floor-mts mts) t))

;; (defun inference-applicable-sdct?-internal (collection) ...) -- commented declareFunction, no body
;; (defun inference-applicable-sdct? (collection) ...) -- commented declareFunction, no body

;; Reconstructed from Internal Constants:
;; $list39: ((ASSERTION-VAR ASENT SENSE &KEY DONE) &BODY BODY)
;; $sym43$DO_GAF_LOOKUP_INDEX - wraps do-gaf-lookup-index
;; $sym44$INFERENCE_GAF_LOOKUP_INDEX - computes the lookup index
;; $kw45$TRUTH - passed as :truth keyword
;; $sym46$SENSE_TRUTH - converts sense to truth via sense-truth
;; The macro computes a GAF lookup index using inference-gaf-lookup-index,
;; then delegates to do-gaf-lookup-index with the :truth derived from sense.
(defmacro do-inference-gaf-lookup-index ((assertion-var asent sense
                                          &key done) &body body)
  `(do-gaf-lookup-index (,assertion-var (inference-gaf-lookup-index ,asent ,sense)
                          :truth (sense-truth ,sense)
                          :done ,done)
     ,@body))

(defun-memoized inference-gaf-lookup-index (asent sense) (:test equal)
  (best-gaf-lookup-index asent (sense-truth sense)))

(defun-memoized inference-num-gaf-lookup-index (asent sense) (:test equal)
  (num-best-gaf-lookup-index asent (sense-truth sense)))

;; (defun inference-relevant-num-gaf-lookup-index-internal (asent sense mt) ...) -- commented declareFunction, no body
;; (defun inference-relevant-num-gaf-lookup-index (asent sense mt) ...) -- commented declareFunction, no body
;; (defun inference-key-gaf-arg-index-internal (v-term &optional argnum predicate) ...) -- commented declareFunction, no body
;; (defun inference-key-gaf-arg-index (v-term &optional argnum predicate) ...) -- commented declareFunction, no body

(defun problem-backchain-required? (problem)
  "[Cyc] Return T iff PROBLEM is backchain required"
  (declare (type problem-p problem))
  (let ((query (problem-query problem)))
    (dolist (contextualized-dnf-clause query)
      (unless (inference-some-backchain-required-asent-in-clause?
               contextualized-dnf-clause)
        (return-from problem-backchain-required? nil)))
    t))

(defun inference-some-backchain-required-asent-in-clause? (contextualized-dnf-clause)
  (dolist (contextualized-asent (neg-lits contextualized-dnf-clause))
    (when (inference-backchain-required-contextualized-asent? contextualized-asent)
      (return-from inference-some-backchain-required-asent-in-clause? t)))
  (dolist (contextualized-asent (pos-lits contextualized-dnf-clause))
    (when (inference-backchain-required-contextualized-asent? contextualized-asent)
      (return-from inference-some-backchain-required-asent-in-clause? t)))
  nil)

(defun inference-backchain-required-contextualized-asent? (contextualized-asent)
  (let ((asent (contextualized-asent-asent contextualized-asent))
        (mt (contextualized-asent-mt contextualized-asent)))
    (inference-backchain-required-asent? asent mt)))

(defun inference-backchain-required-asent? (asent mt)
  (setf mt (backchain-control-mt mt))
  (let ((pred (atomic-sentence-predicate asent)))
    (when (fort-p pred)
      (when (inference-predicate-backchain-required? pred mt)
        (return-from inference-backchain-required-asent? t))
      (when (member pred (list #$isa #$genls) :test #'eq)
        (let ((col (atomic-sentence-arg2 asent)))
          (when (fort-p col)
            (when (inference-collection-backchain-required? col mt)
              (return-from inference-backchain-required-asent? t))
            (when (and (eq pred #$isa)
                       (inference-collection-isa-backchain-required? col mt))
              (return-from inference-backchain-required-asent? t))
            (when (and (eq pred #$genls)
                       (inference-collection-genls-backchain-required? col mt))
              (return-from inference-backchain-required-asent? t)))))))
  nil)

(defun-memoized inference-predicate-backchain-required? (predicate mt) (:test eq)
  (backchain-required? predicate (backchain-control-mt mt)))

(defun-memoized inference-backchain-forbidden? (predicate mt) (:test eq)
  (backchain-forbidden? predicate (backchain-control-mt mt)))

;; (defun inference-collection-isa-backchain-encouraged?-internal (col mt) ...) -- commented declareFunction, no body
;; (defun inference-collection-isa-backchain-encouraged? (col mt) ...) -- commented declareFunction, no body
;; (defun inference-collection-genls-backchain-encouraged?-internal (col mt) ...) -- commented declareFunction, no body
;; (defun inference-collection-genls-backchain-encouraged? (col mt) ...) -- commented declareFunction, no body
;; (defun inference-collection-backchain-encouraged?-internal (col mt) ...) -- commented declareFunction, no body
;; (defun inference-collection-backchain-encouraged? (col mt) ...) -- commented declareFunction, no body

(defun-memoized inference-collection-backchain-required? (col mt) (:test eq)
  (collection-backchain-required? col (backchain-control-mt mt)))

(defun-memoized inference-collection-isa-backchain-required? (col mt) (:test eq)
  (collection-isa-backchain-required? col (backchain-control-mt mt)))

(defun-memoized inference-collection-genls-backchain-required? (col mt) (:test eq)
  (collection-genls-backchain-required? col (backchain-control-mt mt)))

(defun backchain-control-mt (mt)
  "[Cyc] Assuming that we are doing inference MT, return the mt in which to look for
assertions that control the behaviour of backchaining.  If all mts are relevant,
we need to be conservative and only look for universally true backchain control assertions."
  (conservative-constraint-mt mt))

(defun inference-relevant-mt? (assertion-mt &optional inference-mt)
  (and (fort-p assertion-mt)
       (some-pred-value-in-relevant-mts assertion-mt #$highlyRelevantMt
                                        inference-mt 1 :true)))

;; (defun inference-relevant-assertion? (assertion &optional inference-mt) ...) -- commented declareFunction, no body
;; (defun inference-relevant-predicate-assertion? (predicate assertion &optional inference-mt) ...) -- commented declareFunction, no body
;; (defun inference-relevant-term? (v-term &optional inference-mt) ...) -- commented declareFunction, no body

(defun inference-irrelevant-mt? (assertion-mt &optional inference-mt)
  (and (fort-p assertion-mt)
       (some-pred-value-in-relevant-mts assertion-mt #$irrelevantMt
                                        inference-mt 1 :true)))

;; (defun inference-irrelevant-assertion? (assertion &optional inference-mt) ...) -- commented declareFunction, no body
;; (defun inference-irrelevant-predicate-assertion? (predicate assertion &optional inference-mt) ...) -- commented declareFunction, no body
;; (defun inference-irrelevant-term? (v-term &optional inference-mt) ...) -- commented declareFunction, no body
;; (defun inference-rule-has-utility? (assertion &optional mt) ...) -- commented declareFunction, no body
;; (defun inference-rule-utility (assertion &optional mt) ...) -- commented declareFunction, no body
;; (defun inference-known-sentence-removal-query-internal (sentence mt &optional params) ...) -- commented declareFunction, no body
;; (defun inference-known-sentence-removal-query (sentence mt &optional params) ...) -- commented declareFunction, no body
;; (defun inference-known-sentence-recursive-query (sentence mt &optional params) ...) -- commented declareFunction, no body
;; (defun inference-true-sentence-recursion-cycle? (sentence) ...) -- commented declareFunction, no body
;; (defun inference-true-sentence-recursive-query-internal (sentence mt &optional params) ...) -- commented declareFunction, no body
;; (defun inference-true-sentence-recursive-query (sentence mt &optional params) ...) -- commented declareFunction, no body
;; (defun inference-mts-where-gaf-sentence-true-internal (gaf-sentence) ...) -- commented declareFunction, no body
;; (defun inference-mts-where-gaf-sentence-true (gaf-sentence) ...) -- commented declareFunction, no body
;; (defun inference-mts-where-gaf-sentence-true-justified-memoized-internal (gaf-sentence) ...) -- commented declareFunction, no body
;; (defun inference-mts-where-gaf-sentence-true-justified-memoized (gaf-sentence) ...) -- commented declareFunction, no body
;; (defun inference-mts-where-gaf-sentence-true-justified (gaf-sentence) ...) -- commented declareFunction, no body
;; (defun determine-sentence-recursive-query-properties (sentence mt) ...) -- commented declareFunction, no body
;; (defun determine-sentence-recursive-query-properties-recursive (sentence mt) ...) -- commented declareFunction, no body
;; (defun inference-rule-type-constraints-internal (assertion) ...) -- commented declareFunction, no body
;; (defun inference-rule-type-constraints (assertion) ...) -- commented declareFunction, no body

;;; Variables

(defparameter *inference-true-sentence-recursion-stack* nil)

;;; Setup phase toplevel forms
;; note-memoized-function calls for active defun-memoized forms are generated by the macro.
;; The remaining note calls are for commented-out functions; they must still appear.
(toplevel
  (note-memoized-function 'inference-all-genl-predicates)
  (note-memoized-function 'inference-all-genl-inverses)
  (note-memoized-function 'inference-all-proper-genl-predicates-with-axiom-index)
  (note-memoized-function 'inference-all-negation-predicates-with-axiom-index)
  (note-memoized-function 'inference-max-floor-mts-of-nat)
  (note-memoized-function 'inference-applicable-sdct?)
  (note-memoized-function 'inference-relevant-num-gaf-lookup-index)
  (note-memoized-function 'inference-key-gaf-arg-index)
  (note-memoized-function 'inference-collection-isa-backchain-encouraged?)
  (note-memoized-function 'inference-collection-genls-backchain-encouraged?)
  (note-memoized-function 'inference-collection-backchain-encouraged?)
  (note-memoized-function 'inference-known-sentence-removal-query)
  (note-memoized-function 'inference-true-sentence-recursive-query)
  (note-memoized-function 'inference-mts-where-gaf-sentence-true)
  (note-memoized-function 'inference-mts-where-gaf-sentence-true-justified-memoized)
  (note-memoized-function 'inference-rule-type-constraints))
