#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#


(in-package :clyc)

;; Graph structures used by the canonicalizer for formula graph isomorphism.
;; All function bodies are missing-larkc; only struct definitions and
;; print trampolines survive.

;;; V-COLOUR struct — vertex colouring for graph isomorphism comparison

(defstruct (v-colour (:conc-name "V-COLOUR-"))
  sorted-constant-list
  sorted-nat-list
  sorted-assertion-list
  list-structure
  sorted-var-positions)

(defconstant *dtp-v-colour* 'v-colour)


;; v-colour-p is generated by defstruct; Java UnaryFunction uses missing-larkc 29117
;; Struct accessors/setters generated by defstruct: v-colour-sorted-constant-list,
;; v-colour-sorted-nat-list, v-colour-sorted-assertion-list, v-colour-list-structure,
;; v-colour-sorted-var-positions and their setf expansions
;; (defun make-v-colour (&rest args) ...) -- generated by defstruct
;; (defun v-colour-as-list (v-colour) ...) -- active declareFunction, no body
;; (defun v-colour-min (v-colour) ...) -- active declareFunction, no body

;;; ARC struct — directed edge in the canonicalizer graph

(defstruct (arc (:conc-name "ARC-"))
  head
  colour)

(defconstant *dtp-arc* 'arc)


;; arc-p is generated by defstruct; Java UnaryFunction uses missing-larkc 29090
;; Struct accessors/setters generated by defstruct
;; (defun make-arc (&rest args) ...) -- generated by defstruct
;; (defun print-arc (arc stream depth) ...) -- active declareFunction, no body
;; (defun new-arc (head colour) ...) -- active declareFunction, no body
;; (defun arc-as-sortable-list (arc) ...) -- active declareFunction, no body
;; (defun arc-as-unifiable-list (arc) ...) -- active declareFunction, no body
;; (defun colour-arc (arc graph v-colour) ...) -- active declareFunction, no body

;;; VERTEX struct — node in the canonicalizer graph

(defstruct (vertex (:conc-name "VERTEX-"))
  id
  colour
  arc-set)

(defconstant *dtp-vertex* 'vertex)


;; vertex-p is generated by defstruct; Java UnaryFunction uses missing-larkc 29120
;; Struct accessors/setters generated by defstruct
;; (defun make-vertex (&rest args) ...) -- generated by defstruct
;; (defun print-vertex (vertex stream depth) ...) -- active declareFunction, no body
;; (defun find-vertex-by-id (id graph) ...) -- active declareFunction, no body
;; (defun vertex-as-sortable-list (vertex) ...) -- active declareFunction, no body
;; (defun vertex-as-unifiable-list (vertex) ...) -- active declareFunction, no body
;; (defun vertex-first-half-as-sortable-list (vertex) ...) -- active declareFunction, no body
;; (defun vertex-first-half-as-unifiable-list (vertex) ...) -- active declareFunction, no body
;; (defun vertex-second-half-as-sortable-set (vertex) ...) -- active declareFunction, no body
;; (defun vertex-second-half-as-unifiable-set (vertex) ...) -- active declareFunction, no body
;; (defun vertex-add-arc (vertex arc-head v-colour) ...) -- active declareFunction, no body
;; (defun colour-vertex (vertex v-colour) ...) -- active declareFunction, no body
;; (defun new-vertex (id colour arc-set) ...) -- active declareFunction, no body

;;; GRAPH-SEARCH-NODE struct — search state in graph isomorphism

(defstruct (graph-search-node (:conc-name "GRAPH-SEARCH-NODE-"))
  vertex
  search-history)

(defconstant *dtp-graph-search-node* 'graph-search-node)


;; graph-search-node-p is generated by defstruct; Java UnaryFunction uses missing-larkc 29094
;; Struct accessors/setters generated by defstruct
;; (defun make-graph-search-node (&rest args) ...) -- generated by defstruct
;; (defun print-graph-search-node (node stream depth) ...) -- active declareFunction, no body
;; (defun inert-variable (variable) ...) -- active declareFunction, no body
;; (defun graph-search-node-as-sortable-sets (node) ...) -- active declareFunction, no body
;; (defun graph-search-node-as-unifiable-sets (node) ...) -- active declareFunction, no body
;; (defun unify-graph-search-node (node1 node2) ...) -- active declareFunction, no body
;; (defun graph-search-nodes-isomorphic? (node1 node2) ...) -- active declareFunction, no body
;; (defun graph-search-node-< (node1 node2) ...) -- active declareFunction, no body
;; (defun min-graph-search-node (nodes) ...) -- active declareFunction, no body
;; (defun vertex-search-state-as-unifiable-sets-of-sets (state) ...) -- active declareFunction, no body
;; (defun vertex-search-state-as-sortable-sets-of-sets (state) ...) -- active declareFunction, no body
;; (defun unify-vertex-search-state (state1 state2) ...) -- active declareFunction, no body
;; (defun vertex-search-states-isomorphic? (state1 state2) ...) -- active declareFunction, no body
;; (defun vertex-search-state-< (state1 state2) ...) -- active declareFunction, no body
;; (defun min-vertex-search-state (states graph) ...) -- active declareFunction, no body
;; (defun source-vertex (graph) ...) -- active declareFunction, no body
;; (defun init-graph-search-state (graph) ...) -- active declareFunction, no body
;; (defun graph-search-state-covers-graph? (state graph) ...) -- active declareFunction, no body
;; (defun least-vertex (graph &optional done-already) ...) -- active declareFunction, no body
;; (defun least-vertex-recursive (state graph candidates) ...) -- active declareFunction, no body
;; (defun penultimate-resort-literals (clauses) ...) -- active declareFunction, no body
;; (defun last-resort-literal (clause index) ...) -- active declareFunction, no body
;; (defun compute-sorted-shared-vars (formula1 formula2) ...) -- active declareFunction, no body
