#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

;;; ======================================================================
;;; Variables
;;; ======================================================================

(defvar *has-suf-defn-cache* nil)
(defvar *has-quoted-suf-defn-cache* nil)
(defvar *iff-defns* nil)
(defvar *quoted-iff-defns* nil)
(defvar *suf-defns* nil)
(defvar *quoted-suf-defns* nil)
(defvar *nec-defns* nil)
(defvar *quoted-nec-defns* nil)
(defvar *defn-term* nil)
(defvar *org-collection* nil)
(defvar *failing-suf-defns* nil)

;; Metering state vars for the first 5 metered functions are generated by
;; define-defn-metered macro calls below (in the Metering infrastructure section).

(deflexical *min-defn-admits-map*
    (list (list #'stringp #$CharacterString)
          (list #'positive-integer-p #$PositiveInteger)
          (list #'non-negative-integer-p #$NonNegativeInteger)
          (list #'integerp #$Integer)
          (list #'floatp #$RealNumber)
          (list (constantly t) #$Thing)))

(deflexical *min-quoted-defn-admits-map*
    (list (list #'stringp #$SubLString)
          (list #'integerp #$SubLInteger)
          (list #'floatp #$SubLRealNumber)
          (list #'symbolp #$SubLSymbol)
          (list #'constant-p #$CycLConstant)
          (list #'nart-p #$CycLNonAtomicReifiedTerm)
          (list #'assertion-p #$CycLAssertion)
          (list (constantly t) #$CycLExpression)))

;; Metering state vars for the handle-*-genl-for-suf-*-defns functions are
;; generated by define-defn-metered macro calls below (Genl-for-suf-defns section).

;;; ======================================================================
;;; Functions
;;; ======================================================================

(defun suf-defn-count (col quoted?)
  "[Cyc] Return the suf-defn count for COL."
  (unless (or *has-suf-defn-cache* *has-quoted-suf-defn-cache*)
    ;; missing-larkc 10597 likely initializes the defns cache
    (missing-larkc 10597))
  (if quoted?
      (gethash col *has-quoted-suf-defn-cache*)
      (gethash col *has-suf-defn-cache*)))

(defun has-suf-defn-somewhere? (col quoted?)
  "[Cyc] Return T if COL has a suf-defn somewhere."
  (and (suf-defn-count col quoted?) t))

;; (defun set-suf-defn-count (col count quoted?) ...) -- commented declareFunction (3 0)
;; (defun rem-suf-defn-count (col quoted?) ...) -- commented declareFunction (2 0)

(defun iff-defn (col quoted?)
  "[Cyc] Return the iff-defn for COL."
  (unless (or *iff-defns* *quoted-iff-defns*)
    ;; missing-larkc 10600 likely initializes the defns cache
    (missing-larkc 10600))
  (if quoted?
      (gethash col *quoted-iff-defns*)
      (gethash col *iff-defns*)))

;; (defun rem-iff-defn (col quoted?) ...) -- commented declareFunction (2 0)

(defun suf-defns (col quoted?)
  "[Cyc] Return the suf-defns for COL."
  (unless (or *suf-defns* *quoted-suf-defns*)
    ;; missing-larkc 10602 likely initializes the defns cache
    (missing-larkc 10602))
  (if quoted?
      (gethash col *quoted-suf-defns*)
      (gethash col *suf-defns*)))

;; (defun rem-suf-defn (col defn quoted?) ...) -- commented declareFunction (3 0)
;; (defun new-suf-defn? (col &optional quoted?) ...) -- commented declareFunction (2 1)

(defun nec-defns (col quoted?)
  "[Cyc] Return the nec-defns for COL."
  (unless (or *nec-defns* *quoted-nec-defns*)
    ;; missing-larkc 10604 likely initializes the defns cache
    (missing-larkc 10604))
  (if quoted?
      (gethash col *quoted-nec-defns*)
      (gethash col *nec-defns*)))

;; (defun rem-nec-defn (col defn quoted?) ...) -- commented declareFunction (3 0)

(defun has-some-defn? (col quoted?)
  "[Cyc] Return T if COL has some defn (iff, suf, or nec)."
  (or (iff-defn col quoted?)
      (suf-defns col quoted?)
      (nec-defns col quoted?)
      nil))

;;; ======================================================================
;;; Metering infrastructure
;;; ======================================================================

(define-defn-metered new-defns-admit? (col term &optional (mt *mt*))
  (defns-admit?-int col term mt nil))

(defun defns-admit?-int (col term mt quoted?)
  "[Cyc] Return T if all defns for COL admit TERM in MT."
  (when (reifiable-nat? col)
    ;; missing-larkc 10336 likely calls nart-substitute to get the reified form
    (setf col (missing-larkc 10336)))
  (when (permitting-denotational-terms-admitted-by-defn-via-isa?)
    (if quoted?
        (when (quoted-isa? term col mt)
          (return-from defns-admit?-int t))
        (when (isa? term col mt)
          (return-from defns-admit?-int t))))
  (unless (or (fort-p col)
              (has-suf-defn-somewhere? col quoted?))
    (return-from defns-admit?-int nil))
  (let ((admitted? nil))
    (let ((*defn-fn-history* (possibly-make-defn-fn-history-table))
          (*quoted-defn-fn-history* (possibly-make-quoted-defn-fn-history-table))
          (*defn-col-history* (possibly-make-defn-col-history-table))
          (*quoted-defn-col-history* (possibly-make-quoted-defn-col-history-table)))
      (unwind-protect
           (let ((status (initial-check-defn-admit-status col term mt quoted?)))
             (case status
               (:admitted (setf admitted? t))
               (:rejected (setf admitted? nil))
               (otherwise
                (if (defns-walk-admit? col term mt quoted?)
                    (setf admitted? t)
                    (when (and (not quoted?)
                               (fast-quote-term-p term))
                      ;; missing-larkc 31111 likely calls cycl-denotation-term
                      ;; to get the denoted term from the quoted expression
                      (let ((denoted-term (missing-larkc 31111)))
                        (when (and denoted-term
                                   (quoted-defns-admit? col denoted-term mt))
                          (setf admitted? t))))))))
        (clear-defn-space)))
    admitted?))

(define-defn-metered new-defns-reject? (col term &optional (mt *mt*))
  (defns-reject?-int col term mt nil))

(defun defns-reject?-int (col term mt quoted?)
  "[Cyc] Return T if defns for COL reject TERM in MT."
  (when (reifiable-nat? col)
    ;; missing-larkc 10337 likely calls nart-substitute to get the reified form
    (setf col (missing-larkc 10337)))
  (when (permitting-denotational-terms-admitted-by-defn-via-isa?)
    (if quoted?
        (when (quoted-isa? term col mt)
          (return-from defns-reject?-int nil))
        (when (isa? term col mt)
          (return-from defns-reject?-int nil))))
  (unless (fort-p col)
    (return-from defns-reject?-int nil))
  (let ((rejected? nil))
    (let ((*defn-fn-history* (possibly-make-defn-fn-history-table))
          (*quoted-defn-fn-history* (possibly-make-quoted-defn-fn-history-table))
          (*defn-col-history* (possibly-make-defn-col-history-table))
          (*quoted-defn-col-history* (possibly-make-quoted-defn-col-history-table)))
      (unwind-protect
           (let ((status (initial-check-defn-admit-status col term mt quoted?)))
             (case status
               (:admitted (setf rejected? nil))
               (:rejected (setf rejected? t))
               (otherwise
                (if (nec-defn-rejects? col term mt quoted?)
                    (setf rejected? t)
                    (when (and (not quoted?)
                               (fast-quote-term-p term))
                      ;; missing-larkc 31112 likely calls cycl-denotation-term
                      (let ((denoted-term (missing-larkc 31112)))
                        (when (and denoted-term
                                   ;; missing-larkc 5429 likely calls
                                   ;; quoted-defns-reject? for the denoted term
                                   (missing-larkc 5429))
                          (setf rejected? t))))))))
        (clear-defn-space)))
    rejected?))

(define-defn-metered new-quoted-defns-admit? (col term &optional (mt *mt*))
  (defns-admit?-int col term mt t))

;; new-quoted-defns-reject?-metered and new-quoted-defns-reject? are commented out
;; in Java (//declareFunction (2 1)); only reset-new-quoted-defns-reject?-meters is active.
(define-defn-metered new-quoted-defns-reject? (col term &optional (mt *mt*))
  (missing-larkc "new-quoted-defns-reject?-metered and new-quoted-defns-reject? do not exist in Java; only the reset function is active."))

;;; ======================================================================
;;; Defn checking logic
;;; ======================================================================

(defun initial-check-defn-admit-status (col term mt quoted?)
  "[Cyc] If the defnIff of the COL explicitly admits or rejects TERM, return result.
Otherwise, return :rejected if a necessaryDefn of genls of COL rejects the TERM.
Will delegate to the correct defns checks for quoted/non-quoted using QUOTED?"
  (let ((admit-status (defining-defns-admits? col term mt quoted?))
        (done? nil))
    (case admit-status
      (:admitted)
      (:rejected)
      (otherwise
       (when *at-apply-necessary-defns?*
         (let ((*defn-collection* col))
           (unless done?
             ;; Walk genls of COL checking nec-defn-rejects? for each.
             ;; This is an inline expansion of (do-all-genls (genl col :direction :forward) ...)
             ;; which uses the sbhl module for #$genls.
             ;; Since sbhl modules are unported, we use genls:all-genls instead.
             (dolist (genl (all-genls col mt))
               (when done? (return))
               (when (not (eq genl col))
                 (when (nec-defn-rejects? genl term mt quoted? t)
                   (setf done? t)
                   (setf admit-status :rejected)))))))))
    admit-status))

(defun defns-walk-admit? (col term mt quoted?)
  "[Cyc] Walk genls of COL, checking defn admission."
  (let ((result nil))
    (let ((*defn-term* term)
          (*org-collection* col)
          (*failing-suf-defns* nil))
      (if quoted?
          (setf result (sbhl-simply-gather-first-among-all-backward-true-nodes-with-prune
                        (get-sbhl-module #$genls) col #'col-quoted-defn-admits? mt))
          (setf result (sbhl-simply-gather-first-among-all-backward-true-nodes-with-prune
                        (get-sbhl-module #$genls) col #'col-defn-admits? mt)))
      (when (and (not result)
                 *noting-at-violations?*
                 *include-suf-defn-violations?*
                 *failing-suf-defns*)
        ;; missing-larkc 7223 likely checks some condition about suf-defn violations
        (when (missing-larkc 7223)
          ;; missing-larkc 11308 likely records suf-defn violation
          (missing-larkc 11308))))
    result))

;; (defun sufficient-defn-violations (col term mt quoted? violations) ...) -- commented declareFunction (5 0)
;; (defun sufficient-defn-violation (col term mt quoted? violation assertion) ...) -- commented declareFunction (6 0)

(defun col-defn-admits? (col)
  "[Cyc] Does COL's defn admit the current *defn-term*?"
  (col-defn-admits?-int col *defn-term* *mt* nil))

;; (defun col-quoted-defn-admits? (col) ...) -- commented declareFunction (1 0)

(defun col-defn-admits?-int (col term mt quoted?)
  "[Cyc] Implementation of col-defn-admits? with explicit args."
  (unless (has-suf-defn-somewhere? col quoted?)
    (return-from col-defn-admits?-int (list nil t)))
  (unless (has-some-defn? col quoted?)
    (return-from col-defn-admits?-int (list nil nil)))
  (let ((result nil)
        (done? nil)
        (status (if (eq *org-collection* col)
                    t
                    (defining-defns-admits? col term mt quoted?))))
    (case status
      (:admitted (setf result t done? t))
      (:rejected (setf result nil done? t))
      (otherwise
       (when (nec-defn-permits? col term mt quoted? nil)
         (when (suf-defn-admits? col term mt quoted?)
           (setf result t done? t)))
       (unless done?
         (setf result nil done? t))))
    (list result done?)))

(defun defining-defns-admits? (col term mt quoted?)
  "[Cyc] Check the iff-defn of COL for whether it admits TERM in MT."
  (let ((iff-defn (iff-defn col quoted?))
        (admit-status nil))
    (when (null iff-defn)
      (return-from defining-defns-admits? nil))
    (possibly-in-mt (mt)
      (when (and (valid-assertion iff-defn)
                 (relevant-mt? (assertion-mt iff-defn)))
        (let ((defn (cycl-subl-symbol-symbol (gaf-arg2 iff-defn))))
          (let ((*defn-collection* col))
            (when (viable-defn? defn col)
              (if (if quoted?
                      (quoted-defn-admits? defn term col mt)
                      (defn-admits? defn term col mt))
                  (setf admit-status :admitted)
                  (progn
                    (setf admit-status :rejected)
                    (when *noting-at-violations?*
                      ;; missing-larkc 11309 likely records iff-defn violation
                      (missing-larkc 11309)))))))))
    admit-status))

;; (defun defining-defn-violations (col term mt quoted? assertion) ...) -- commented declareFunction (5 0)
;; (defun defining-defn-violation (col term mt quoted? violation assertion) ...) -- commented declareFunction (6 0)

(defun suf-defn-admits? (col term mt quoted?)
  "[Cyc] Check whether any sufficient defn of COL admits TERM in MT."
  (let ((suf-defns (suf-defns col quoted?))
        (admitted? nil)
        (done? nil))
    (when (null suf-defns)
      (return-from suf-defn-admits? nil))
    (possibly-in-mt (mt)
      (unless done?
        (dolist (suf-defn suf-defns)
          (when done? (return))
          (when (and (valid-assertion suf-defn)
                     (relevant-mt? (assertion-mt suf-defn)))
            (let ((defn (cycl-subl-symbol-symbol (gaf-arg2 suf-defn))))
              (let ((*defn-collection* col))
                (when (viable-defn? defn col)
                  (if (if quoted?
                          ;; missing-larkc 5365 likely calls quiet-quoted-defn-admits?
                          (missing-larkc 5365)
                          (quiet-defn-admits? defn term col mt))
                      (progn
                        (setf admitted? t)
                        (setf done? t))
                      (progn
                        (setf admitted? nil)
                        (setf done? nil)
                        (when *noting-at-violations?*
                          (pushnew defn *failing-suf-defns*)))))))))))
    admitted?))

(defun nec-defn-permits? (col term mt quoted? &optional (consider-iff-as-nec? nil))
  "[Cyc] Return T if the necessary defns of COL permit TERM in MT."
  (not (nec-defn-rejects? col term mt quoted? consider-iff-as-nec?)))

(define-defn-metered nec-defn-rejects? (col term mt quoted? &optional (consider-iff-as-nec? nil))
  "[Cyc] Do the necessary defns of COL reject TERM in MT?"
  (let ((nec-defns (nec-defns col quoted?))
        (rejected? nil)
        (done? nil))
    (when (null nec-defns)
      (when consider-iff-as-nec?
        (setf nec-defns (list (iff-defn col quoted?))))
      (when (null nec-defns)
        (return-from nec-defn-rejects?-metered nil)))
    (possibly-in-mt (mt)
      (unless done?
        (dolist (nec-defn nec-defns)
          (when done? (return))
          (when (and (valid-assertion nec-defn)
                     (relevant-mt? (assertion-mt nec-defn)))
            (let ((defn (cycl-subl-symbol-symbol (gaf-arg2 nec-defn))))
              (let ((*defn-collection* col))
                (when (viable-defn? defn col)
                  (if (if quoted?
                          (quoted-defn-admits? defn term col mt)
                          (defn-admits? defn term col mt))
                      (progn
                        (setf rejected? nil)
                        (setf done? nil))
                      (progn
                        (setf rejected? t)
                        (setf done? t)
                        (when *noting-at-violations?*
                          ;; missing-larkc 11310 likely records nec-defn violation
                          (missing-larkc 11310)))))))))))
    rejected?))

;;; ======================================================================
;;; Commented-out stubs for various defn operations
;;; ======================================================================

;; (defun necessary-defn-violations (col term mt quoted? consider-iff-as-nec? violations) ...) -- commented declareFunction (6 0)
;; (defun necessary-defn-violation (col term mt quoted? consider-iff-as-nec? violation assertion) ...) -- commented declareFunction (7 0)
;; (defun new-mts-of-admitting-defns (col term) ...) -- commented declareFunction (2 0)
;; (defun mts-of-admitting-quoted-defns (col term) ...) -- commented declareFunction (2 0)
;; (defun new-hl-justify-isa-via-defns (col term &optional mt) ...) -- commented declareFunction (2 1)
;; (defun hl-justify-quoted-isa-via-defns (col term &optional mt) ...) -- commented declareFunction (2 1)
;; (defun assertions-of-admitting-defns (col term mt quoted? assertions) ...) -- commented declareFunction (5 0)
;; (defun mts-from-defn-assertions (col defn-assertions) ...) -- commented declareFunction (2 0)
;; (defun initial-check-admit-defn (col term mt) ...) -- commented declareFunction (3 0)
;; (defun defns-of-admitting-sufficient-defns (col term mt quoted?) ...) -- commented declareFunction (4 0)
;; (defun admitting-defn-assertions (col) ...) -- commented declareFunction (1 0)
;; (defun admitting-quoted-defn-assertions (col) ...) -- commented declareFunction (1 0)
;; (defun admitting-defn-assertion (col) ...) -- commented declareFunction (1 0)
;; (defun admitting-quoted-defn-assertion (col) ...) -- commented declareFunction (1 0)
;; (defun admitting-defn-assertions-int (col term mt quoted?) ...) -- commented declareFunction (4 0)
;; (defun suf-admitting-defns (col term mt quoted?) ...) -- commented declareFunction (4 0)
;; (defun min-defn-admits (col &optional mt) ...) -- commented declareFunction (1 1)
;; (defun all-defn-admits (col &optional mt) ...) -- commented declareFunction (1 1)
;; (defun min-quoted-defn-admits (col &optional mt) ...) -- commented declareFunction (1 1)
;; (defun all-quoted-defn-admits (col &optional mt) ...) -- commented declareFunction (1 1)
;; (defun update-iff-or-suf-defn (col defn type quoted?) ...) -- commented declareFunction (4 0)
;; (defun update-nec-defn (col defn quoted?) ...) -- commented declareFunction (3 0)
;; (defun new-add-iff-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun new-remove-iff-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun new-add-suf-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun new-remove-suf-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun add-nec-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun remove-nec-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun new-add-iff-quoted-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun new-remove-iff-quoted-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun new-add-suf-quoted-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun new-remove-suf-quoted-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun add-nec-quoted-defn (col defn) ...) -- commented declareFunction (2 0)
;; (defun remove-nec-quoted-defn (col defn) ...) -- commented declareFunction (2 0)

;;; ======================================================================
;;; Genl-for-suf-defns handlers
;;; ======================================================================

(defun handle-added-genl-for-suf-defns-int (spec genl quoted?)
  "[Cyc] Handle an added genls link from SPEC to GENL, propagating suf-defn counts."
  (let ((spec-suf-count (suf-defn-count spec quoted?)))
    (when (and (integerp spec-suf-count) (> spec-suf-count 0))
      (with-all-mts
        ;; Walk all genls of GENL, incrementing suf-defn counts.
        ;; This is an inline expansion of do-all-genls on #$genls module forward.
        ;; Since sbhl modules are unported, we use all-genls instead.
        (dolist (genl-col (all-genls genl))
          ;; missing-larkc 10594 likely calls inc-suf-defn-count for genl-col
          (missing-larkc 10594)))))
  nil)

(define-defn-metered new-handle-added-genl-for-suf-defns (spec genl)
  (handle-added-genl-for-suf-defns-int spec genl nil))

(define-defn-metered new-handle-added-genl-for-suf-quoted-defns (spec genl)
  (handle-added-genl-for-suf-defns-int spec genl t))

(defun handle-removed-genl-for-suf-defns-int (spec genl quoted?)
  "[Cyc] Handle a removed genls link from SPEC to GENL, updating suf-defn counts."
  (with-all-mts
    (unless (genl? spec genl)
      (let ((spec-suf-count (suf-defn-count spec quoted?)))
        (when (and (integerp spec-suf-count) (> spec-suf-count 0))
          ;; Walk all genls of GENL, decrementing suf-defn counts.
          ;; Since sbhl modules are unported, we use all-genls instead.
          (dolist (genl-col (all-genls genl))
            ;; missing-larkc 10590 likely calls dec-suf-defn-count for genl-col
            (missing-larkc 10590))))))
  nil)

(define-defn-metered new-handle-removed-genl-for-suf-defns (spec genl)
  (handle-removed-genl-for-suf-defns-int spec genl nil))

(define-defn-metered new-handle-removed-genl-for-suf-quoted-defns (spec genl)
  (handle-removed-genl-for-suf-defns-int spec genl t))

;;; ======================================================================
;;; Cache management
;;; ======================================================================

(defun clear-defns ()
  "[Cyc] Clear all defn caches."
  (unless *use-new-defns-functions?*
    (return-from clear-defns nil))
  (when *has-suf-defn-cache*
    (clrhash *has-suf-defn-cache*))
  (when *iff-defns*
    (clrhash *iff-defns*))
  (when *suf-defns*
    (clrhash *suf-defns*))
  (when *nec-defns*
    (clrhash *nec-defns*))
  (when *has-quoted-suf-defn-cache*
    (clrhash *has-quoted-suf-defn-cache*))
  (when *quoted-iff-defns*
    (clrhash *quoted-iff-defns*))
  (when *quoted-suf-defns*
    (clrhash *quoted-suf-defns*))
  (when *quoted-nec-defns*
    (clrhash *quoted-nec-defns*))
  nil)

;; (defun initialize-defns-cache () ...) -- commented declareFunction (0 0)
;; (defun initialize-defns () ...) -- commented declareFunction (0 0)
;; (defun inc-suf-defn-count (col &optional quoted? delta) ...) -- commented declareFunction (2 1)
;; (defun dec-suf-defn-count (col &optional quoted? delta) ...) -- commented declareFunction (2 1)
;; (defun update-suf-defn-cache (col count quoted?) ...) -- commented declareFunction (3 0)
;; (defun update-defns (col defn type quoted?) ...) -- commented declareFunction (4 0)

(defun defns-cache-unbuilt? ()
  "[Cyc] Return T if the defns cache has not yet been populated."
  (not (and (hash-table-p *has-suf-defn-cache*)
            (not (hash-table-empty-p *has-suf-defn-cache*))
            (hash-table-p *iff-defns*)
            (not (hash-table-empty-p *iff-defns*))
            (hash-table-p *suf-defns*)
            (not (hash-table-empty-p *suf-defns*))
            (hash-table-p *nec-defns*)
            (not (hash-table-empty-p *nec-defns*))
            (hash-table-p *has-quoted-suf-defn-cache*)
            (not (hash-table-empty-p *has-quoted-suf-defn-cache*))
            (hash-table-p *quoted-iff-defns*)
            (not (hash-table-empty-p *quoted-iff-defns*))
            (hash-table-p *quoted-suf-defns*)
            (hash-table-p *quoted-nec-defns*)
            (hash-table-p *suf-defn-cache*)
            (not (hash-table-empty-p *suf-defn-cache*))
            (hash-table-p *suf-quoted-defn-cache*)
            (not (hash-table-empty-p *suf-quoted-defn-cache*))
            (hash-table-p *suf-function-cache*)
            (not (hash-table-empty-p *suf-function-cache*))
            (hash-table-p *suf-quoted-function-cache*)
            (not (hash-table-empty-p *suf-quoted-function-cache*)))))

(defun clear-defns-cache ()
  "[Cyc] Clear all defns and suf-defn caches."
  (clear-defns)
  (clear-suf-defns)
  (clear-suf-quoted-defns)
  (clear-suf-functions)
  (clear-suf-quoted-functions)
  nil)

;; (defun rebuild-defns-cache () ...) -- commented declareFunction (0 0)
;; (defun dump-defns-cache-to-stream (stream) ...) -- commented declareFunction (1 0)

(defun load-defns-cache-from-stream (stream)
  "[Cyc] Load defns cache from a CFASL stream."
  (setf *has-suf-defn-cache* (cfasl-input stream))
  (setf *iff-defns* (cfasl-input stream))
  (setf *suf-defns* (cfasl-input stream))
  (setf *nec-defns* (cfasl-input stream))
  (setf *has-quoted-suf-defn-cache* (cfasl-input stream))
  (setf *quoted-iff-defns* (cfasl-input stream))
  (setf *quoted-suf-defns* (cfasl-input stream))
  (setf *quoted-nec-defns* (cfasl-input stream))
  (setf *suf-defn-cache* (cfasl-input stream))
  (setf *suf-quoted-defn-cache* (cfasl-input stream))
  (setf *suf-function-cache* (cfasl-input stream))
  (setf *suf-quoted-function-cache* (cfasl-input stream))
  ;; Three dummy reads for forward compatibility
  (cfasl-input stream)
  (cfasl-input stream)
  (cfasl-input stream)
  nil)

;;; ======================================================================
;;; Setup phase — KB function registrations
;;; ======================================================================
;; Metering cache setup (reset, :reset key, *defn-meter-caches* registration)
;; is handled by the define-defn-metered macro expansions above.

(toplevel
  ;; Register KB functions for defn add/remove handlers
  (register-kb-function 'new-add-iff-defn)
  (register-kb-function 'new-remove-iff-defn)
  (register-kb-function 'new-add-suf-defn)
  (register-kb-function 'new-remove-suf-defn)
  (register-kb-function 'add-nec-defn)
  (register-kb-function 'remove-nec-defn)
  (register-kb-function 'new-add-iff-quoted-defn)
  (register-kb-function 'new-remove-iff-quoted-defn)
  (register-kb-function 'new-add-suf-quoted-defn)
  (register-kb-function 'new-remove-suf-quoted-defn)
  (register-kb-function 'add-nec-quoted-defn)
  (register-kb-function 'remove-nec-quoted-defn))
