#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

;;; FINITE-STATE-TRANSDUCER defstruct

(defstruct (finite-state-transducer (:conc-name "FST-")
                                    (:print-function print-fst))
  initial-state
  final-states
  machine-table
  token-builder
  input
  current-token-index
  current-state
  memory
  indexed-output)

(defconstant *dtp-finite-state-transducer* 'finite-state-transducer)

;;; Functions (ordered by declare_finite_state_transducer_file)

(defun finite-state-transducer-print-function-trampoline (object stream)
  "[Cyc] Print function trampoline for FINITE-STATE-TRANSDUCER."
  (declare (ignore object stream))
  (missing-larkc 29478))

(defun finite-state-transducer-p (object)
  "[Cyc] Return T if OBJECT is a FINITE-STATE-TRANSDUCER struct."
  (declare (ignore object))
  (missing-larkc 29449))

;; Struct accessors fst-initial-state, fst-final-states, fst-machine-table,
;; fst-token-builder, fst-input, fst-current-token-index, fst-current-state,
;; fst-memory, fst-indexed-output — generated by defstruct.
;; _CSETF-FST-* setters — (setf fst-*) generated by defstruct.

;; (defun make-finite-state-transducer (&optional arglist) ...) -- active declareFunction, no body
;; (defun print-fst (object stream &optional depth) ...) -- active declareFunction, no body
;; (defun fst-output-start (fst) ...) -- active declareFunction, no body
;; (defun fst-output-end (fst) ...) -- active declareFunction, no body
;; (defun new-finite-state-transducer (initial-state final-states machine-table &optional token-builder) ...) -- active declareFunction, no body
;; (defun fst-output (fst) ...) -- active declareFunction, no body
;; (defun fst-match (sequence fst) ...) -- active declareFunction, no body

;;; Macros (reconstructed from Internal Constants evidence)

;; $list44 = ((MATCH SEQUENCE FST) &BODY BODY)
;; Orphan constants: $sym45$PROGN, $sym46$FST-INITIALIZE, $sym47$CDO,
;;   $sym48$FST-MATCH-INTERNAL, $sym49$NULL, $sym50$VECTOR, $kw51$END
;; The VECTOR / :END keywords suggest CDO iterates a vector-form sequence.
;; CDO macro and its exact expansion shape are not yet ported/known; full
;; reconstruction cannot be verified because there are no visible expansion
;; sites in the available Java. TODO: verify against CDO semantics once
;; CDO is ported.
(defmacro fst-do-match ((match sequence fst) &body body)
  "[Cyc] Iterate MATCH over the results of running FST on SEQUENCE, executing BODY each time."
  ;; TODO: reconstruction unverified — depends on unported CDO iteration macro
  `(progn
     (fst-initialize ,fst ,sequence)
     (cdo (,match (fst-match-internal ,fst) (fst-match-internal ,fst))
          ((null ,match))
       ,@body)))

;; (defun fst-match-global (sequence fst) ...) -- active declareFunction, no body
;; (defun fst-initialize (fst sequence) ...) -- active declareFunction, no body
;; (defun fst-match-internal (fst) ...) -- active declareFunction, no body
;; (defun fst-run (fst) ...) -- active declareFunction, no body
;; (defun fst-current-token (fst) ...) -- active declareFunction, no body
;; (defun fst-final-state-p (fst) ...) -- active declareFunction, no body
;; (defun fst-action-p (action) ...) -- active declareFunction, no body
;; (defun fst-execute (fst action-list) ...) -- active declareFunction, no body
;; (defun fst-emit (fst) ...) -- active declareFunction, no body
;; (defun fst-remember (fst) ...) -- active declareFunction, no body
;; (defun fst-backup (fst) ...) -- active declareFunction, no body
;; (defun machine-table-set (machine-table state key value action) ...) -- active declareFunction, no body
;; (defun machine-table-get (machine-table state key) ...) -- active declareFunction, no body
;; (defun key-matches (key token) ...) -- active declareFunction, no body
;; (defun max-state (machine-table) ...) -- active declareFunction, no body

;;; Setup phase

(note-funcall-helper-function 'print-fst)
