#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

;;; Port of com.cyc.tool.subl.jrtl.nativeCode.subLisp.Guids (SubL runtime)
;;; and com.cyc.tool.subl.jrtl.nativeCode.type.core.SubLGuid (type definition).
;;; GUIDs are a primitive SubL type wrapping a UUID string representation.

(in-package :clyc)

;;; GUID struct — wraps a UUID string in a distinct type

(defstruct (guid (:constructor %make-guid)
                 (:print-function print-guid))
  (string "" :type string))

(defconstant *dtp-guid* 127)

(defun print-guid (guid stream depth)
  (declare (ignore depth))
  (format stream "#G\"~a\"" (guid-string guid)))

;;; Construction

(defun string-to-guid (string)
  "Convert a UUID string to a GUID object."
  (declare (type string string))
  (%make-guid :string string))

(defun guid-to-string (guid)
  "Convert a GUID object to its UUID string representation."
  (declare (type guid guid))
  (guid-string guid))

(defun new-guid ()
  "Generate a new random GUID."
  ;; Read 16 random bytes, format as UUID version 4
  (let* ((bytes (make-array 16 :element-type '(unsigned-byte 8)))
         (_ (dotimes (i 16) (setf (aref bytes i) (random 256))))
         ;; Set version 4 (random) in byte 6
         (_ (setf (aref bytes 6) (logior (logand (aref bytes 6) #x0f) #x40)))
         ;; Set variant 1 (RFC 4122) in byte 8
         (_ (setf (aref bytes 8) (logior (logand (aref bytes 8) #x3f) #x80))))
    (declare (ignore _ _ _))
    (%make-guid :string (format nil "~(~2,'0x~2,'0x~2,'0x~2,'0x-~2,'0x~2,'0x-~2,'0x~2,'0x-~2,'0x~2,'0x-~2,'0x~2,'0x~2,'0x~2,'0x~2,'0x~2,'0x~)"
                                (aref bytes 0) (aref bytes 1) (aref bytes 2) (aref bytes 3)
                                (aref bytes 4) (aref bytes 5)
                                (aref bytes 6) (aref bytes 7)
                                (aref bytes 8) (aref bytes 9)
                                (aref bytes 10) (aref bytes 11) (aref bytes 12) (aref bytes 13) (aref bytes 14) (aref bytes 15)))))

;;; Predicates

;; guid-p is auto-generated by defstruct above

(defun guid-string-p (object)
  "Return T if OBJECT is a string that looks like a valid GUID."
  (and (stringp object)
       (= (length object) 36)
       (char= (char object 8) #\-)
       (char= (char object 13) #\-)
       (char= (char object 18) #\-)
       (char= (char object 23) #\-)
       (every (lambda (c) (or (digit-char-p c 16) (char= c #\-))) object)
       t))

;;; Comparison

(defun guid= (guid1 guid2)
  "Return T if two GUIDs are equal."
  (declare (type guid guid1 guid2))
  (string-equal (guid-string guid1) (guid-string guid2)))

(defun guid/= (guid1 guid2)
  "Return T if two GUIDs are not equal."
  (declare (type guid guid1 guid2))
  (not (guid= guid1 guid2)))

(defun guid< (guid1 guid2)
  "Return T if GUID1 is less than GUID2."
  (declare (type guid guid1 guid2))
  (string-lessp (guid-string guid1) (guid-string guid2)))

(defun guid<= (guid1 guid2)
  "Return T if GUID1 is less than or equal to GUID2."
  (declare (type guid guid1 guid2))
  (not (guid< guid2 guid1)))

(defun guid> (guid1 guid2)
  "Return T if GUID1 is greater than GUID2."
  (declare (type guid guid1 guid2))
  (guid< guid2 guid1))

(defun guid>= (guid1 guid2)
  "Return T if GUID1 is greater than or equal to GUID2."
  (declare (type guid guid1 guid2))
  (not (guid< guid1 guid2)))

;;; Byte-vector assembly/disassembly (for CFASL serialization)

(defun disassemble-guid-to-fixnums (guid &optional (byte-vector (make-array 16 :initial-element 0)))
  "Decompose a GUID into a 16-element byte vector."
  (declare (type guid guid))
  (let* ((s (remove #\- (guid-string guid)))
         (hex-len (length s)))
    (declare (type string s))
    (assert (= hex-len 32))
    (dotimes (i 16)
      (setf (aref byte-vector i)
            (parse-integer s :start (* i 2) :end (+ (* i 2) 2) :radix 16))))
  byte-vector)

(defun assemble-fixnums-to-guid (byte-vector)
  "Construct a GUID from a 16-element byte vector."
  (%make-guid :string (format nil "~(~2,'0x~2,'0x~2,'0x~2,'0x-~2,'0x~2,'0x-~2,'0x~2,'0x-~2,'0x~2,'0x-~2,'0x~2,'0x~2,'0x~2,'0x~2,'0x~2,'0x~)"
                              (aref byte-vector 0) (aref byte-vector 1) (aref byte-vector 2) (aref byte-vector 3)
                              (aref byte-vector 4) (aref byte-vector 5)
                              (aref byte-vector 6) (aref byte-vector 7)
                              (aref byte-vector 8) (aref byte-vector 9)
                              (aref byte-vector 10) (aref byte-vector 11) (aref byte-vector 12) (aref byte-vector 13) (aref byte-vector 14) (aref byte-vector 15))))

;; (defun crack-date-relative-guid (guid) ...) -- unimplemented in Java
;; (defun date-relative-guid-p (guid) ...) -- unimplemented in Java
;; (defun make-date-relative-guid (year month day offset) ...) -- unimplemented in Java
