#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#


(in-package :clyc)


;; MESSAGE structure

(defstruct (message (:conc-name "MSG-")
                    (:print-function print-message))
  from
  to
  cc
  bcc
  subject
  additional-headers
  host
  port
  parts)

(defconstant *dtp-message* 'message)


;; MESSAGE-PART structure

(defstruct (message-part (:conc-name "MSG-PART-")
                         (:print-function print-message-part))
  content-type
  content-type-parameters
  disposition
  content-disposition-parameters
  encoding
  data
  data-type)

(defconstant *dtp-message-part* 'message-part)


;; Functions (declare section ordering)

;; MESSAGE struct accessors/mutators are generated by defstruct above.

(defun message-print-function-trampoline (object stream)
  "[Cyc] Print function trampoline for MESSAGE."
  (print-message object stream 0))

(defun message-p (object)
  "[Cyc] Return T if OBJECT is a MESSAGE structure."
  (typep object 'message))

;; MSG-FROM, MSG-TO, MSG-CC, MSG-BCC, MSG-SUBJECT, MSG-ADDITIONAL-HEADERS,
;; MSG-HOST, MSG-PORT, MSG-PARTS — generated by defstruct
;; _CSETF-MSG-FROM etc. — (setf msg-from) generated by defstruct

(defun make-message (&optional arglist)
  "[Cyc] Create a new MESSAGE, optionally with keyword arguments."
  (declare (ignore arglist))
  (make-message))

(defun print-message (object stream depth)
  "[Cyc] Print a MESSAGE."
  (declare (ignore depth))
  (format stream "<MESSAGE>"))

(defun new-message (&optional from to subject host port cc)
  "[Cyc] Create a new MESSAGE with the given fields."
  (declare (type (or null string) from to subject cc)
           (type (or null string) host)
           (type (or null integer) port))
  (let ((msg (make-message)))
    (when from (setf (msg-from msg) from))
    (when to (setf (msg-to msg) (list to)))
    (when subject (setf (msg-subject msg) subject))
    (setf (msg-host msg) (or host "localhost"))
    (when port (setf (msg-port msg) port))
    (when cc (setf (msg-cc msg) (list cc)))
    msg))

(defun message-set-from (message from)
  "[Cyc] Set the FROM field of MESSAGE."
  (setf (msg-from message) from))

(defun message-from (message)
  "[Cyc] Return the FROM field of MESSAGE."
  (msg-from message))

(defun message-add-to (message to)
  "[Cyc] Add TO to the recipients of MESSAGE."
  (setf (msg-to message) (append (msg-to message) (list to))))

(defun message-to (message)
  "[Cyc] Return the TO list of MESSAGE."
  (msg-to message))

(defun message-add-cc (message cc)
  "[Cyc] Add CC to the carbon-copy list of MESSAGE."
  (setf (msg-cc message) (append (msg-cc message) (list cc))))

(defun message-cc (message)
  "[Cyc] Return the CC list of MESSAGE."
  (msg-cc message))

(defun message-add-bcc (message bcc)
  "[Cyc] Add BCC to the blind-carbon-copy list of MESSAGE."
  (setf (msg-bcc message) (append (msg-bcc message) (list bcc))))

(defun message-bcc (message)
  "[Cyc] Return the BCC list of MESSAGE."
  (msg-bcc message))

(defun message-set-subject (message subject)
  "[Cyc] Set the SUBJECT of MESSAGE."
  (setf (msg-subject message) subject))

(defun message-subject (message)
  "[Cyc] Return the SUBJECT of MESSAGE."
  (msg-subject message))

(defun message-add-header (message header)
  "[Cyc] Add HEADER to the additional headers of MESSAGE."
  (setf (msg-additional-headers message)
        (append (msg-additional-headers message) (list header))))

(defun message-additional-headers (message)
  "[Cyc] Return the additional headers of MESSAGE."
  (msg-additional-headers message))

(defun message-set-host (message host)
  "[Cyc] Set the HOST of MESSAGE."
  (setf (msg-host message) host))

(defun message-host (message)
  "[Cyc] Return the HOST of MESSAGE."
  (msg-host message))

(defun message-set-port (message port)
  "[Cyc] Set the PORT of MESSAGE."
  (setf (msg-port message) port))

(defun message-port (message)
  "[Cyc] Return the PORT of MESSAGE."
  (msg-port message))

(defun message-add-part (message part)
  "[Cyc] Add PART to the parts of MESSAGE."
  (setf (msg-parts message) (append (msg-parts message) (list part))))

(defun message-parts (message)
  "[Cyc] Return the parts of MESSAGE."
  (msg-parts message))

;; (defun send-message (message &optional verbose?) ...) -- active declareFunction, no body

;; (defun send-message-parts (message stream) ...) -- active declareFunction, no body

(defun sxhash-message-method (object)
  "[Cyc] Sxhash method for MESSAGE."
  (missing-larkc 29965))

;; (defun sxhash-message (message) ...) -- active declareFunction, no body

;; (defun validate-message (message) ...) -- active declareFunction, no body

;; (defun send-message-internal (message verbose?) ...) -- active declareFunction, no body


;; MESSAGE-PART struct accessors/mutators are generated by defstruct above.

(defun message-part-print-function-trampoline (object stream)
  "[Cyc] Print function trampoline for MESSAGE-PART."
  (print-message-part object stream 0))

(defun message-part-p (object)
  "[Cyc] Return T if OBJECT is a MESSAGE-PART structure."
  (typep object 'message-part))

;; MSG-PART-CONTENT-TYPE, MSG-PART-CONTENT-TYPE-PARAMETERS, MSG-PART-DISPOSITION,
;; MSG-PART-CONTENT-DISPOSITION-PARAMETERS, MSG-PART-ENCODING, MSG-PART-DATA,
;; MSG-PART-DATA-TYPE — generated by defstruct
;; _CSETF-MSG-PART-* — (setf msg-part-*) generated by defstruct

(defun make-message-part (&optional arglist)
  "[Cyc] Create a new MESSAGE-PART, optionally with keyword arguments."
  (declare (ignore arglist))
  (make-message-part))

(defun print-message-part (object stream depth)
  "[Cyc] Print a MESSAGE-PART."
  (declare (ignore depth))
  (format stream "<MESSAGE-PART (~A)" (msg-part-content-type object))
  (format stream ">"))

(defun new-inline-message-part (data &optional content-type encoding)
  "[Cyc] Create a new inline MESSAGE-PART."
  (new-message-part (or content-type "text/plain")
                    "inline"
                    (or encoding "7bit")
                    data
                    :string))

(defun new-message-attachment (filename &optional content-type encoding data-type)
  "[Cyc] Create a new attachment MESSAGE-PART."
  (new-message-part (or content-type "text/plain")
                    "attachment"
                    (or encoding "7bit")
                    filename
                    (or data-type :file)))

(defun valid-message-part-data-type-p (data-type)
  "[Cyc] Return T if DATA-TYPE is a valid message part data type."
  (member data-type '(:string :file)))

(defun valid-message-part-encoding-p (encoding)
  "[Cyc] Return T if ENCODING is a valid message part encoding."
  (member encoding '("7bit" "8bit" "binary") :test #'string=))

(defun new-message-part (content-type disposition encoding data data-type)
  "[Cyc] Create a new MESSAGE-PART with the given fields."
  (let ((part (make-message-part)))
    (setf (msg-part-content-type part) content-type)
    (setf (msg-part-disposition part) disposition)
    (setf (msg-part-encoding part) encoding)
    (setf (msg-part-data part) data)
    (setf (msg-part-data-type part) data-type)
    part))

(defun message-part-content-type (part)
  "[Cyc] Return the content type of PART."
  (msg-part-content-type part))

(defun message-part-set-content-type (part content-type)
  "[Cyc] Set the content type of PART."
  (setf (msg-part-content-type part) content-type))

(defun message-part-content-disposition-parameters (part)
  "[Cyc] Return the content disposition parameters of PART."
  (msg-part-content-disposition-parameters part))

(defun message-part-set-attachment-name (part name)
  "[Cyc] Set the attachment name of PART."
  (message-part-set-content-disposition-parameter part :filename name))

(defun message-part-disposition (part)
  "[Cyc] Return the disposition of PART."
  (msg-part-disposition part))

(defun message-part-encoding (part)
  "[Cyc] Return the encoding of PART."
  (msg-part-encoding part))

(defun message-part-data (part)
  "[Cyc] Return the data of PART."
  (msg-part-data part))

(defun message-part-data-type (part)
  "[Cyc] Return the data type of PART."
  (msg-part-data-type part))

(defun sxhash-message-part-method (object)
  "[Cyc] Sxhash method for MESSAGE-PART."
  (missing-larkc 29966))

;; (defun sxhash-message-part (part) ...) -- active declareFunction, no body

(defun message-part-set-content-disposition-parameter (part key value)
  "[Cyc] Set a content disposition parameter on PART."
  (setf (msg-part-content-disposition-parameters part)
        (cons (cons key value)
              (remove key (msg-part-content-disposition-parameters part) :key #'car))))

;; (defun send-message-part (part boundary stream) ...) -- active declareFunction, no body

;; (defun send-message-part-headers (part stream) ...) -- active declareFunction, no body

;; (defun send-message-part-data (part stream) ...) -- active declareFunction, no body


;; Setup phase

(note-funcall-helper-function 'print-message)
(note-funcall-helper-function 'print-message-part)
