#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#


(in-package :clyc)


;;; Variables

(defparameter *all-communication-modes*
  (list (cons :transmit-and-receive "Sending and Receiving")
        (cons :receive-only "Storing and Receiving")
        (cons :transmit-only "Sending Only")
        (cons :dead-receive "Not Recording but Receiving")
        (cons :deaf "Storing Only")
        (cons :dead "Not Recording or Receiving")))

(defglobal *allow-transmitting* t
  "[Cyc] Is this image allowed to transmit. As of now, 4/24/98, there are only 3
reasons for this to be nil. One, the image is an experimental image. See
*experimental-image*. Two, the image has connected to the transcript
server and requested a transcript that has been CLOSED. Three, the image
has read through a master transcript and evaluated the CLOSE-KB operation
and the defvar *auto-increment-kb* is nil.")

(defglobal *kb-full-transcript-loaded* nil)

(defparameter *experimental-image* nil
  "[Cyc] Boolean: If T, then this image can not transmit operations. This
parameter should only be set at start up time. It is intended to provide
an image that can not transmit operations to the master transcript. It is
closely tied to *allow-transmitting* and its accessor functions. For more
info see *allow-transmitting*.")

(defparameter *read-transcript-op-limit* 200
  "[Cyc] The max number of read-transcript ops to load at once")

(defglobal *receiving-remote-operations?* t)

(defglobal *process-local-operations?* t)

(defglobal *process-auxiliary-operations?* t)

(defglobal *saving-operations?* nil)

(defglobal *total-remote-operations-run* 0
  "[Cyc] The number of successfully processed operations generated by a different
image, and read from the master transcript.")

(defglobal *total-auxiliary-operations-run* 0
  "[Cyc] The number of operations that have been processed by the auxiliary queue.")

(defglobal *total-local-operations-recorded* 0
  "[Cyc] The number of operations that have been processed and recorded locally by
this image. This is cummulative over all time, i.e. it is not reset when
a new local transcript is started.")

(defglobal *total-local-operations-transmitted* 0
  "[Cyc] The number of local operations that have been transmitted to the master
transcript by this image. This is cummulative over all time, i.e. it is
not reset when a new local transcript is started.")

(defglobal *read-master-transcript-op-number* 0
  "[Cyc] The number of operations that have been read from the master transcript
by this image. The objective is to accurately mark exactly where in the
master transcript we are. This variable is accessed via (kb-op-number).
It should NOT be directly accessed. Operations are counted in two places.
As they are removed from the remote-queue and are about to be processed.
And as they are dropped because they were from this image.")

(defglobal *total-master-transcript-operations-processed* 0
  "[Cyc] The number of operations that have been read from the master transcript
by this image *and* processed.")

(deflexical *image-requires-authentication?* nil
  "[Cyc] Determines whether the image requires authentication")

(defparameter *cyclist-authenticating-app* #$CycBrowser
  "[Cyc] The Application for which the user is being authenticated.")

(defparameter *default-cyclist-authentication-mt* #$CyclistsMt
  "[Cyc] The default MT for looking up the Cyclist authentication information.")

(deflexical *transmit-states* (list "transmit" "store" "none"))

(deflexical *receive-states* (list "yes" "no"))

(deflexical *build-request-email* "build-requests@cyc.com")

(defparameter *save-transcript-ops-lock* (bt:make-lock "Save Transcript OPS lock")
  "[Cyc] This lock controls who actually gets to write to the transcript file,
since multiple threads could otherwise open the same file for appending
and stomp all over each other.")

(defparameter *save-hl-transcript-ops-lock* (bt:make-lock "Save Hl-Transcript OPS lock")
  "[Cyc] This lock controls who actually gets to write to the hl-transcript file,
since multiple threads could otherwise open the same file for appending
and stomp all over each other.")

(defvar *transcript-load-succeeded* nil)

(defglobal *transcript-read-attempted* nil)

(defglobal *initial-read-transcript-size* 0)

(defglobal *remote-operations-kb-check-point* nil)


;;; Functions (declare section ordering)

(defun allow-transmitting ()
  "[Cyc] Accessor for *allow-transmitting*"
  *allow-transmitting*)

;; (defun set-allow-transmitting (v-boolean) ...) -- 1/0, commented declareFunction, no body
;; (defun kb-full-transcript-loaded () ...) -- 0/0, commented declareFunction, no body
;; (defun set-kb-full-transcript-loaded (v-boolean) ...) -- 1/0, commented declareFunction, no body
;; (defun experimental-image () ...) -- 0/0, commented declareFunction, no body
;; (defun set-experimental-image (v-boolean) ...) -- 1/0, commented declareFunction, no body
;; (defun read-transcript-op-limit () ...) -- 0/0, commented declareFunction, no body
;; (defun set-read-transcript-op-limit (limit) ...) -- 1/0, commented declareFunction, no body

(defun dont-record-operations-locally ()
  *dont-record-operations-locally*)

;; (defun set-dont-record-operations-locally (v-boolean) ...) -- 1/0, commented declareFunction, no body

(defun receiving-remote-operations? ()
  *receiving-remote-operations?*)

(defun set-receiving-remote-operations? (v-boolean)
  (setf *receiving-remote-operations?* v-boolean)
  *receiving-remote-operations?*)

(defun process-local-operations? ()
  *process-local-operations?*)

;; (defun set-process-local-operations? (v-boolean) ...) -- 1/0, commented declareFunction, no body

(defun process-auxiliary-operations? ()
  *process-auxiliary-operations?*)

(defun set-process-auxiliary-operations? (v-boolean)
  (setf *process-auxiliary-operations?* v-boolean)
  *process-auxiliary-operations?*)

(defun saving-operations? ()
  *saving-operations?*)

(defun set-saving-operations? (v-boolean)
  (setf *saving-operations?* v-boolean)
  *saving-operations?*)

;; (defun total-remote-operations-run () ...) -- 0/0, commented declareFunction, no body
;; (defun set-total-remote-operations-run (count) ...) -- 1/0, commented declareFunction, no body
;; (defun total-auxiliary-operations-run () ...) -- 0/0, commented declareFunction, no body
;; (defun inc-total-auxiliary-operations-run () ...) -- 0/0, commented declareFunction, no body
;; (defun total-local-operations-recorded () ...) -- 0/0, commented declareFunction, no body

(defun inc-total-local-operations-recorded ()
  (setf *total-local-operations-recorded* (+ *total-local-operations-recorded* 1))
  *total-local-operations-recorded*)

;; (defun total-local-operations-transmitted () ...) -- 0/0, commented declareFunction, no body
;; (defun inc-total-local-operations-transmitted () ...) -- 0/0, commented declareFunction, no body

(defun read-master-transcript-op-number ()
  *read-master-transcript-op-number*)

;; (defun set-read-master-transcript-op-number (number) ...) -- 1/0, commented declareFunction, no body
;; (defun total-master-transcript-operations-processed () ...) -- 0/0, commented declareFunction, no body
;; (defun set-total-master-transcript-operations-processed (count) ...) -- 1/0, commented declareFunction, no body

(defun the-cyclist ()
  *the-cyclist*)

(defun set-the-cyclist (&optional name)
  (let ((fort (map-cyclist-name-to-cyclist-term name)))
    (setf *the-cyclist* fort)
    *the-cyclist*))

(defun map-cyclist-name-to-cyclist-term (name)
  (let ((cyclist-term (if (stringp name)
                          (fi-find-int name)
                          (if (valid-fort? name)
                              name
                              nil))))
    (if (and cyclist-term
             (cyclist? cyclist-term))
        cyclist-term
        #$Guest)))

;; (defun the-cyclist-is-guest? () ...) -- 0/0, commented declareFunction, no body
;;   register-cyc-api-function: (register-cyc-api-function 'the-cyclist-is-guest? nil "Return T iff the current CyclIst is the #$Guest account." nil '((list booleanp)))
;; (defun image-requires-authentication? () ...) -- 0/0, commented declareFunction, no body
;;   register-cyc-api-function: (register-cyc-api-function 'image-requires-authentication? nil "@return non-NIL iff this Cyc image requires authentication." nil '(booleanp))
;; (defun authenticate-the-cyclist (name encrypted-password &optional (application *cyclist-authenticating-app*)) ...) -- 2/1, commented declareFunction, no body
;;   register-cyc-api-function: (register-cyc-api-function 'authenticate-the-cyclist '(name encrypted-password &optional (application *cyclist-authenticating-app*)) "Ensure that the encrypted passphrase ..." '((name stringp) (encrypted-password stringp) (application fort-p)) '(fort-p))
;; (defun lookup-password-for-cyclist-from-kb (cyclist &optional mt) ...) -- 1/1, commented declareFunction, no body
;; (defun get-stored-password-for-cyclist-from-kb (cyclist) ...) -- 1/0, commented declareFunction, no body
;; (defun specify-authentication-info-for-user (cyclist passphrase &optional (application *cyclist-authenticating-app*)) ...) -- 2/1, commented declareFunction, no body
;;   register-cyc-api-function: (register-cyc-api-function 'specify-authentication-info-for-user '(cyclist passphrase &optional (application *cyclist-authenticating-app*)) "Store the authenitcation information ..." '((cyclist fort-p) (passphrase stringp)) '(booleanp stringp))
;; (defun assert-stored-password-for-cyclist-in-kb (cyclist passphrase) ...) -- 2/0, commented declareFunction, no body
;; (defun unassert-stored-password-for-cyclist-in-kb (cyclist) ...) -- 1/0, commented declareFunction, no body
;; (defun kb-op-number () ...) -- 0/0, commented declareFunction, no body

(defun kb-version-string ()
  "[Cyc] Return the current KB version, i.e. both KB number and number of master
transcript operations performed."
  (if (> (read-master-transcript-op-number) 0)
      (format nil "~a.~a" (kb-loaded) (read-master-transcript-op-number))
      (format nil "~a" (kb-loaded))))

;; (defun remote-ops-processed () ...) -- 0/0, commented declareFunction, no body
;; (defun available-communication-modes (&optional mode) ...) -- 0/1, commented declareFunction, no body
;; (defun communication-mode? (keyword) ...) -- 1/0, commented declareFunction, no body
;; (defun communication-mode-name (keyword) ...) -- 1/0, commented declareFunction, no body

(defun communication-mode ()
  "[Cyc] Accessor for *communication-mode*."
  *communication-mode*)

(defun set-communication-mode-internal (mode)
  (setf *communication-mode* mode)
  *communication-mode*)

(defun set-communication-mode (&optional (keyword :receive-only))
  (check-type keyword symbol)
  (when (null (cyc-image-id))
    (set-cyc-image-id))
  (when (not (eq (communication-mode) keyword))
    (when (null (master-transcript))
      (set-master-transcript))
    (when (and *init-file-loaded?*
               (local-transcript))
      (save-transcript-ops))
    (cond
      ((eq keyword :transmit-and-receive)
       ;; missing-larkc 12972: likely set-to-transmit-and-receive, which would
       ;; configure the image for both sending and receiving transcript operations
       (missing-larkc 12972))
      ((eq keyword :transmit-only)
       ;; missing-larkc 12973: likely set-to-transmit-only, which would
       ;; configure the image for sending transcript operations only
       (missing-larkc 12973))
      ((eq keyword :deaf)
       (set-to-deaf))
      ((eq keyword :dead)
       ;; missing-larkc 12968: likely set-to-dead, which would configure
       ;; the image for neither recording nor receiving operations
       (missing-larkc 12968))
      ((eq keyword :dead-receive)
       ;; missing-larkc 12969: likely set-to-dead-receive, which would configure
       ;; the image for receiving but not recording operations
       (missing-larkc 12969))
      (t
       ;; missing-larkc 12970: likely handles the default/unknown communication mode case
       (missing-larkc 12970))))
  (communication-mode))

;; (defun transmit-state-p (state) ...) -- 1/0, commented declareFunction, no body
;; (defun receive-state-p (state) ...) -- 1/0, commented declareFunction, no body
;; (defun set-communication-state (transmit-state receive-state) ...) -- 2/0, commented declareFunction, no body
;; (defun set-transmit-state (state) ...) -- 1/0, commented declareFunction, no body
;; (defun set-receive-state (state) ...) -- 1/0, commented declareFunction, no body
;; (defun set-to-transmitting () ...) -- 0/0, commented declareFunction, no body

(defun set-to-storing ()
  (new-local-transcript)
  (set-process-auxiliary-operations? t)
  (set-saving-operations? t)
  (setf *use-transcript?* t)
  nil)

;; (defun set-to-no-record () ...) -- 0/0, commented declareFunction, no body
;; (defun set-to-receiving () ...) -- 0/0, commented declareFunction, no body

(defun set-to-not-receiving ()
  (set-receiving-remote-operations? nil)
  nil)

(defun transmitting-change? (new-mode)
  "[Cyc] Is the change in communication-mode going to change the way processed
operations are handled?"
  (if (equal (get-transmit-state new-mode)
             (get-transmit-state (communication-mode)))
      nil
      t))

(defun receiving-change? (new-mode)
  "[Cyc] Is the change in communication-mode going to change the receive part of
the mode?"
  (if (equal (get-receive-state new-mode)
             (get-receive-state (communication-mode)))
      nil
      t))

;; (defun set-to-receive-only () ...) -- 0/0, commented declareFunction, no body

(defun set-to-deaf ()
  (when (transmitting-change? :deaf)
    (set-to-storing))
  (when (receiving-change? :deaf)
    (set-to-not-receiving))
  (set-communication-mode-internal :deaf)
  :deaf)

;; (defun set-to-dead () ...) -- 0/0, commented declareFunction, no body
;; (defun set-to-transmit-and-receive () ...) -- 0/0, commented declareFunction, no body
;; (defun set-to-transmit-only () ...) -- 0/0, commented declareFunction, no body
;; (defun set-to-dead-receive () ...) -- 0/0, commented declareFunction, no body

(defun transmitting? ()
  (if (or (equal (communication-mode) :transmit-only)
          (equal (communication-mode) :transmit-and-receive))
      t
      nil))

(defun storing? ()
  (if (or (equal (communication-mode) :deaf)
          (equal (communication-mode) :receive-only))
      t
      nil))

;; (defun not-recording? () ...) -- 0/0, commented declareFunction, no body
;; (defun receiving? () ...) -- 0/0, commented declareFunction, no body

(defun get-transmit-state (&optional (mode (communication-mode)))
  "[Cyc] @return TRANSMIT-STATE-P"
  (let ((state nil))
    (cond
      ((or (eq mode :transmit-and-receive)
           (eq mode :transmit-only))
       (setf state "transmit"))
      ((or (eq mode :deaf)
           (eq mode :receive-only))
       (setf state "store"))
      ((or (eq mode :dead)
           (eq mode :dead-receive))
       (setf state "none"))
      (t
       (setf state nil)))
    state))

(defun get-receive-state (&optional (mode (communication-mode)))
  "[Cyc] @return RECEIVE-STATE-P"
  (let ((state nil))
    (cond
      ((or (eq mode :transmit-and-receive)
           (eq mode :receive-only)
           (eq mode :dead-receive))
       (setf state "yes"))
      ((or (eq mode :deaf)
           (eq mode :transmit-only)
           (eq mode :dead))
       (setf state "no"))
      (t
       (setf state nil)))
    state))

;; (defun get-communication-state (transmit-state receive-state) ...) -- 2/0, commented declareFunction, no body
;; (defun valid-transcript-expression (expression) ...) -- 1/0, commented declareFunction, no body
;; (defun operation-from-me? (operation) ...) -- 1/0, commented declareFunction, no body
;; (defun writing-transcripts? () ...) -- 0/0, commented declareFunction, no body
;; (defun reading-transcripts? () ...) -- 0/0, commented declareFunction, no body
;; (defun clear-stored-operations () ...) -- 0/0, commented declareFunction, no body
;; (defun send-stored-operations () ...) -- 0/0, commented declareFunction, no body
;; (defun fi-save-ops () ...) -- 0/0, commented declareFunction, no body
;; (defun send-local-transcript () ...) -- 0/0, commented declareFunction, no body
;; (defun possibly-save-transcript-ops () ...) -- 0/0, commented declareFunction, no body

(defun save-transcript-ops ()
  (when *hl-transcripts-enabled?*
    ;; missing-larkc 12960: likely save-hl-transcript-ops or similar,
    ;; handles saving HL transcript operations when HL transcripts are enabled
    (missing-larkc 12960))
  (when (not (transcript-queue-empty))
    (bt:with-lock-held (*save-transcript-ops-lock*)
      (save-transcript-ops-internal))
    (return-from save-transcript-ops t))
  nil)

(defun save-transcript-ops-internal (&optional transcript-known-to-exist)
  (declare (ignore transcript-known-to-exist))
  (let ((local-transcript (local-transcript)))
    (with-open-file (stream local-transcript :direction :output
                                             :if-exists :append
                                             :if-does-not-exist :create)
      (unless (streamp stream)
        (error "Unable to open ~S" local-transcript))
      (let ((*print-level* nil)
            (*print-length* nil))
        (loop until (transcript-queue-empty)
              for op = (transcript-queue-dequeue)
              do (when (and (not (dont-record-operations-locally))
                            (storing?))
                   (format stream "~s~%" op)
                   (local-operation-storage-queue-enqueue op)
                   (inc-total-local-operations-recorded))
                 (when (and (allow-transmitting)
                            (transmitting?))
                   ;; missing-larkc 22952: likely transmit-queue-enqueue or similar,
                   ;; queues the operation for transmission to the master transcript
                   (missing-larkc 22952)
                   ;; missing-larkc 12946: likely inc-total-local-operations-transmitted,
                   ;; increments the count of transmitted local operations
                   (missing-larkc 12946))))))
  nil)

;; (defun possibly-save-hl-transcript-ops () ...) -- 0/0, commented declareFunction, no body
;; (defun save-hl-transcript-ops () ...) -- 0/0, commented declareFunction, no body
;; (defun save-hl-transcript-ops-internal () ...) -- 0/0, commented declareFunction, no body
;; (defun close-kb (reason op-number) ...) -- 2/0, commented declareFunction, no body
;; (defun read-one-transcript-operation (stream) ...) -- 1/0, commented declareFunction, no body
;; (defun backup-transcript-stream (stream position) ...) -- 2/0, commented declareFunction, no body
;; (defun load-transcript-exprs () ...) -- 0/0, commented declareFunction, no body
;; (defun load-transcript-exprs-internal () ...) -- 0/0, commented declareFunction, no body

(defun remote-operation-to-run? ()
  "[Cyc] Return T iff there are remote operations available to run."
  (and (receiving-remote-operations?)
       ;; missing-larkc 22949: likely checks if the remote operation queue is non-empty
       ;; (e.g. remote-queue-empty returns T when empty, negated here)
       (not (missing-larkc 22949))))

;; (defun master-transcript-catch-up () ...) -- 0/0, commented declareFunction, no body
;; (defun run-random-transcript-op (operation) ...) -- 1/0, commented declareFunction, no body
;; (defun load-transcript-file (filename &optional start-op end-op run-type verbose?) ...) -- 1/4, commented declareFunction, no body
;; (defun server-summary (&optional stream) ...) -- 0/1, commented declareFunction, no body
;; (defun write-cyc-image (directory &optional minor-version) ...) -- 1/1, commented declareFunction, no body
;; (defun make-cyc-image-filename (&optional directory) ...) -- 0/1, commented declareFunction, no body
;; (defun make-next-cyc-image-filename (directory) ...) -- 1/0, commented declareFunction, no body

;; commented declareFunction, but body present in Java -- ported for reference
(defun halt-cyc-image (&optional (reason "done"))
  "[Cyc] Gracefully halt a running Cyc image"
  (warn "Halting Cyc image : ~A" reason)
  (halt-agenda)
  (when (kb-loaded)
    (save-transcript-ops)
    (mark-local-transcript "QUIT")
    (save-recent-experience)
    (save-recent-asked-queries))
  (sb-ext:exit :code 0)
  nil)

;; (defun get-remote-operations-kb-check-point () ...) -- 0/0, commented declareFunction, no body
;; (defun set-remote-operations-kb-check-point (check-point) ...) -- 1/0, commented declareFunction, no body
;; (defun clear-remote-operations-kb-check-point () ...) -- 0/0, commented declareFunction, no body
;; (defun note-kb-check-point-reached (op-number) ...) -- 1/0, commented declareFunction, no body
;; (defun transmit-kb-check-point-operation (op-number) ...) -- 1/0, commented declareFunction, no body
;; (defun possibly-roll-to-allow-transmitting () ...) -- 0/0, commented declareFunction, no body


;;; Setup phase

(register-external-symbol 'the-cyclist)
(register-external-symbol 'kb-version-string)
