#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

;;; REMOTE-IMAGE defstruct

(defstruct (remote-image (:conc-name "RMT-IMG-")
                         (:print-function print-remote-image))
  machine
  port
  protocol)

;;; REMOTE-IMAGE-CONNECTION defstruct

(defstruct (remote-image-connection (:conc-name "RMT-IMG-CONN-")
                                    (:print-function print-remote-image-connection))
  image
  channel)

;;; Variables

(defconstant *dtp-remote-image* 'remote-image)
(defconstant *dtp-remote-image-connection* 'remote-image-connection)

(defparameter *current-remote-image-connection* nil)

;;; Functions (ordered by declare_remote_image_file)

;; (defun api-channel-remote-eval (channel form &optional timeout) ...) -- active declareFunction, no body

(defun remote-image-print-function-trampoline (object stream)
  "[Cyc] Print function trampoline for REMOTE-IMAGE."
  (declare (ignore object stream))
  (missing-larkc 29985))

(defun remote-image-p (object)
  "[Cyc] Return T if OBJECT is a REMOTE-IMAGE struct."
  (typep object 'remote-image))

;; Struct accessors rmt-img-machine, rmt-img-port, rmt-img-protocol
;; and their _csetf_ setters are generated by defstruct.

(defun make-remote-image (&optional arglist)
  "[Cyc] Construct a REMOTE-IMAGE from keyword arglist."
  (declare (ignore arglist))
  (make-remote-image))

;; (defun print-remote-image (object stream depth) ...) -- active declareFunction, no body

;; (defun new-remote-image (machine port &optional protocol) ...) -- active declareFunction, no body

;; (defun remote-image-machine (image) ...) -- active declareFunction, no body

;; (defun remote-image-port (image) ...) -- active declareFunction, no body

;; (defun remote-image-protocol (image) ...) -- active declareFunction, no body

(defun remote-image-connection-print-function-trampoline (object stream)
  "[Cyc] Print function trampoline for REMOTE-IMAGE-CONNECTION."
  (declare (ignore object stream))
  (missing-larkc 29986))

(defun remote-image-connection-p (object)
  "[Cyc] Return T if OBJECT is a REMOTE-IMAGE-CONNECTION struct."
  (typep object 'remote-image-connection))

;; Struct accessors rmt-img-conn-image, rmt-img-conn-channel
;; and their _csetf_ setters are generated by defstruct.

(defun make-remote-image-connection (&optional arglist)
  "[Cyc] Construct a REMOTE-IMAGE-CONNECTION from keyword arglist."
  (declare (ignore arglist))
  (make-remote-image-connection))

;; (defun print-remote-image-connection (object stream depth) ...) -- active declareFunction, no body

;; (defun new-remote-image-connection (image) ...) -- active declareFunction, no body

;; (defun remote-image-connection-image (connection) ...) -- active declareFunction, no body

;; (defun remote-image-connection-channel (connection) ...) -- active declareFunction, no body

;; (defun open-remote-image-connection (connection) ...) -- active declareFunction, no body

;; (defun close-remote-image-connection (connection) ...) -- active declareFunction, no body

;; (defun remote-image-connection-open? (connection) ...) -- active declareFunction, no body

;; (defun remote-image-connection-closed? (connection) ...) -- active declareFunction, no body

;; (defun remote-image-connection-machine (connection) ...) -- active declareFunction, no body

;; (defun remote-image-connection-port (connection) ...) -- active declareFunction, no body

;; (defun remote-image-connection-protocol (connection) ...) -- active declareFunction, no body

;; (defun reopen-remote-image-connection (connection) ...) -- active declareFunction, no body

;; (defun remote-image-connection-eval (connection form) ...) -- active declareFunction, no body

;;; Macros (reconstructed from Internal Constants evidence)

;; $list43 = (CONNECTION &BODY BODY)
;; Orphan constants: $sym44$CLET, $sym45$*CURRENT-REMOTE-IMAGE-CONNECTION*
;; Reconstruction: binds *current-remote-image-connection* to the given connection
(defmacro with-remote-image-connection ((connection) &body body)
  "[Cyc] Execute BODY with *CURRENT-REMOTE-IMAGE-CONNECTION* bound to CONNECTION."
  `(clet ((*current-remote-image-connection* ,connection))
     ,@body))

;; (defun current-remote-image-connection () ...) -- active declareFunction, no body

;; (defun current-remote-image-connection-eval (form) ...) -- active declareFunction, no body

;; $list46 = (REMOTE-IMAGE &BODY BODY)
;; Orphan constants: $sym47$CONNECTION (unintern), $sym48$NEW_REMOTE_IMAGE_CONNECTION,
;;   $sym49$CUNWIND_PROTECT, $sym50$PROGN, $sym51$OPEN_REMOTE_IMAGE_CONNECTION,
;;   $sym52$WITH_REMOTE_IMAGE_CONNECTION, $sym53$CLOSE_REMOTE_IMAGE_CONNECTION
;; Reconstruction: creates a new connection, opens it, runs body inside with-remote-image-connection, closes on exit
(defmacro with-new-remote-image-connection ((remote-image) &body body)
  "[Cyc] Execute BODY with a new remote image connection to REMOTE-IMAGE, closing on exit."
  (let ((connection (make-symbol "CONNECTION")))
    `(let ((,connection (new-remote-image-connection ,remote-image)))
       (cunwind-protect
         (progn
           (open-remote-image-connection ,connection)
           (with-remote-image-connection (,connection)
             ,@body))
         (close-remote-image-connection ,connection)))))
