#|
  Copyright (c) 2019 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

;; TODO - cyc home seems to be for the cyc project source code, but are worlds supposed to be all held under here?
(deflexical *cyc-home-directory* (asdf:system-source-directory :clyc)
  "[Cyc] The pathname for the cyc home directory (suitable for use with RELATIVE-FILENAME)")

(deflexical *kbs-directory* (merge-pathnames #P"clyc-kbs/" (user-homedir-pathname))
  "[Cyc] The pathname for the kbs directory (suitable for use with RELATIVE-FILENAME)")

(defglobal *available-cyc-features* nil)

;; (defun note-translation-feature (feature) ...) -- active declareFunction, no body

;; Reconstructed from Internal Constants:
;; $sym3$NOTE_TRANSLATION_FEATURE, $sym4$PROGN
(defmacro note-translation-features (&body features)
  `(progn ,@(mapcar (lambda (f) `(note-translation-feature ',f)) features)))

;; TODO - $list5 = (FEATURE) is the arglist. No visible expansions found;
;; the cyc-*-feature functions were likely generated by this macro but their
;; bodies were stripped by LarKC. Cannot reconstruct body confidently.
(defmacro check-for-feature (feature)
  (declare (ignore feature))
  nil)

;; (defun cyc-html-feature () ...) -- active declareFunction, no body
;; (defun cyc-date-feature () ...) -- active declareFunction, no body
;; (defun cyc-quant-feature () ...) -- active declareFunction, no body
;; (defun cyc-pph-feature () ...) -- active declareFunction, no body
;; (defun cyc-lexicon-feature () ...) -- active declareFunction, no body
;; (defun cyc-nl-feature () ...) -- active declareFunction, no body
;; (defun cyc-hpsg-feature () ...) -- active declareFunction, no body
;; (defun cyc-external-feature () ...) -- active declareFunction, no body
;; (defun cyc-wordnet-feature () ...) -- active declareFunction, no body
;; (defun cyc-retrieval-feature () ...) -- active declareFunction, no body
;; (defun cyc-thesaurus-feature () ...) -- active declareFunction, no body
;; (defun cyc-maint-feature () ...) -- active declareFunction, no body
;; (defun cyc-secure-feature () ...) -- active declareFunction, no body
;; (defun cyc-hitek-feature () ...) -- active declareFunction, no body
;; (defun cyc-hpkb-feature () ...) -- active declareFunction, no body
;; (defun cyc-qa-feature () ...) -- active declareFunction, no body
;; (defun cyc-kbi-feature () ...) -- active declareFunction, no body
(defun cyc-opencyc-feature () nil)
;; (defun cyc-researchcyc-feature () ...) -- active declareFunction, no body
;; (defun cyc-sksi-feature () ...) -- active declareFunction, no body

;; (defun matches-execution-context-p (context) ...) -- active declareFunction, no body
;; (defun cycorp-execution-context-p () ...) -- active declareFunction, no body

(defun cyc-revision-string ()
  "[Cyc] Returns the current Cyc revision numbers expressed as a period-delimited string"
  *cyc-revision-string*)

;; (defun cyc-revision-string-s1p-format () ...) -- active declareFunction, no body

(defun cyc-revision-numbers ()
  "[Cyc] Returns a list of the current Cyc revision numbers"
  *cyc-revision-numbers*)

(defglobal *cycl-start-time* nil)

(defun reset-cycl-start-time (&optional (universal-time (get-universal-time)))
  (setf *cycl-start-time* universal-time))

;; (defun cycl-start-time () ...) -- active declareFunction, no body
;; (defun cycl-uptime () ...) -- active declareFunction, no body

(defglobal *subl-initial-continuation* nil
  "[Cyc] Backpointer for the original SubL initial continuation.")

;; (defun cyc-initial-continuation (kb-size kb-number agenda-allowed? read-everything?) ...) -- active declareFunction, no body
;; (defun cyc-initialization () ...) -- active declareFunction, no body

;;; Setup phase

(toplevel
  (register-external-symbol 'cyc-revision-string)
  (register-external-symbol 'cyc-revision-string-s1p-format)
  (register-external-symbol 'cyc-revision-numbers)
  (declare-defglobal '*cycl-start-time*)
  (register-external-symbol 'cycl-start-time)
  (declare-defglobal '*subl-initial-continuation*))
