#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#


(in-package :clyc)

;; Reconstructed from Internal Constants:
;; $list0 = ((CACHE BIN-PRED) &BODY BODY), $sym1 = PRED-CACHES (unintern gensym),
;; $sym2 = DO-DICTIONARY, $list3 = ((TVA-CACHE-REGISTRY)), $sym4 = CDOLIST
(defmacro do-tva-caches ((cache bin-pred) &body body)
  "[Cyc] Iterate over all TVA caches in the registry, binding BIN-PRED to each
predicate and CACHE to each cache for that predicate."
  (with-temp-vars (pred-caches)
    `(do-dictionary (,bin-pred ,pred-caches (tva-cache-registry))
       (dolist (,cache ,pred-caches)
         ,@body))))

;; Reconstructed from Internal Constants:
;; $list5 = ((KEY RAW-SUPPORTED-VALUES SUPPORTED-SUBKEYS CACHE) &BODY BODY),
;; $sym6 = ENTRY (unintern gensym), $sym7 = DO-MAP, $sym8 = TVA-CACHE-MAP,
;; $sym9 = CDESTRUCTURING-BIND, $list18 = (KEY #:ENTRY),
;; $list19 = (RAW-SUPPORTED-VALUES . SUPPORTED-SUBKEYS)
(defmacro do-tva-cache ((key raw-supported-values supported-subkeys cache) &body body)
  "[Cyc] Iterate over the entries of a TVA CACHE's map, destructuring each entry
into KEY, RAW-SUPPORTED-VALUES, and SUPPORTED-SUBKEYS."
  (with-temp-vars (entry)
    `(maphash (lambda (,key ,entry)
                (destructuring-bind (,raw-supported-values . ,supported-subkeys) ,entry
                  ,@body))
              (tva-cache-map ,cache))))

;; (defun tva-cache-get-values (key cache inverse? done?) ...) -- commented declareFunction (4 0), no body
;; (defun tva-cache-check-value (key cache inverse? done? &optional arg5 arg6) ...) -- commented declareFunction (4 2), no body

(defun tva-cache-predicate-index-arg-cached-p (predicate index-arg)
  "[Cyc] Return whether a TVA cache exists for PREDICATE at INDEX-ARG."
  (not (null (tva-cache-for-predicate-and-index-argnum predicate index-arg))))

;; (defun initialize-tva-caches () ...) -- commented declareFunction (0 0), no body
;; (defun initialize-uninitialized-tva-caches () ...) -- commented declareFunction (0 0), no body
;; (defun initialize-tva-caches-int (flag) ...) -- commented declareFunction (1 0), no body

(defun tva-cache-enabled-p ()
  "[Cyc] Return whether TVA caching is enabled."
  (not (null *use-tva-cache?*)))

;; (defun cached-tva-value-count () ...) -- commented declareFunction (0 0), no body

;; --- defstruct tva-cache ---

(defstruct (tva-cache (:print-function tva-cache-print-function-trampoline))
  "[Cyc] TVA cache structure."
  pred
  index-argnum
  tva-pred-gafs
  tvai-pred-gafs
  map)

(defun tva-cache-print-function-trampoline (object stream depth)
  "[Cyc] Print function trampoline for tva-cache."
  (declare (ignore object stream depth))
  (missing-larkc 3819))

;; tva-cache-p — generated by defstruct
;; tva-cache-pred — generated by defstruct
;; tva-cache-index-argnum — generated by defstruct (active declareFunction)
;; tva-cache-tva-pred-gafs — generated by defstruct
;; tva-cache-tvai-pred-gafs — generated by defstruct
;; tva-cache-map — generated by defstruct
;; _csetf-* accessors — generated by defstruct as setf methods
;; make-tva-cache — generated by defstruct

(defun sxhash-tva-cache-method (object)
  "[Cyc] Sxhash method for tva-cache."
  (declare (ignore object))
  (sxhash (missing-larkc 3867)))

;; (defun pprint-tva-cache (object &optional stream depth) ...) -- commented declareFunction (1 2), no body
;; (defun clone-swappable-tva-cache (cache fvector) ...) -- commented declareFunction (2 0), no body
;; (defun reconnect-swappable-tva-cache (cache fvector &optional common-symbols) ...) -- commented declareFunction (2 1), no body

(defun tva-cache-registry ()
  "[Cyc] Return the TVA cache registry."
  *tva-cache-registry*)

;; (defun register-tva-cache (cache) ...) -- commented declareFunction (1 0), no body

(defun tva-caches-for-predicate (predicate)
  "[Cyc] Return the list of TVA caches registered for PREDICATE."
  (gethash predicate (tva-cache-registry)))

(defun tva-caches-implied-by-predicate (predicate)
  "[Cyc] @return LISTP of TVA caches that represent facts implied by PREDICATE."
  (let ((caches nil)
        (inverse-caches nil))
    (let ((*relevant-mt-function* #'relevant-mt-is-any-mt)
          (*mt* #$InferencePSC))
      (let* ((module (get-sbhl-module #$genlPreds))
             (node-var predicate)
             (recur-deck (create-deck :queue))
             (node-and-predicate-mode nil))
        (let ((*sbhl-space* (get-sbhl-marking-space)))
          (let* ((tv-var #$True-JustificationTruth)
                 (*sbhl-tv* (or tv-var (get-sbhl-true-tv)))
                 (*relevant-sbhl-tv-function* (if tv-var
                                                  #'relevant-sbhl-tv-is-general-tv
                                                  *relevant-sbhl-tv-function*)))
            (when tv-var
              (when (sbhl-object-type-checking-p)
                (unless (sbhl-true-tv-p tv-var)
                  (let ((pcase-var *sbhl-type-error-action*))
                    (cond
                      ((eql pcase-var :error)
                       (sbhl-error 1 "~A is not a ~A" tv-var 'sbhl-true-tv-p))
                      ((eql pcase-var :cerror)
                       (missing-larkc 2231))
                      ((eql pcase-var :warn)
                       (warn "~A is not a ~A" tv-var 'sbhl-true-tv-p))
                      (t
                       (warn "~A is not a valid *sbhl-type-error-action* value"
                             *sbhl-type-error-action*)
                       (cerror "continue anyway" "~A is not a ~A"
                               tv-var 'sbhl-true-tv-p)))))))
            (let ((*sbhl-search-module* module)
                  (*sbhl-search-module-type* (get-sbhl-module-type module))
                  (*sbhl-add-node-to-result-test* (get-sbhl-add-node-to-result-test module))
                  (*genl-inverse-mode-p* nil)
                  (*sbhl-module* module))
              (if (or (suspend-sbhl-type-checking?)
                      (apply-sbhl-module-type-test predicate (get-sbhl-module)))
                  (let ((*sbhl-search-direction* (get-sbhl-forward-search-direction))
                        (*sbhl-link-direction* (sbhl-search-direction-to-link-direction
                                                (get-sbhl-forward-search-direction) module))
                        (*genl-inverse-mode-p* nil))
                    (sbhl-mark-node-marked node-var)
                    (setf node-and-predicate-mode (list predicate (genl-inverse-mode-p)))
                    (loop while node-and-predicate-mode do
                      (let* ((node-var-16 (first node-and-predicate-mode))
                             (predicate-mode (second node-and-predicate-mode))
                             (genl-pred node-var-16))
                        (let ((*genl-inverse-mode-p* predicate-mode))
                          (let ((inverse? predicate-mode))
                            (dolist (v-cache (tva-caches-for-predicate genl-pred))
                              (if inverse?
                                  (push v-cache inverse-caches)
                                  (push v-cache caches))))
                          (dolist (module-var (get-sbhl-accessible-modules module))
                            (let ((*sbhl-module* module-var)
                                  (*genl-inverse-mode-p*
                                    (if (flip-genl-inverse-mode?)
                                        (not *genl-inverse-mode-p*)
                                        *genl-inverse-mode-p*)))
                              (let ((node (naut-to-nart node-var-16)))
                                (if (sbhl-node-object-p node)
                                    (let ((d-link (get-sbhl-graph-link node (get-sbhl-module))))
                                      (if d-link
                                          (let ((mt-links (get-sbhl-mt-links d-link
                                                                             (get-sbhl-link-direction)
                                                                             (get-sbhl-module))))
                                            (when mt-links
                                              (maphash
                                               (lambda (mt tv-links)
                                                 (when (relevant-mt? mt)
                                                   (let ((*sbhl-link-mt* mt))
                                                     (maphash
                                                      (lambda (tv link-nodes)
                                                        (when (relevant-sbhl-tv? tv)
                                                          (let ((*sbhl-link-tv* tv))
                                                            (let ((new-list
                                                                    (if (sbhl-randomize-lists-p)
                                                                        (missing-larkc 9332)
                                                                        link-nodes)))
                                                              (dolist (node-vars-link-node new-list)
                                                                (unless (sbhl-search-path-termination-p
                                                                         node-vars-link-node)
                                                                  (sbhl-mark-node-marked
                                                                   node-vars-link-node)
                                                                  (deck-push
                                                                   (list node-vars-link-node
                                                                         (genl-inverse-mode-p))
                                                                   recur-deck)))))))
                                                      tv-links))))
                                               mt-links)))
                                          (sbhl-error 5 "attempting to bind direction link variable, to NIL. macro body not executed.")))
                                    (when (cnat-p node)
                                      (let ((new-list (if (sbhl-randomize-lists-p)
                                                          (missing-larkc 9333)
                                                          (missing-larkc 2715))))
                                        (dolist (generating-fn new-list)
                                          (let ((*sbhl-link-generator* generating-fn))
                                            (let ((link-nodes (funcall generating-fn node)))
                                              (let ((new-list-26
                                                      (if (sbhl-randomize-lists-p)
                                                          (missing-larkc 9334)
                                                          link-nodes)))
                                                (dolist (node-vars-link-node new-list-26)
                                                  (unless (sbhl-search-path-termination-p
                                                           node-vars-link-node)
                                                    (sbhl-mark-node-marked node-vars-link-node)
                                                    (deck-push
                                                     (list node-vars-link-node
                                                           (genl-inverse-mode-p))
                                                     recur-deck))))))))))))))
                      (setf node-and-predicate-mode (deck-pop recur-deck))))
                  (sbhl-warn 2 "Node ~a does not pass sbhl-type-test ~a~%"
                             predicate (get-sbhl-type-test (get-sbhl-module)))))))
          (free-sbhl-marking-space *sbhl-space*))))
    (values caches inverse-caches)))

;; (defun tva-caches-with-transitive-predicate (predicate) ...) -- commented declareFunction (1 0), no body

(defun tva-cache-for-predicate-and-index-argnum (predicate index-argnum)
  "[Cyc] Return the TVA cache for PREDICATE with INDEX-ARGNUM."
  (find index-argnum (tva-caches-for-predicate predicate)
        :test #'eql :key #'tva-cache-index-argnum))

;; (defun ensure-tva-cache-created (predicate index-argnum) ...) -- commented declareFunction (2 0), no body
;; (defun deregister-tva-cache (cache &optional predicate) ...) -- commented declareFunction (1 1), no body
;; (defun deregister-all-tva-caches-for-predicate (predicate) ...) -- commented declareFunction (1 0), no body

;; TODO - macro DO-TVA-SUB-CACHES
;; Arglist: ((sub-cache cache inverse? &key done?) &body body)
;; Evidence from Internal Constants:
;;   $list65 = ((SUB-CACHE CACHE INVERSE? &KEY DONE?) &BODY BODY)
;;   $list66 = (:DONE?), $kw67 = :ALLOW-OTHER-KEYS, $kw68 = :DONE?
;;   $sym69 = SPEC-PRED (makeUninternedSymbol — template var)
;;   $sym70 = DO-ALL-SPEC-PREDICATES-AND-INVERSES — unported macro from genl-predicates
;;   $sym71 = CLET, $sym72 = FIF, $sym73 = FIND-TVA-SUB-CACHE (commented stub in this file)
;; Cannot reconstruct reliably: do-all-spec-predicates-and-inverses arglist/bindings
;; unknown, FIF dispatch target unclear, done? integration uncertain.

;; (defun find-tva-sub-cache (cache predicate inverse?) ...) -- commented declareFunction (3 0), no body
;; (defun tva-cache-lookup (cache key &optional inverse? done? arg5) ...) -- commented declareFunction (2 3), no body
;; (defun tva-cache-lookup-recursive (cache key inverse? done? arg5 arg6) ...) -- commented declareFunction (6 0), no body
;; (defun cleanup-tva-cache-supports-genl-preds-chains (supports) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-entry-for-key (cache key) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-lookup-internal (cache key inverse? done? arg5 arg6) ...) -- commented declareFunction (6 0), no body
;; (defun tva-cache-has-key? (cache key) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-valid-support?-internal (support) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-valid-support? (support) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-support-gaf (support) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-support-equal? (support1 support2) ...) -- commented declareFunction (2 0), no body
;; (defun unpack-and-validate-tva-cache-support (support cache &optional inverse?) ...) -- commented declareFunction (2 1), no body
;; (defun unpack-and-validate-tva-cache-complex-support (support cache &optional inverse?) ...) -- commented declareFunction (2 1), no body

(defun add-tva-cache-value (argument assertion)
  "[Cyc] We've just added a new key->value support to the KB."
  (declare (ignore argument))
  (destructuring-bind (bin-pred arg1 arg2)
      (formula-terms (gaf-hl-formula assertion))
    (declare (ignore arg1 arg2))
    (multiple-value-bind (caches inverse-caches)
        (tva-caches-implied-by-predicate bin-pred)
      (let ((mt-var (with-inference-mt-relevance-validate (assertion-mt assertion))))
        (let ((*mt* (update-inference-mt-relevance-mt mt-var))
              (*relevant-mt-function* (update-inference-mt-relevance-function mt-var))
              (*relevant-mts* (update-inference-mt-relevance-mt-list mt-var)))
          (dolist (v-cache caches)
            (let ((pcase-var (tva-cache-index-argnum v-cache)))
              (cond
                ((eql pcase-var 1) (missing-larkc 3889))
                ((eql pcase-var 2) (missing-larkc 3890)))))
          (dolist (v-cache inverse-caches)
            (let ((pcase-var (tva-cache-index-argnum v-cache)))
              (cond
                ((eql pcase-var 2) (missing-larkc 3891))
                ((eql pcase-var 1) (missing-larkc 3892)))))))))
  nil)

(defun remove-tva-cache-value (argument assertion)
  "[Cyc] We're about to remove a key->value support from the KB."
  (declare (ignore argument))
  (destructuring-bind (bin-pred arg1 arg2)
      (formula-terms (gaf-hl-formula assertion))
    (declare (ignore arg1 arg2))
    (multiple-value-bind (caches inverse-caches)
        (tva-caches-implied-by-predicate bin-pred)
      (let ((mt-var (with-inference-mt-relevance-validate (assertion-mt assertion))))
        (let ((*mt* (update-inference-mt-relevance-mt mt-var))
              (*relevant-mt-function* (update-inference-mt-relevance-function mt-var))
              (*relevant-mts* (update-inference-mt-relevance-mt-list mt-var)))
          (dolist (v-cache caches)
            (let ((pcase-var (tva-cache-index-argnum v-cache)))
              (cond
                ((eql pcase-var 1) (missing-larkc 3872))
                ((eql pcase-var 2) (missing-larkc 3873)))))))
      ;; Note: inverse-caches loop is OUTSIDE with-inference-mt-relevance (matches Java)
      (dolist (v-cache inverse-caches)
        (let ((pcase-var (tva-cache-index-argnum v-cache)))
          (cond
            ((eql pcase-var 2) (missing-larkc 3874))
            ((eql pcase-var 1) (missing-larkc 3875)))))))
  nil)

;; (defun add-tva-cache-key (argument assertion) ...) -- commented declareFunction (2 0), no body
;; (defun remove-tva-cache-key (argument assertion) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-add-transitive-via-arg (assertion) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-add-transitive-via-arg-inverse (assertion) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-remove-transitive-via-arg (assertion) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-remove-transitive-via-arg-inverse (assertion) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-add-trans-gaf (cache key value inverse?) ...) -- commented declareFunction (4 0), no body
;; (defun create-tva-cache (predicate index-argnum &optional initialize?) ...) -- commented declareFunction (2 1), no body
;; (defun initialize-tva-cache (cache) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-asserted-values (cache) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-relation-all-instance-values (cache) ...) -- commented declareFunction (1 0), no body
;; (defun clear-tva-cache-max-instances-to-cache () ...) -- commented declareFunction (0 0), no body
;; (defun remove-tva-cache-max-instances-to-cache () ...) -- commented declareFunction (0 0), no body
;; (defun tva-cache-max-instances-to-cache-internal () ...) -- commented declareFunction (0 0), no body
;; (defun tva-cache-max-instances-to-cache () ...) -- commented declareFunction (0 0), no body
;; (defun tva-cache-add-one-relation-all-instance-gaf (cache gaf) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-add-relation-instance-all-gaf (gaf) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-add-relation-all-instance-gaf (gaf) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-remove-relation-all-instance-gaf (gaf) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-remove-one-relation-all-instance-gaf (cache gaf) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-remove-relation-instance-all-gaf (gaf) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-remove-one-relation-instance-all-gaf (cache gaf) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-relation-instance-all-values (cache) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-add-one-relation-instance-all-gaf (cache gaf) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-silent-progress? (cache count total) ...) -- commented declareFunction (3 0), no body
;; (defun tva-cache-store-one-gaf (cache key value inverse? gaf) ...) -- commented declareFunction (5 0), no body
;; (defun tva-cache-store-one-value (cache entry) ...) -- commented declareFunction (2 0), no body
;; (defun make-tva-cache-complex-support (supports) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-support-component-supports (support) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-support-complex-p (support) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-complex-support-equal? (support1 support2) ...) -- commented declareFunction (2 0), no body
;; (defun make-tva-cache-support (type gaf &optional specified-pred arg4) ...) -- commented declareFunction (4 0), no body
;; (defun tva-cache-ensure-cache-has-key (cache key) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-add-key (cache key) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-note-implicit-keys-from-trans-gaf (cache key value &optional arg4 arg5) ...) -- commented declareFunction (3 2), no body
;; (defun tva-cache-get-implicit-terms (cache key value inverse?) ...) -- commented declareFunction (4 0), no body
;; (defun tva-cache-get-implicit-terms-internal (cache key value inverse? arg5 &optional arg6) ...) -- commented declareFunction (5 1), no body
;; (defun make-tva-cache-hl-support (arg1 &optional arg2 arg3) ...) -- commented declareFunction (1 2), no body
;; (defun tva-cache-tva-pred-from-support (support) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-transitivity-support (arg1 arg2 &optional arg3) ...) -- commented declareFunction (2 1), no body
;; (defun new-tva-cache-entry () ...) -- commented declareFunction (0 0), no body
;; (defun tva-cache-note-key-value-supports (cache key value supports) ...) -- commented declareFunction (4 0), no body
;; (defun tva-cache-implied-values (cache key) ...) -- commented declareFunction (2 0), no body
;; (defun tva-cache-transitive-binary-predicate-support (predicate) ...) -- commented declareFunction (1 0), no body
;; (defun tva-cache-note-implicit-key-supports (cache key value supports) ...) -- commented declareFunction (4 0), no body
;; (defun tva-cache-remove-key-value-support (cache key value support) ...) -- commented declareFunction (4 0), no body
;; (defun tva-cache-remove-implicit-key-support (cache key value support) ...) -- commented declareFunction (4 0), no body
;; (defun invert-binary-argnum (argnum) ...) -- commented declareFunction (1 0), no body

(defun cfasl-output-object-tva-cache-method (object stream)
  "[Cyc] CFASL output method for tva-cache."
  (declare (ignore object stream))
  (missing-larkc 3785))

;; (defun cfasl-output-tva-cache (cache stream) ...) -- commented declareFunction (2 0), no body
;; (defun cfasl-input-tva-cache (stream) ...) -- commented declareFunction (1 0), no body

(defun tva-cache-unbuilt? ()
  "[Cyc] Return whether the TVA cache registry has not been built."
  (let ((result nil))
    (let ((*relevant-mt-function* #'relevant-mt-is-any-mt)
          (*mt* #$InferencePSC))
      (setf result (or (not (map-p *tva-cache-registry*))
                       (and (map-empty-p *tva-cache-registry*)
                            (> (num-predicate-extent-index #$cacheTransitiveClosureForArgs)
                               0)))))
    result))

;; (defun rebuild-tva-cache () ...) -- commented declareFunction (0 0), no body

(defun get-tva-cache-contents-data-file (&optional directory-path)
  "[Cyc] Return the TVA cache contents data file path."
  (kb-dump-file "tva-cache-contents" directory-path))

(defun get-tva-cache-contents-index-file (&optional directory-path)
  "[Cyc] Return the TVA cache contents index file path."
  (kb-dump-file "tva-cache-contents-index" directory-path))

(defun reconnect-tva-cache-registry (directory common-symbols)
  "[Cyc] Helper method for system KB initializations code."
  (let ((data-file (get-tva-cache-contents-data-file directory))
        (index-file (get-tva-cache-contents-index-file directory)))
    (reconnect-tva-cache-registry-to-file-vector-files data-file index-file common-symbols)))

(defun reconnect-tva-cache-registry-to-file-vector-files (data-file index-file
                                                          &optional (common-symbols
                                                                     (cfasl-current-common-symbols)))
  "[Cyc] Walks the TVA cache registry and reconnects all of the TVA caches registered."
  (declare (ignore common-symbols))
  (let ((valid-files (and (file-exists? data-file) (file-exists? index-file))))
    (if valid-files
        (let ((fvector (new-file-vector data-file index-file))
              (iterator (new-map-iterator *tva-cache-registry*)))
          (declare (ignore fvector))
          (loop
            (multiple-value-bind (entry valid) (iteration-next iterator)
              (unless valid (return))
              (destructuring-bind (key tva-caches) entry
                (declare (ignore key))
                (dolist (v-tva-cache tva-caches)
                  (declare (ignore v-tva-cache))
                  (missing-larkc 3823))))))
        (warn "Reconnecting to legacy unit files w/out TVA cache contents in ~A and ~A."
              data-file index-file))
    valid-files))

;; (defun dump-swappable-tva-cache-to-stream (cache stream) ...) -- commented declareFunction (2 0), no body
;; (defun dump-tva-cache-to-stream (stream) ...) -- commented declareFunction (1 0), no body

(defun load-tva-cache-from-stream (stream)
  "[Cyc] Load the TVA cache from STREAM."
  (setf *tva-cache-registry* (cfasl-input stream))
  nil)

;; Variables — init phase

(defparameter *use-tva-cache?* t
  "[Cyc] Whether to use the TVA cache.")

(defglobal *tva-cache-registry* (make-hash-table :test #'eql)
  "[Cyc] DICTIONARY-P mapping binary predicates to their TVA-CACHE-P objects.")

(defparameter *tva-cache-assume-supports-are-valid?* nil)

(deflexical *tva-cache-max-instances-to-cache-caching-state* nil)

(defconstant *cfasl-opcode-tva-cache* 96)

;; Setup phase

(toplevel
  (note-memoized-function 'tva-cache-valid-support?)
  (register-kb-function 'add-tva-cache-value)
  (register-kb-function 'remove-tva-cache-value)
  (register-kb-function 'add-tva-cache-key)
  (register-kb-function 'remove-tva-cache-key)
  (note-globally-cached-function 'tva-cache-max-instances-to-cache)
  (register-cfasl-input-function *cfasl-opcode-tva-cache* 'cfasl-input-tva-cache)
  (defmethod cfasl-output-object ((object tva-cache) stream)
    (cfasl-output-object-tva-cache-method object stream))
  (define-obsolete-register 'dump-tva-cache-to-stream '(dump-swappable-tva-cache-to-stream)))
