#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

(defparameter *hl-prototypes-enabled?* t)

(defparameter *gather-hl-prototype-statistics?* t)

(defglobal *hl-prototype-hits* 0)

(defglobal *hl-prototype-hit-table* (make-hash-table :test #'eq))

(defglobal *hl-prototype-misses* 0)

(defun hl-prototypes-enabled? ()
  (and *hl-prototypes-enabled?*
       (valid-constant? #$hlPrototypicalInstance)
       (valid-constant? #$HLPrototypicalTerm)))

(defun hl-prototype-allowed-forward-rules (assertions-found-or-created)
  (when (hl-prototypes-enabled?)
    (when (singleton? assertions-found-or-created)
      (let ((assertion (first assertions-found-or-created)))
        (when (possibly-hl-prototype-assertion? assertion)
          (let* ((col (gaf-arg2 assertion))
                 (prototypical-instance (find-or-create-hl-prototypical-instance col))
                 (rules (relevant-hl-prototype-rules prototypical-instance)))
            (when *gather-hl-prototype-statistics?*
              (incf *hl-prototype-hits*)
              (dictionary-increment *hl-prototype-hit-table* col))
            (return-from hl-prototype-allowed-forward-rules rules))))))
  (when *gather-hl-prototype-statistics?*
    (incf *hl-prototype-misses*))
  (forward-inference-allowed-rules))

(defun hl-prototypical-instance-after-adding (assertion argument)
  (declare (ignore assertion argument))
  nil)

;; (defun hl-prototypical-instance-after-removing (assertion argument) ...) -- active declareFunction, no body

(defun-cached the-hl-prototype-ke-irrelevant-rule () (:test eq)
  "[Cyc] The CNF of the forward rule that implements #$keIrrelevantTerm for HL prototypical instances.
We don't want to include this in the forward inference allowed rules."
  (find-assertion (list (list (list* #$quotedIsa
                                     (find-variable-by-id 0)
                                     (list #$HLPrototypicalTerm)))
                        (list (list #$keIrrelevantTerm
                                    (find-variable-by-id 0))))
                  #$UniversalVocabularyMt))

;; remove-the-hl-prototype-ke-irrelevant-rule is not generated by defun-cached
;; (defun remove-the-hl-prototype-ke-irrelevant-rule () ...) -- active declareFunction, no body

(defun relevant-hl-prototype-rules (term)
  (let ((rules (all-forward-rules-relevant-to-term term)))
    (remove (the-hl-prototype-ke-irrelevant-rule) rules :test #'eq)))

;; (defun clear-hl-prototype-caches () ...) -- active declareFunction, no body

(defun possibly-hl-prototype-assertion? (assertion)
  "[Cyc] Return booleanp; whether ASSERTION is of the form (#$isa NEW-TERM COL),
where NEW-TERM has no assertions other than ASSERTION, and COL is an HL prototype collection."
  (when (gaf-assertion-with-pred-p assertion #$isa)
    (let ((mt (assertion-mt assertion)))
      (when (or (eq mt *anect-mt*)
                (eq mt *core-mt-floor*))
        (let ((new-term (gaf-arg1 assertion)))
          (when (onep (num-index new-term))
            t))))))

(defun find-or-create-hl-prototypical-instance (col &optional (use-transcript? nil))
  (let ((prototypical-instance (hl-prototypical-instance col)))
    (if prototypical-instance
        prototypical-instance
        (create-hl-prototypical-instance col use-transcript?))))

(defun hl-prototypical-instance (col)
  "[Cyc] Return constant-p; the constant denoting the prototypical instance of COL."
  (fpred-value col #$hlPrototypicalInstance 2 1))

(defun create-hl-prototypical-instance (col &optional (use-transcript? nil))
  "[Cyc] Return constant-p; a newly created prototypical instance of COL."
  (let* ((name (hl-prototypical-instance-name col))
         (v-const (if use-transcript?
                      (ke-create-now name)
                      (cyc-create-new-ephemeral name)))
         (environment (get-forward-inference-environment)))
    (declare (type queue environment))
    (let ((*forward-inference-environment* environment)
          (*hl-prototypes-enabled?* nil))
      (let ((*forward-inference-allowed-rules*
              (non-null-answer-to-singleton (the-hl-prototype-ke-irrelevant-rule))))
        (if use-transcript?
            (ke-assert-now (list* #$quotedIsa v-const (list #$HLPrototypicalTerm))
                           *anect-mt*)
            (cyc-assert-wff (list* #$quotedIsa v-const (list #$HLPrototypicalTerm))
                            *anect-mt*)))
      (let ((*forward-inference-allowed-rules* nil))
        (if use-transcript?
            (ke-assert-now (list #$hlPrototypicalInstance v-const col) *anect-mt*)
            (cyc-assert-wff (list #$hlPrototypicalInstance v-const col) *anect-mt*)))
      (let ((*forward-inference-allowed-rules* :all))
        (if use-transcript?
            (ke-assert-now (list #$isa v-const col) *anect-mt*)
            (cyc-assert-wff (list #$isa v-const col) *anect-mt*))))
    v-const))

(defun hl-prototypical-instance-name (col)
  (make-valid-constant-name (concatenate 'string "ThePrototypical" (fort-name col))))

;; (defun hl-prototype-collections () ...) -- active declareFunction, no body
;; (defun hl-prototypical-collection (term) ...) -- active declareFunction, no body
;; (defun hl-prototypical-instance? (term) ...) -- active declareFunction, no body
;; (defun show-hl-prototype-statistics () ...) -- active declareFunction, no body
;; (defun clear-hl-prototype-statistics () ...) -- active declareFunction, no body
;; (defun create-hl-prototypical-instances-for-common-collections (n &optional use-transcript?) ...) -- active declareFunction, no body
;; (defun n-most-useful-hl-prototype-collections (n &optional include-existing?) ...) -- active declareFunction, no body
;; (defun most-useful-hl-prototypical-instances-dict () ...) -- active declareFunction, no body
;; (defun likely-first-asserted-isa-col (term) ...) -- active declareFunction, no body
;; (defun likely-first-asserted-isa-gaf (term) ...) -- active declareFunction, no body

(toplevel
  (declare-defglobal '*hl-prototype-hits*)
  (declare-defglobal '*hl-prototype-hit-table*)
  (declare-defglobal '*hl-prototype-misses*)
  (register-kb-function 'hl-prototypical-instance-after-adding)
  (register-kb-function 'hl-prototypical-instance-after-removing))
;; note-globally-cached-function for the-hl-prototype-ke-irrelevant-rule is generated by defun-cached
