#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

;;; inference-metric struct
;;; print-object is missing-larkc 36325 — CL's default print-object handles this.

(defstruct (inference-metric (:conc-name "INF-METRIC-"))
  name
  evaluation-func
  evaluation-arg1
  cross-product?)

(defconstant *dtp-inference-metric* 'inference-metric)

;;; Functions — following declare_inference_metrics_file() ordering

;; (defun inference-metric-evaluation-arg1-p (object) ...) -- active declareFunction, no body

;; inference-metric-p generated by defstruct
;; inf-metric-name, inf-metric-evaluation-func, inf-metric-evaluation-arg1,
;; inf-metric-cross-product? generated by defstruct
;; _csetf-* generated by defstruct
;; make-inference-metric generated by defstruct

;; (defun print-inference-metric (metric stream depth) ...) -- active declareFunction, no body

(defun new-inference-metric (name evaluation-func evaluation-arg1 cross-product?)
  (declare (type keyword name)
           (type symbol evaluation-func))
  (let ((metric (make-inference-metric)))
    (setf (inf-metric-name metric) name)
    (setf (inf-metric-evaluation-func metric) evaluation-func)
    (setf (inf-metric-evaluation-arg1 metric) evaluation-arg1)
    (setf (inf-metric-cross-product? metric) cross-product?)
    metric))

;; (defun inference-metric-name (metric) ...) -- active declareFunction, no body
;; (defun inference-metric-evaluation-func (metric) ...) -- active declareFunction, no body
;; (defun inference-metric-evaluation-arg1 (metric) ...) -- active declareFunction, no body
;; (defun inference-metric-cross-product? (metric) ...) -- active declareFunction, no body
;; (defun inference-metric-evaluate (metric problem-store inference) ...) -- active declareFunction, no body
;; (defun inference-metric-property-p (object) ...) -- active declareFunction, no body

(defun declare-inference-metric (name evaluation-func evaluation-arg1 &optional cross-product?)
  (let ((metric (new-inference-metric name evaluation-func evaluation-arg1 cross-product?)))
    (setf (gethash name *inference-metrics-store*) metric)
    metric))

;; (defun inference-metric-lookup (name) ...) -- active declareFunction, no body
;; (defun inference-metric-name? (name) ...) -- active declareFunction, no body
;; (defun inference-metric-names () ...) -- active declareFunction, no body

;;; Historical counters

;; problem-store counters

(defglobal *problem-store-historical-count* 0)

;; (defun problem-store-historical-count () ...) -- active declareFunction, no body

(defun increment-problem-store-historical-count ()
  (incf *problem-store-historical-count*))

(defglobal *forward-problem-store-historical-count* 0)

;; (defun forward-problem-store-historical-count () ...) -- active declareFunction, no body
;; (defun backward-problem-store-historical-count () ...) -- active declareFunction, no body

(defun increment-forward-problem-store-historical-count ()
  (incf *forward-problem-store-historical-count*))

(defglobal *maximum-problem-store-historical-problem-count* 0)

(defun update-maximum-problem-store-historical-problem-count (problem-store)
  (let ((count (problem-store-historical-problem-count problem-store)))
    (setf *maximum-problem-store-historical-problem-count*
          (max *maximum-problem-store-historical-problem-count* count)))
  *maximum-problem-store-historical-problem-count*)

;; (defun average-problem-store-historical-problem-count () ...) -- active declareFunction, no body

(defglobal *maximum-forward-problem-store-historical-problem-count* 0)

(defvar *expensive-forward-problem-store-threshold* 1000)

(defun update-maximum-forward-problem-store-historical-problem-count (problem-store)
  (let ((count (problem-store-historical-problem-count problem-store)))
    (when *inference-debug?*
      (when (>= count *expensive-forward-problem-store-threshold*)
        (warn "Forward ~S contained ~S problems" problem-store count)))
    (setf *maximum-forward-problem-store-historical-problem-count*
          (max *maximum-forward-problem-store-historical-problem-count* count)))
  *maximum-forward-problem-store-historical-problem-count*)

;; (defun average-forward-problem-store-historical-problem-count () ...) -- active declareFunction, no body

;; problem counters

(defglobal *problem-historical-count* 0)

(defun increment-problem-historical-count ()
  (incf *problem-historical-count*))

;; (defun problem-historical-count () ...) -- active declareFunction, no body

(defglobal *good-problem-historical-count* 0)

;; (defun good-problem-historical-count () ...) -- active declareFunction, no body

(defun increment-good-problem-historical-count ()
  (incf *good-problem-historical-count*))

;; (defun decrement-good-problem-historical-count () ...) -- active declareFunction, no body

(defglobal *no-good-problem-historical-count* 0)

;; (defun no-good-problem-historical-count () ...) -- active declareFunction, no body

(defun increment-no-good-problem-historical-count ()
  (incf *no-good-problem-historical-count*))

(defglobal *forward-problem-historical-count* 0)

;; (defun forward-problem-historical-count () ...) -- active declareFunction, no body

(defun update-forward-problem-historical-count (problem-store)
  (let ((count (problem-store-historical-problem-count problem-store)))
    (incf *forward-problem-historical-count* count))
  *forward-problem-historical-count*)

(defglobal *single-literal-problem-historical-count* 0)

;; (defun single-literal-problem-historical-count () ...) -- active declareFunction, no body
;; (defun multi-literal-problem-historical-count () ...) -- active declareFunction, no body

(defun increment-single-literal-problem-historical-count ()
  (incf *single-literal-problem-historical-count*))

;; link counters

(defglobal *problem-link-historical-count* 0)
(defglobal *structural-link-historical-count* 0)
(defglobal *content-link-historical-count* 0)
(defglobal *removal-link-historical-count* 0)
(defglobal *transformation-link-historical-count* 0)

;; (defun problem-link-historical-count () ...) -- active declareFunction, no body
;; (defun structural-link-historical-count () ...) -- active declareFunction, no body
;; (defun content-link-historical-count () ...) -- active declareFunction, no body
;; (defun removal-link-historical-count () ...) -- active declareFunction, no body
;; (defun transformation-link-historical-count () ...) -- active declareFunction, no body

(defun increment-problem-link-type-historical-counts (link-type)
  (cond
    ((eql link-type :removal)
     (incf *removal-link-historical-count*)
     (incf *content-link-historical-count*))
    ((eql link-type :transformation)
     (incf *transformation-link-historical-count*)
     (incf *content-link-historical-count*))
    ((eql link-type :rewrite)
     (incf *content-link-historical-count*))
    (t
     (incf *structural-link-historical-count*)))
  (incf *problem-link-historical-count*)
  nil)

(defglobal *dependent-link-historical-count* 0)

;; (defun dependent-link-historical-count () ...) -- active declareFunction, no body

(defun increment-dependent-link-historical-count ()
  (incf *dependent-link-historical-count*))

(defglobal *single-literal-problem-dependent-link-historical-count* 0)

;; (defun single-literal-problem-dependent-link-historical-count () ...) -- active declareFunction, no body
;; (defun multi-literal-problem-dependent-link-historical-count () ...) -- active declareFunction, no body

(defun increment-single-literal-problem-dependent-link-historical-count ()
  (incf *single-literal-problem-dependent-link-historical-count*))

;; (defun problem-reuses-historical-count () ...) -- active declareFunction, no body
;; (defun problem-reuse-historical-ratio () ...) -- active declareFunction, no body
;; (defun single-literal-problem-reuses-historical-count () ...) -- active declareFunction, no body
;; (defun single-literal-problem-reuse-historical-ratio () ...) -- active declareFunction, no body
;; (defun multi-literal-problem-reuses-historical-count () ...) -- active declareFunction, no body
;; (defun multi-literal-problem-reuse-historical-ratio () ...) -- active declareFunction, no body

;; tactic counters

(defglobal *tactic-historical-count* 0)

;; (defun tactic-historical-count () ...) -- active declareFunction, no body

(defun increment-tactic-historical-count ()
  (incf *tactic-historical-count*))

(defglobal *executed-tactic-historical-count* 0)

;; (defun executed-tactic-historical-count () ...) -- active declareFunction, no body

(defun increment-executed-tactic-historical-count ()
  (incf *executed-tactic-historical-count*))

(defglobal *discarded-tactic-historical-count* 0)

;; (defun discarded-tactic-historical-count () ...) -- active declareFunction, no body

(defun increment-discarded-tactic-historical-count ()
  (incf *discarded-tactic-historical-count*))

;; unification counters

(defglobal *unification-attempt-historical-count* 0)

;; (defun unification-attempt-historical-count () ...) -- active declareFunction, no body

(defun increment-unification-attempt-historical-count ()
  (incf *unification-attempt-historical-count*))

(defglobal *unification-success-historical-count* 0)

;; (defun unification-success-historical-count () ...) -- active declareFunction, no body

(defun increment-unification-success-historical-count ()
  (incf *unification-success-historical-count*))

;; SBHL counters

(defglobal *sbhl-cache-attempt-historical-count* 0)

;; (defun sbhl-cache-attempt-historical-count () ...) -- active declareFunction, no body

(defun increment-sbhl-cache-attempt-historical-count ()
  (incf *sbhl-cache-attempt-historical-count*))

(defglobal *sbhl-cache-success-historical-count* 0)

;; (defun sbhl-cache-success-historical-count () ...) -- active declareFunction, no body

(defun increment-sbhl-cache-success-historical-count ()
  (incf *sbhl-cache-success-historical-count*))

(defglobal *sbhl-graph-attempt-historical-count* 0)

;; (defun sbhl-graph-attempt-historical-count () ...) -- active declareFunction, no body

(defun increment-sbhl-graph-attempt-historical-count ()
  (incf *sbhl-graph-attempt-historical-count*))

(defglobal *sbhl-graph-success-historical-count* 0)

;; (defun sbhl-graph-success-historical-count () ...) -- active declareFunction, no body

(defun increment-sbhl-graph-success-historical-count ()
  (incf *sbhl-graph-success-historical-count*))

(defglobal *sbhl-link-historical-count* 0)

;; (defun sbhl-link-historical-count () ...) -- active declareFunction, no body
;; (defun increment-sbhl-link-historical-count () ...) -- active declareFunction, no body

;; proof and inference counters

(defglobal *proof-historical-count* 0)

;; (defun proof-historical-count () ...) -- active declareFunction, no body

(defun increment-proof-historical-count ()
  (incf *proof-historical-count*))

(defglobal *inference-historical-count* 0)

;; (defun inference-historical-count () ...) -- active declareFunction, no body

(defun increment-inference-historical-count ()
  (incf *inference-historical-count*))

(defglobal *successful-inference-historical-count* 0)

;; (defun successful-inference-historical-count () ...) -- active declareFunction, no body

(defun increment-successful-inference-historical-count ()
  (incf *successful-inference-historical-count*))

(defglobal *forward-inference-historical-count* 0)

;; (defun forward-inference-historical-count () ...) -- active declareFunction, no body
;; (defun backward-inference-historical-count () ...) -- active declareFunction, no body

(defun increment-forward-inference-historical-count ()
  (incf *forward-inference-historical-count*))

;; (defun successful-forward-inference-historical-count () ...) -- active declareFunction, no body
;; (defun successful-backward-inference-historical-count () ...) -- active declareFunction, no body

(defglobal *successful-forward-inference-historical-count* 0)

(defun increment-successful-forward-inference-historical-count ()
  (incf *successful-forward-inference-historical-count*))

;; (defun average-historical-inference-relevant-problem-count () ...) -- active declareFunction, no body
;; (defun sksi-query-total-time-accumulator-lookup (rule) ...) -- active declareFunction, no body
;; (defun sksi-query-start-times-accumulator-lookup (rule) ...) -- active declareFunction, no body
;; (defun sparql-query-profile-accumulator-lookup (rule) ...) -- active declareFunction, no body

;;; Forward inference metrics

(defvar *gathering-forward-inference-metrics?* nil
  "[Cyc] Whether we are gathering metrics on the expense of forward inference.")

;; gathering-forward-inference-metrics — active declareMacro
;; TODO: Reconstruct macro body from Internal Constants.
;; $list304 = ((&BODY BODY)), $sym305$CLET, $list306 = ((*GATHERING-FORWARD-INFERENCE-METRICS?* T))
(defmacro gathering-forward-inference-metrics (&body body)
  `(let ((*gathering-forward-inference-metrics?* t))
     ,@body))

;; show-forward-inference-metrics-of — active declareMacro
;; TODO: Reconstruct macro body from Internal Constants.
;; $list307 = ((FORM &KEY STREAM), more constants follow
(defmacro show-forward-inference-metrics-of ((form &key stream) &body body)
  (declare (ignore form stream body))
  (error "show-forward-inference-metrics-of: TODO macro body not yet reconstructed"))

;; show-new-forward-inference-metrics-of — active declareMacro
;; TODO: Reconstruct macro body from Internal Constants.
(defmacro show-new-forward-inference-metrics-of ((form &key stream) &body body)
  (declare (ignore form stream body))
  (error "show-new-forward-inference-metrics-of: TODO macro body not yet reconstructed"))

(defglobal *forward-inference-metrics-time-index* (make-hash-table :test #'eq))
(defglobal *forward-inference-metrics-count-index* (make-hash-table :test #'eq))
(defglobal *forward-inference-metrics-inference-index* (make-hash-table :test #'eq))
(defglobal *forward-inference-metrics-gaf-index* (make-hash-table :test #'eq))

;; (defun forward-inference-metrics-time-index () ...) -- active declareFunction, no body
;; (defun forward-inference-metrics-count-index () ...) -- active declareFunction, no body
;; (defun forward-inference-metrics-inference-index () ...) -- active declareFunction, no body
;; (defun finalize-forward-inference-metrics-inference-index () ...) -- active declareFunction, no body
;; (defun forward-inference-metrics-gaf-index () ...) -- active declareFunction, no body
;; (defun clear-forward-inference-metrics () ...) -- active declareFunction, no body

(defun increment-forward-inference-metrics (rule rule-time inference)
  (when *gathering-forward-inference-metrics?*
    (when *browse-forward-inferences?*
      (when inference
        ;; missing-larkc 36297 — likely forward-inference-metrics-inference-index call
        (dictionary-push (missing-larkc 36297) rule inference)))
    (let ((gaf ;; missing-larkc 36387 — likely gets the triggering GAF
            (missing-larkc 36387)))
      (when gaf
        ;; missing-larkc 36293 — likely forward-inference-metrics-gaf-index call
        (dictionary-pushnew (missing-larkc 36293) rule gaf)))
    ;; missing-larkc 36291 — likely forward-inference-metrics-count-index call
    (dictionary-increment (missing-larkc 36291) rule)
    ;; missing-larkc 36300 — likely forward-inference-metrics-time-index call
    (dictionary-increment (missing-larkc 36300) rule rule-time)))

;; (defun forward-inference-metrics-info (&optional stream) ...) -- active declareFunction, no body
;; (defun forward-inference-successful-rules () ...) -- active declareFunction, no body
;; (defun forward-inference-unsuccessful-rules () ...) -- active declareFunction, no body
;; (defun rule-forward-inference-metrics-info (rule) ...) -- active declareFunction, no body
;; (defun rule-forward-inference-metrics-info-int (rule stream) ...) -- active declareFunction, no body
;; (defun global-statistics-from-forward-inference-metrics-info (info) ...) -- active declareFunction, no body
;; (defun show-forward-inference-metrics (&optional stream detail-level) ...) -- active declareFunction, no body
;; (defun show-forward-inference-metrics-of-asserting (sentence mt &optional stream detail-level) ...) -- active declareFunction, no body

;; reset and show

;; (defun reset-inference-metrics () ...) -- active declareFunction, no body
;; (defun show-inference-metrics (&optional stream) ...) -- active declareFunction, no body
;; (defun show-inference-metric-percentage (numerator denominator label &optional stream) ...) -- active declareFunction, no body

;;; Variables

(defglobal *inference-metrics-store* (make-hash-table :test #'eq)
  "[Cyc] The repository of inference metrics and information about them.")

(deflexical *inference-metric-properties*
    '(:name :evaluation-func :evaluation-arg1 :cross-product?)
  "[Cyc] The list of allowable properties for an inference metric.")

;;; Setup

(toplevel
  (declare-defglobal '*inference-metrics-store*)
  (declare-inference-metric :answer-count 'inference-answer-count :inference)
  (declare-inference-metric :answer-count-at-30-seconds 'inference-answer-count-at-30-seconds :inference)
  (declare-inference-metric :answer-count-at-60-seconds 'inference-answer-count-at-60-seconds :inference)
  (declare-inference-metric :time-to-first-answer 'inference-first-answer-elapsed-time :inference)
  (declare-inference-metric :time-to-last-answer 'inference-last-answer-elapsed-time :inference)
  (declare-inference-metric :total-time 'inference-cumulative-time :inference)
  (declare-inference-metric :time-per-answer 'inference-time-per-answer :inference)
  (declare-inference-metric :steps-to-first-answer 'inference-first-answer-step-count :inference)
  (declare-inference-metric :steps-to-last-answer 'inference-last-answer-step-count :inference)
  (declare-inference-metric :total-steps 'inference-cumulative-step-count :inference)
  (declare-inference-metric :steps-per-answer 'inference-steps-per-answer :inference)
  (declare-inference-metric :wasted-time-after-last-answer 'inference-wasted-time-after-last-answer :inference)
  (declare-inference-metric :latency-improvement-from-iterativity 'inference-latency-improvement-from-iterativity :inference)
  (declare-inference-metric :problem-count 'problem-store-problem-count :store)
  (declare-inference-metric :problem-store-problem-count 'problem-store-problem-count :store)
  (declare-inference-metric :proof-count 'problem-store-proof-count :store)
  (declare-inference-metric :problem-store-proof-count 'problem-store-proof-count :store)
  (declare-inference-metric :link-count 'problem-store-link-count :store)
  (declare-inference-metric :tactic-count 'problem-store-tactic-count :store)
  (declare-inference-metric :possible-tactic-count 'problem-store-possible-tactic-count :store)
  (declare-inference-metric :executed-tactic-count 'problem-store-executed-tactic-count :store)
  (declare-inference-metric :tactic-execution-count 'problem-store-tactic-execution-count :store)
  (declare-inference-metric :discarded-tactic-count 'problem-store-discarded-tactic-count :store)
  (declare-inference-metric :content-link-count 'problem-store-content-link-count :store)
  (declare-inference-metric :removal-link-count 'problem-store-removal-link-count :store)
  (declare-inference-metric :rewrite-link-count 'problem-store-rewrite-link-count :store))
