#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

;;; rewrite-link-data defstruct -- 3 slots, conc-name "rw-link-data-"

(defstruct (rewrite-link-data
            (:conc-name "rw-link-data-"))
  hl-module
  bindings
  supports)

;; rewrite-link-data-p is auto-generated by defstruct
;; rw-link-data-hl-module, rw-link-data-bindings, rw-link-data-supports generated by defstruct
;; _csetf-* handled by (setf rw-link-data-*) from defstruct
;; make-rewrite-link-data generated by defstruct

(defconstant *dtp-rewrite-link-data* 'rewrite-link-data)

;; (defun new-rewrite-link (supported-problem mapped-problem hl-module supports) ...) -- active declareFunction, no body
;; (defun new-rewrite-link-int (supported-problem mapped-problem hl-module) ...) -- active declareFunction, no body
;; (defun new-rewrite-link-data (hl-module) ...) -- active declareFunction, no body
;; (defun destroy-rewrite-link (link) ...) -- active declareFunction, no body
;; (defun rewrite-link-hl-module (link) ...) -- active declareFunction, no body
;; (defun rewrite-link-bindings (link) ...) -- active declareFunction, no body
;; (defun rewrite-link-supports (link) ...) -- active declareFunction, no body
;; (defun set-rewrite-link-hl-module (link hl-module) ...) -- active declareFunction, no body
;; (defun set-rewrite-link-bindings (link bindings) ...) -- active declareFunction, no body
;; (defun set-rewrite-link-supports (link supports) ...) -- active declareFunction, no body
;; (defun rewrite-link-tactic (link) ...) -- active declareFunction, no body
;; (defun rewrite-link-supporting-mapped-problem (link) ...) -- active declareFunction, no body
;; (defun rewrite-link-supporting-variable-map (link) ...) -- active declareFunction, no body
;; (defun rewrite-link-rewrite-mt (link) ...) -- active declareFunction, no body

(defun rewrite-link-p (object)
  (and (problem-link-p object)
       (eq :rewrite (problem-link-type object))))

(defun rewrite-tactic-p (tactic)
  (and (tactic-p tactic)
       (eq :rewrite (tactic-type tactic))))

;; (defun rewrite-tactic-support (tactic) ...) -- active declareFunction, no body
;; (defun rewrite-proof-p (proof) ...) -- active declareFunction, no body
;; (defun determine-new-literal-rewrite-tactics (problem asent sense &optional already-tried-tactics) ...) -- active declareFunction, no body

(defun literal-level-rewrite-tactic-p (tactic)
  (and (rewrite-tactic-p tactic)
       (literal-level-tactic-p tactic)))

;; (defun maybe-new-rewrite-link (problem asent hl-module supports) ...) -- active declareFunction, no body
;; (defun new-rewrite-tactic (problem hl-module asent supports) ...) -- active declareFunction, no body
;; (defun compute-strategic-properties-of-rewrite-tactic (tactic strategy) ...) -- active declareFunction, no body
;; (defun current-rewrite-mt () ...) -- active declareFunction, no body
;; (defun execute-literal-level-rewrite-tactic (tactic problem strategic-context) ...) -- active declareFunction, no body
;; (defun rewrite-add-link (tactic proof) ...) -- active declareFunction, no body
;; (defun compute-rewrite-bindings (link) ...) -- active declareFunction, no body
;; (defun identity-variable-map-for-sentence (sentence) ...) -- active declareFunction, no body
;; (defun restriction-rewrite-add-link (link proof) ...) -- active declareFunction, no body

(defun trigger-restriction-link-listeners (link proof)
  (declare (ignore proof))
  (when (restriction-listening-link-p link)
    (let* ((unrestricted-problem (problem-link-supported-problem link))
           (restricted-mapped-problem
            ;; Likely returns the restriction link's sole supporting mapped problem
            (missing-larkc 35684))
           (restricted-problem (mapped-problem-problem restricted-mapped-problem))
           (restricted-asent (single-literal-problem-atomic-sentence restricted-problem)))
      (declare (ignorable unrestricted-problem))
      (dolist (tactic
               ;; Likely returns the rewrite tactics applicable to unrestricted-problem
               (missing-larkc 35682))
        (let* ((hl-module (tactic-hl-module tactic))
               (rewrite-closure-fn
                ;; Likely retrieves the rewrite closure function from the hl-module
                (missing-larkc 36424))
               (rewritten-closure (funcall rewrite-closure-fn restricted-asent)))
          (dolist (asent-and-supports rewritten-closure)
            (destructuring-bind (asent supports) asent-and-supports
              ;; Likely calls maybe-add-restriction-rewrite-problem or similar
              ;; to create a rewrite problem from the rewritten asent and supports
              (missing-larkc 32960)))))))
  nil)

;; (defun maybe-add-restriction-rewrite-problem (problem asent hl-module supports link proof) ...) -- active declareFunction, no body
;; (defun structurally-redundant-restriction-rewrite-problem? (problem asent) ...) -- active declareFunction, no body
;; (defun new-rewrite-proof (link proof bindings) ...) -- active declareFunction, no body
;; (defun bubble-up-proof-to-rewrite-link (link proof variable-map) ...) -- active declareFunction, no body
