#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#

(in-package :clyc)

;; (defun balanced-strategy-motivation-p (object) ...) -- active declareFunction, no body

(defstruct (balanced-strategy-data
            (:conc-name "BAL-STRAT-DATA-")
            (:constructor make-balanced-strategy-data-int ()))
  problems-motivated-wrt-new-root-table
  problems-motivated-wrt-removal
  problems-motivated-wrt-transformation
  link-heads-motivated-wrt-removal
  link-heads-motivated-wrt-transformation
  problems-pending-wrt-new-root
  problems-pending-wrt-removal
  problems-pending-wrt-transformation
  new-root-index
  new-root-problems
  removal-strategem-index
  problem-total-strategems-active-wrt-removal
  current-new-root-wrt-removal
  transformation-strategem-index
  problem-total-strategems-active-wrt-transformation
  problem-strategems-set-aside-wrt-removal
  problem-strategems-set-aside-wrt-transformation
  problem-strategems-thrown-away-wrt-removal
  problem-strategems-thrown-away-wrt-transformation)

(defconstant *dtp-balanced-strategy-data* 'balanced-strategy-data)

;; (defun balanced-strategy-data-print-function-trampoline (object stream) ...) -- active declareFunction, no body
;; balanced-strategy-data-p is auto-generated by defstruct

(defun make-balanced-strategy-data (&optional arglist)
  (let ((v-new (make-balanced-strategy-data-int)))
    (loop for next = arglist then (cddr next)
          while next
          for current-arg = (first next)
          for current-value = (second next)
          do (case current-arg
               (:problems-motivated-wrt-new-root-table
                (setf (bal-strat-data-problems-motivated-wrt-new-root-table v-new) current-value))
               (:problems-motivated-wrt-removal
                (setf (bal-strat-data-problems-motivated-wrt-removal v-new) current-value))
               (:problems-motivated-wrt-transformation
                (setf (bal-strat-data-problems-motivated-wrt-transformation v-new) current-value))
               (:link-heads-motivated-wrt-removal
                (setf (bal-strat-data-link-heads-motivated-wrt-removal v-new) current-value))
               (:link-heads-motivated-wrt-transformation
                (setf (bal-strat-data-link-heads-motivated-wrt-transformation v-new) current-value))
               (:problems-pending-wrt-new-root
                (setf (bal-strat-data-problems-pending-wrt-new-root v-new) current-value))
               (:problems-pending-wrt-removal
                (setf (bal-strat-data-problems-pending-wrt-removal v-new) current-value))
               (:problems-pending-wrt-transformation
                (setf (bal-strat-data-problems-pending-wrt-transformation v-new) current-value))
               (:new-root-index
                (setf (bal-strat-data-new-root-index v-new) current-value))
               (:new-root-problems
                (setf (bal-strat-data-new-root-problems v-new) current-value))
               (:removal-strategem-index
                (setf (bal-strat-data-removal-strategem-index v-new) current-value))
               (:problem-total-strategems-active-wrt-removal
                (setf (bal-strat-data-problem-total-strategems-active-wrt-removal v-new) current-value))
               (:current-new-root-wrt-removal
                (setf (bal-strat-data-current-new-root-wrt-removal v-new) current-value))
               (:transformation-strategem-index
                (setf (bal-strat-data-transformation-strategem-index v-new) current-value))
               (:problem-total-strategems-active-wrt-transformation
                (setf (bal-strat-data-problem-total-strategems-active-wrt-transformation v-new) current-value))
               (:problem-strategems-set-aside-wrt-removal
                (setf (bal-strat-data-problem-strategems-set-aside-wrt-removal v-new) current-value))
               (:problem-strategems-set-aside-wrt-transformation
                (setf (bal-strat-data-problem-strategems-set-aside-wrt-transformation v-new) current-value))
               (:problem-strategems-thrown-away-wrt-removal
                (setf (bal-strat-data-problem-strategems-thrown-away-wrt-removal v-new) current-value))
               (:problem-strategems-thrown-away-wrt-transformation
                (setf (bal-strat-data-problem-strategems-thrown-away-wrt-transformation v-new) current-value))
               (otherwise
                (error "Invalid slot ~S for construction function" current-arg))))
    v-new))

(defun balanced-strategy-p (object)
  (or (heuristic-balanced-strategy-p object)
      (abductive-strategy-p object)))

(defun new-balanced-strategy-data (removal-index new-root-index transformation-index)
  (let ((data (make-balanced-strategy-data)))
    (setf (bal-strat-data-problems-motivated-wrt-new-root-table data) (new-dictionary #'eq))
    (setf (bal-strat-data-problems-motivated-wrt-removal data) (new-set #'eq))
    (setf (bal-strat-data-problems-motivated-wrt-transformation data) (new-set #'eq))
    (setf (bal-strat-data-link-heads-motivated-wrt-removal data) (new-set #'eq))
    (setf (bal-strat-data-link-heads-motivated-wrt-transformation data) (new-set #'eq))
    (setf (bal-strat-data-problems-pending-wrt-new-root data) (new-set #'eq))
    (setf (bal-strat-data-problems-pending-wrt-removal data) (new-set #'eq))
    (setf (bal-strat-data-problems-pending-wrt-transformation data) (new-set #'eq))
    (setf (bal-strat-data-new-root-index data) new-root-index)
    (setf (bal-strat-data-new-root-problems data) (new-set #'eq))
    (setf (bal-strat-data-removal-strategem-index data) removal-index)
    (setf (bal-strat-data-problem-total-strategems-active-wrt-removal data) (new-dictionary #'eq))
    (setf (bal-strat-data-current-new-root-wrt-removal data) nil)
    (setf (bal-strat-data-transformation-strategem-index data) transformation-index)
    (setf (bal-strat-data-problem-total-strategems-active-wrt-transformation data) (new-dictionary #'eq))
    (setf (bal-strat-data-problem-strategems-set-aside-wrt-removal data) (new-dictionary #'eq))
    (setf (bal-strat-data-problem-strategems-set-aside-wrt-transformation data) (new-dictionary #'eq))
    (setf (bal-strat-data-problem-strategems-thrown-away-wrt-removal data) (new-dictionary #'eq))
    (setf (bal-strat-data-problem-strategems-thrown-away-wrt-transformation data) (new-dictionary #'eq))
    data))

(defun balanced-strategy-problems-motivated-wrt-new-root-table (strategy)
  "[Cyc] @return set-p of problem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problems-motivated-wrt-new-root-table data)))

(defun balanced-strategy-problems-motivated-wrt-removal (strategy)
  "[Cyc] @return set-p of problem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problems-motivated-wrt-removal data)))

(defun balanced-strategy-problems-motivated-wrt-transformation (strategy)
  "[Cyc] @return set-p of problem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problems-motivated-wrt-transformation data)))

(defun balanced-strategy-link-heads-motivated-wrt-removal (strategy)
  "[Cyc] @return set-p of motivation-strategem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-link-heads-motivated-wrt-removal data)))

(defun balanced-strategy-link-heads-motivated-wrt-transformation (strategy)
  "[Cyc] @return set-p of motivation-strategem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-link-heads-motivated-wrt-transformation data)))

(defun balanced-strategy-problems-pending-wrt-new-root (strategy)
  "[Cyc] @return set-p of problem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problems-pending-wrt-new-root data)))

(defun balanced-strategy-problems-pending-wrt-removal (strategy)
  "[Cyc] @return set-p of problem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problems-pending-wrt-removal data)))

(defun balanced-strategy-problems-pending-wrt-transformation (strategy)
  "[Cyc] @return set-p of problem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problems-pending-wrt-transformation data)))

(defun balanced-strategy-new-root-index (strategy)
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-new-root-index data)))

(defun balanced-strategy-new-root-problems (strategy)
  "[Cyc] @return #'EQ set of problem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-new-root-problems data)))

(defun balanced-strategy-removal-strategem-index (strategy)
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-removal-strategem-index data)))

(defun balanced-strategy-problem-total-strategems-active-wrt-removal (strategy)
  "[Cyc] @return #'EQ dictionary of problem-p -> non-negative-integer-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problem-total-strategems-active-wrt-removal data)))

;; (defun balanced-strategy-current-new-root-wrt-removal (strategy) ...) -- active declareFunction, no body

(defun balanced-strategy-transformation-strategem-index (strategy)
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-transformation-strategem-index data)))

(defun balanced-strategy-problem-total-strategems-active-wrt-transformation (strategy)
  "[Cyc] @return #'EQ dictionary of problem-p -> non-negative-integer-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problem-total-strategems-active-wrt-transformation data)))

(defun balanced-strategy-problem-strategems-set-aside-wrt-removal (strategy)
  "[Cyc] @return #'EQ dictionary of problem-p -> #'EQ set of strategem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problem-strategems-set-aside-wrt-removal data)))

(defun balanced-strategy-problem-strategems-set-aside-wrt-transformation (strategy)
  "[Cyc] @return #'EQ dictionary of problem-p -> #'EQ set of strategem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problem-strategems-set-aside-wrt-transformation data)))

(defun balanced-strategy-problem-strategems-thrown-away-wrt-removal (strategy)
  "[Cyc] @return #'EQ dictionary of problem-p -> #'EQ set of strategem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problem-strategems-thrown-away-wrt-removal data)))

(defun balanced-strategy-problem-strategems-thrown-away-wrt-transformation (strategy)
  "[Cyc] @return #'EQ dictionary of problem-p -> #'EQ set of strategem-p"
  (declare (type balanced-strategy-p strategy))
  (let ((data (strategy-data strategy)))
    (bal-strat-data-problem-strategems-thrown-away-wrt-transformation data)))

;; (defun balanced-strategy-problems-motivated-wrt-new-root-count (strategy) ...) -- active declareFunction, no body

(defun balanced-strategy-problem-motivated-wrt-new-root? (strategy problem)
  "[Cyc] Return T iff PROBLEM is motivated to be a new root by STRATEGY"
  (declare (type problem-p problem))
  (sublisp-boolean (dictionary-lookup-without-values
                    (balanced-strategy-problems-motivated-wrt-new-root-table strategy)
                    problem)))

;; (defun balanced-strategy-historical-new-root-count (strategy) ...) -- active declareFunction, no body
;; (defun balanced-strategy-historical-new-root-time (strategy problem) ...) -- active declareFunction, no body
;; (defun balanced-strategy-historical-new-root-times (strategy) ...) -- active declareFunction, no body
;; (defun balanced-strategy-current-new-root-wrt-removal-elapsed-time (strategy) ...) -- active declareFunction, no body
;; (defun balanced-strategy-new-root-count (strategy) ...) -- active declareFunction, no body
;; (defun balanced-strategy-problems-motivated-wrt-removal-count (strategy) ...) -- active declareFunction, no body

(defun balanced-strategy-problem-motivated-wrt-removal? (strategy problem)
  "[Cyc] Return T iff removal is motivated on PROBLEM in STRATEGY"
  (declare (type problem-p problem))
  (set-member? problem (balanced-strategy-problems-motivated-wrt-removal strategy)))

;; (defun balanced-strategy-problems-motivated-wrt-transformation-count (strategy) ...) -- active declareFunction, no body

(defun balanced-strategy-problem-motivated-wrt-transformation? (strategy problem)
  "[Cyc] Return T iff transformation is motivated on PROBLEM in STRATEGY"
  (declare (type problem-p problem))
  (set-member? problem (balanced-strategy-problems-motivated-wrt-transformation strategy)))

(defun balanced-strategy-link-head-motivated-wrt-removal? (strategy link-head)
  "[Cyc] Return T iff removal motivation should propagate through LINK-HEAD in STRATEGY"
  (declare (type motivation-strategem-p link-head))
  (set-member? link-head (balanced-strategy-link-heads-motivated-wrt-removal strategy)))

(defun balanced-strategy-link-head-motivated-wrt-transformation? (strategy link-head)
  "[Cyc] Return T iff transformation motivation should propagate through LINK-HEAD in STRATEGY"
  (declare (type motivation-strategem-p link-head))
  (set-member? link-head (balanced-strategy-link-heads-motivated-wrt-transformation strategy)))

(defun balanced-strategy-link-head-motivated? (strategy motivation link-head)
  (case motivation
    (:removal (balanced-strategy-link-head-motivated-wrt-removal? strategy link-head))
    (:transformation (balanced-strategy-link-head-motivated-wrt-transformation? strategy link-head))
    (otherwise (error "unexpected motivation ~s" motivation))))

(defun balanced-strategy-connected-conjunction-link-motivated-wrt-removal? (strategy connected-conjunction-link)
  (declare (type balanced-strategy-p strategy))
  (declare (type connected-conjunction-link-p connected-conjunction-link))
  (let ((link-head (connected-conjunction-link-tactic connected-conjunction-link)))
    (balanced-strategy-link-head-motivated-wrt-removal? strategy link-head)))

(defun balanced-strategy-problem-pending? (strategy problem motivation)
  "[Cyc] Return T iff PROBLEM is pending in STRATEGY wrt MOTIVATION"
  (declare (type problem-p problem))
  (case motivation
    (:new-root (set-member? problem (balanced-strategy-problems-pending-wrt-new-root strategy)))
    (:removal (set-member? problem (balanced-strategy-problems-pending-wrt-removal strategy)))
    (:transformation (set-member? problem (balanced-strategy-problems-pending-wrt-transformation strategy)))
    (otherwise (error "unexpected motivation ~s" motivation))))

(defun balanced-strategy-problem-totally-pending? (strategy problem)
  (and (balanced-strategy-problem-pending? strategy problem :removal)
       (balanced-strategy-problem-pending? strategy problem :transformation)
       t))

(defun balanced-strategy-problem-active? (strategy problem motivation)
  "[Cyc] @return booleanp; whether PROBLEM is actively being considered for MOTIVATION by STRATEGY."
  (case motivation
    (:new-root (balanced-strategy-problem-active-wrt-new-root? strategy problem))
    (:removal (balanced-strategy-problem-active-wrt-removal? strategy problem))
    (:transformation (balanced-strategy-problem-active-wrt-transformation? strategy problem))
    (otherwise (error "unexpected motivation ~s" motivation))))

(defun balanced-strategy-problem-active-wrt-new-root? (strategy problem)
  "[Cyc] @return booleanp; whether PROBLEM is actively being considered a new root by STRATEGY."
  (declare (type problem-p problem))
  (set-member? problem (balanced-strategy-new-root-problems strategy)))

(defun balanced-strategy-problem-active-wrt-removal? (strategy problem)
  "[Cyc] @return booleanp; whether PROBLEM is actively being considered for removal by STRATEGY."
  (declare (type problem-p problem))
  (let ((index (balanced-strategy-problem-total-strategems-active-wrt-removal strategy)))
    (plusp (dictionary-lookup-without-values index problem 0))))

(defun balanced-strategy-problem-active-wrt-transformation? (strategy problem)
  "[Cyc] @return booleanp; whether PROBLEM is actively being considered for transformation by STRATEGY."
  (declare (type problem-p problem))
  (let ((index (balanced-strategy-problem-total-strategems-active-wrt-transformation strategy)))
    (plusp (dictionary-lookup-without-values index problem 0))))

(defun balanced-strategy-problem-set-aside? (strategy problem motivation)
  (declare (type balanced-strategy-motivation-p motivation))
  (case motivation
    (:new-root nil)
    (:removal (balanced-strategy-problem-set-aside-wrt-removal? strategy problem))
    (:transformation (balanced-strategy-problem-set-aside-wrt-transformation? strategy problem))))

(defun balanced-strategy-problem-set-aside-wrt-removal? (strategy problem)
  "[Cyc] @return booleanp; whether PROBLEM has been set aside for later removal consideration by STRATEGY."
  (declare (type problem-p problem))
  (when (not (balanced-strategy-problem-active-wrt-removal? strategy problem))
    (let* ((index (balanced-strategy-problem-strategems-set-aside-wrt-removal strategy))
           (v-set (dictionary-lookup-without-values index problem nil)))
      (when (and v-set
                 (not (set-empty? v-set)))
        (return-from balanced-strategy-problem-set-aside-wrt-removal? t))))
  nil)

(defun balanced-strategy-problem-set-aside-wrt-transformation? (strategy problem)
  "[Cyc] @return booleanp; whether PROBLEM has been set aside for later transformation consideration by STRATEGY."
  (declare (type problem-p problem))
  (when (not (balanced-strategy-problem-active-wrt-transformation? strategy problem))
    (let* ((index (balanced-strategy-problem-strategems-set-aside-wrt-transformation strategy))
           (v-set (dictionary-lookup-without-values index problem nil)))
      (when (and v-set
                 (not (set-empty? v-set)))
        (return-from balanced-strategy-problem-set-aside-wrt-transformation? t))))
  nil)

(defun balanced-strategy-strategem-set-aside? (strategy strategem motivation)
  (declare (type balanced-strategy-motivation-p motivation))
  (case motivation
    (:removal (balanced-strategy-strategem-set-aside-wrt-removal? strategy strategem))
    (:transformation (balanced-strategy-strategem-set-aside-wrt-transformation? strategy strategem))))

(defun balanced-strategy-strategem-set-aside-wrt-removal? (strategy strategem)
  "[Cyc] @return booleanp; whether STRATEGEM has been set aside for later removal consideration by STRATEGY."
  (declare (type strategem-p strategem))
  (let* ((problem (strategem-problem strategem))
         (index (balanced-strategy-problem-strategems-set-aside-wrt-removal strategy))
         (v-set (dictionary-lookup-without-values index problem nil)))
    (and (set-p v-set)
         (set-member? strategem v-set)
         t)))

(defun balanced-strategy-strategem-set-aside-wrt-transformation? (strategy strategem)
  "[Cyc] @return booleanp; whether STRATEGEM has been set aside for later transformation consideration by STRATEGY."
  (declare (type strategem-p strategem))
  (let* ((problem (strategem-problem strategem))
         (index (balanced-strategy-problem-strategems-set-aside-wrt-transformation strategy))
         (v-set (dictionary-lookup-without-values index problem nil)))
    (and (set-p v-set)
         (set-member? strategem v-set)
         t)))

(defun balanced-strategy-strategem-thrown-away? (strategy strategem motivation)
  (declare (type balanced-strategy-motivation-p motivation))
  (case motivation
    (:removal (balanced-strategy-strategem-thrown-away-wrt-removal? strategy strategem))
    (:transformation (balanced-strategy-strategem-thrown-away-wrt-transformation? strategy strategem))))

(defun balanced-strategy-strategem-thrown-away-wrt-removal? (strategy strategem)
  "[Cyc] @return booleanp; whether STRATEGEM has been thrown away by STRATEGY."
  (declare (type strategem-p strategem))
  (let* ((problem (strategem-problem strategem))
         (index (balanced-strategy-problem-strategems-thrown-away-wrt-removal strategy))
         (v-set (dictionary-lookup-without-values index problem nil)))
    (and (set-p v-set)
         (set-member? strategem v-set)
         t)))

(defun balanced-strategy-strategem-thrown-away-wrt-transformation? (strategy strategem)
  "[Cyc] @return booleanp; whether STRATEGEM has been thrown away by STRATEGY."
  (declare (type strategem-p strategem))
  (let* ((problem (strategem-problem strategem))
         (index (balanced-strategy-problem-strategems-thrown-away-wrt-transformation strategy))
         (v-set (dictionary-lookup-without-values index problem nil)))
    (and (set-p v-set)
         (set-member? strategem v-set)
         t)))

(defvar *balanced-strategy-early-removal-productivity-limit*
  (productivity-for-number-of-children (symbol-value '*transformation-early-removal-threshold*)))

;; (defun balanced-strategy-early-removal-productivity-limit (strategy) ...) -- active declareFunction, no body

(defun balanced-strategy-removal-backtracking-productivity-limit (strategy)
  "[Cyc] @return nil or productivity-p"
  (strategy-removal-backtracking-productivity-limit strategy))

(defun balanced-strategy-peek-strategem-wrt-removal (strategy)
  (strategy-dispatch strategy :peek-removal-strategem))

(defun balanced-strategy-peek-new-root (strategy)
  (strategy-dispatch strategy :peek-new-root))

(defun balanced-strategy-peek-strategem-wrt-transformation (strategy)
  (strategy-dispatch strategy :peek-transformation-strategem))

(defun balanced-strategy-note-problem-motivated-wrt-new-root (strategy problem)
  "[Cyc] note N"
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (dictionary-enter (balanced-strategy-problems-motivated-wrt-new-root-table strategy) problem :unactivated))

(defun balanced-strategy-note-new-root-activated-wrt-removal (strategy problem)
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (let ((elapsed (inference-elapsed-internal-real-time-since-start (strategy-inference strategy))))
    (dictionary-enter (balanced-strategy-problems-motivated-wrt-new-root-table strategy) problem elapsed)
    (balanced-strategy-set-current-new-root-wrt-removal strategy problem)
    problem))

(defun balanced-strategy-note-problem-motivated-wrt-removal (strategy problem)
  "[Cyc] note R"
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (set-add problem (balanced-strategy-problems-motivated-wrt-removal strategy)))

(defun balanced-strategy-note-problem-motivated-wrt-transformation (strategy problem)
  "[Cyc] note T"
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (set-add problem (balanced-strategy-problems-motivated-wrt-transformation strategy)))

(defun balanced-strategy-note-link-head-motivated-wrt-removal (strategy link-head)
  "[Cyc] note R"
  (declare (type balanced-strategy-p strategy))
  (declare (type motivation-strategem-p link-head))
  (set-add link-head (balanced-strategy-link-heads-motivated-wrt-removal strategy)))

(defun balanced-strategy-note-link-head-motivated-wrt-transformation (strategy link-head)
  "[Cyc] note T"
  (declare (type balanced-strategy-p strategy))
  (declare (type motivation-strategem-p link-head))
  (set-add link-head (balanced-strategy-link-heads-motivated-wrt-transformation strategy)))

(defun balanced-strategy-note-link-head-motivated (strategy motivation link-head)
  (case motivation
    (:removal (balanced-strategy-note-link-head-motivated-wrt-removal strategy link-head))
    (:transformation (balanced-strategy-note-link-head-motivated-wrt-transformation strategy link-head))
    (otherwise (error "unexpected motivation ~s" motivation))))

(defun balanced-strategy-note-problem-pending-wrt-new-root (strategy problem)
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (set-add problem (balanced-strategy-problems-pending-wrt-new-root strategy)))

(defun balanced-strategy-note-problem-pending-wrt-removal (strategy problem)
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (set-add problem (balanced-strategy-problems-pending-wrt-removal strategy)))

(defun balanced-strategy-note-problem-pending-wrt-transformation (strategy problem)
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (set-add problem (balanced-strategy-problems-pending-wrt-transformation strategy)))

(defun balanced-strategy-note-problem-pending (strategy problem motivation)
  (declare (type balanced-strategy-motivation-p motivation))
  (case motivation
    (:new-root (balanced-strategy-note-problem-pending-wrt-new-root strategy problem))
    (:removal (balanced-strategy-note-problem-pending-wrt-removal strategy problem))
    (:transformation (balanced-strategy-note-problem-pending-wrt-transformation strategy problem))))

(defun balanced-strategy-note-problem-unpending-wrt-removal (strategy problem)
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (set-remove problem (balanced-strategy-problems-pending-wrt-removal strategy)))

(defun balanced-strategy-note-problem-unpending-wrt-transformation (strategy problem)
  (declare (type balanced-strategy-p strategy))
  (declare (type problem-p problem))
  (set-remove problem (balanced-strategy-problems-pending-wrt-transformation strategy)))

(defun balanced-strategy-note-problem-unpending (strategy problem motivation)
  (declare (type balanced-strategy-motivation-p motivation))
  (case motivation
    (:removal (balanced-strategy-note-problem-unpending-wrt-removal strategy problem))
    (:transformation (balanced-strategy-note-problem-unpending-wrt-transformation strategy problem))
    (otherwise (error "new root unpending not yet supported"))))

(defun balanced-strategy-add-new-root (strategy problem)
  (let ((added? nil))
    (setf added? (strategy-dispatch strategy :activate-new-root problem))
    (when added?
      (set-add problem (balanced-strategy-new-root-problems strategy)))
    added?))

(defun balanced-strategy-pop-new-root (strategy)
  (let ((problem nil))
    (setf problem (strategy-dispatch strategy :pop-new-root))
    (when (problem-p problem)
      (set-remove problem (balanced-strategy-new-root-problems strategy)))
    problem))

;; (defun balanced-strategy-clear-current-new-root-wrt-removal (strategy) ...) -- active declareFunction, no body

(defun balanced-strategy-set-current-new-root-wrt-removal (strategy &optional new-root)
  ;; Java conditionally checkType'd new-root when non-nil
  (let ((data (strategy-data strategy)))
    (setf (bal-strat-data-current-new-root-wrt-removal data) new-root))
  strategy)

(defun balanced-strategy-activate-strategem-wrt-removal (strategy removal-strategem)
  "[Cyc] note that REMOVAL-STRATEGEM is in STRATEGY's R-box"
  (declare (type balanced-strategy-p strategy))
  (declare (type removal-strategem-p removal-strategem))
  (let ((result nil))
    (setf result (strategy-dispatch strategy :activate-removal-strategem removal-strategem))
    (when result
      (let* ((problem (strategem-problem removal-strategem))
             (index (balanced-strategy-problem-total-strategems-active-wrt-removal strategy))
             (count (dictionary-lookup-without-values index problem 0)))
        (setf count (+ count 1))
        (when (= 1 count)
          (balanced-strategy-note-problem-unpending-wrt-removal strategy problem))
        (dictionary-enter index problem count)
        (return-from balanced-strategy-activate-strategem-wrt-removal count))))
  nil)

(defun balanced-strategy-pop-strategem-wrt-removal (strategy)
  (strategy-dispatch strategy :pop-removal-strategem))

(defun balanced-strategy-activate-strategem-wrt-transformation (strategy transformation-strategem)
  "[Cyc] note that TRANSFORMATION-STRATEGEM is in STRATEGY's T-box"
  (declare (type balanced-strategy-p strategy))
  (declare (type transformation-strategem-p transformation-strategem))
  (when (and (transformation-tactic-p transformation-strategem)
             (tactic-executed? transformation-strategem))
    ;; Likely logs or warns about re-activating an already-executed tactic
    (missing-larkc 35695))
  (let ((result nil))
    (setf result (strategy-dispatch strategy :activate-transformation-strategem transformation-strategem))
    (when result
      (let* ((problem (strategem-problem transformation-strategem))
             (index (balanced-strategy-problem-total-strategems-active-wrt-transformation strategy))
             (count (dictionary-lookup-without-values index problem 0)))
        (setf count (+ count 1))
        (when (= 1 count)
          (balanced-strategy-note-problem-unpending-wrt-transformation strategy problem))
        (dictionary-enter index problem count)
        (return-from balanced-strategy-activate-strategem-wrt-transformation count))))
  nil)

(defun balanced-strategy-activate-strategem (strategy strategem motivation)
  (case motivation
    (:removal (balanced-strategy-activate-strategem-wrt-removal strategy strategem))
    (:transformation (balanced-strategy-activate-strategem-wrt-transformation strategy strategem))
    (otherwise (error "new root strategem activation not yet supported"))))

(defun balanced-strategy-pop-strategem-wrt-transformation (strategy)
  (strategy-dispatch strategy :pop-transformation-strategem))

;; (defun balanced-strategy-note-strategem-set-aside-wrt-removal (strategy removal-strategem) ...) -- active declareFunction, no body

(defun balanced-strategy-clear-strategems-set-aside-wrt-removal (strategy)
  (declare (type balanced-strategy-p strategy))
  (let ((index (balanced-strategy-problem-strategems-set-aside-wrt-removal strategy)))
    (maphash (lambda (problem strategem-set)
               (declare (ignore strategem-set))
               (balanced-strategy-note-problem-unpending-wrt-removal strategy problem))
             index)
    (clrhash index))
  strategy)

;; (defun balanced-strategy-note-strategem-set-aside-wrt-transformation (strategy transformation-strategem) ...) -- active declareFunction, no body

(defun balanced-strategy-clear-strategems-set-aside-wrt-transformation (strategy)
  (declare (type balanced-strategy-p strategy))
  (let ((index (balanced-strategy-problem-strategems-set-aside-wrt-transformation strategy)))
    (maphash (lambda (problem strategem-set)
               (declare (ignore strategem-set))
               (balanced-strategy-note-problem-unpending-wrt-transformation strategy problem))
             index)
    (clrhash index))
  strategy)

;; (defun balanced-strategy-note-strategem-set-aside (strategy strategem motivation) ...) -- active declareFunction, no body

(defun balanced-strategy-note-strategem-thrown-away-wrt-removal (strategy removal-strategem)
  (declare (type balanced-strategy-p strategy))
  (declare (type removal-strategem-p removal-strategem))
  (let* ((index (balanced-strategy-problem-strategems-thrown-away-wrt-removal strategy))
         (problem (strategem-problem removal-strategem))
         (v-set (dictionary-lookup-without-values index problem nil)))
    (unless (set-p v-set)
      (setf v-set (new-set #'eq))
      (dictionary-enter index problem v-set))
    (set-add removal-strategem v-set)))

;; (defun balanced-strategy-note-strategem-thrown-away-wrt-transformation (strategy transformation-strategem) ...) -- active declareFunction, no body
;; (defun balanced-strategy-note-strategem-thrown-away (strategy strategem motivation) ...) -- active declareFunction, no body

(defun balanced-strategy-no-new-roots? (strategy)
  (declare (type balanced-strategy-p strategy))
  (strategy-dispatch strategy :no-new-roots))

(defun balanced-strategy-no-strategems-active-wrt-removal? (strategy)
  (declare (type balanced-strategy-p strategy))
  (strategy-dispatch strategy :no-active-removal-strategems))

(defun balanced-strategy-no-strategems-active-wrt-transformation? (strategy)
  (declare (type balanced-strategy-p strategy))
  (strategy-dispatch strategy :no-active-transformation-strategems))

(defun balanced-strategy-clear-set-aside-problems (strategy)
  (balanced-strategy-clear-strategems-set-aside-wrt-removal strategy)
  (balanced-strategy-clear-strategems-set-aside-wrt-transformation strategy)
  strategy)

(toplevel
  (note-funcall-helper-function 'balanced-strategy-early-removal-productivity-limit))
