#|
  Copyright (c) 2019-2026 White Flame

  This file is part of Clyc

  Clyc is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clyc is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with Clyc.  If not, see <https://www.gnu.org/licenses/>.

This file derives from work covered by the following copyright
and permission notice:

  Copyright (c) 1995-2009 Cycorp Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
|#


(in-package :clyc)

;;; Struct: join-link-data

(defstruct (join-link-data (:conc-name "J-LINK-DATA-"))
  join-vars
  first-proof-index
  second-proof-index)

(defconstant *dtp-join-link-data* 'join-link-data)

(defmethod print-object ((object join-link-data) stream)
  (default-struct-print-function object stream 0))

;; join-link-data-p is generated by defstruct

(defun new-join-link-data (first-mapped-problem second-mapped-problem)
  (let ((data (make-join-link-data)))
    (setf (j-link-data-join-vars data) (shared-sibling-vars first-mapped-problem second-mapped-problem))
    (setf (j-link-data-first-proof-index data) (new-dictionary #'equal))
    (setf (j-link-data-second-proof-index data) (new-dictionary #'equal))
    data))

;; (defun valid-join-link-data-p (object) ...) -- active declareFunction, no body

(defun join-link-p (object)
  (and (problem-link-p object)
       (eq :join (problem-link-type object))))

(defun maybe-new-join-link (supported-problem first-supporting-mapped-problem second-supporting-mapped-problem)
  "[Cyc] Return join-link-p, either the already existing one or a new one."
  (do-problem-argument-links (candidate-link supported-problem :type :join)
    (when (and (mapped-problem-equal first-supporting-mapped-problem
                                     (join-link-first-mapped-problem candidate-link))
               (mapped-problem-equal second-supporting-mapped-problem
                                     (join-link-second-mapped-problem candidate-link)))
      (return-from maybe-new-join-link candidate-link)))
  (new-join-link supported-problem first-supporting-mapped-problem second-supporting-mapped-problem))

(defun new-join-link (supported-problem first-supporting-mapped-problem second-supporting-mapped-problem)
  (declare (type mapped-problem-p first-supporting-mapped-problem)
           (type mapped-problem-p second-supporting-mapped-problem))
  (let* ((link (new-problem-link :join supported-problem))
         (data (new-join-link-data first-supporting-mapped-problem second-supporting-mapped-problem)))
    (set-problem-link-data link data)
    (connect-supporting-mapped-problem-with-dependent-link second-supporting-mapped-problem link)
    (connect-supporting-mapped-problem-with-dependent-link first-supporting-mapped-problem link)
    (propagate-problem-link link)
    link))

;; (defun destroy-join-link (join-link) ...) -- active declareFunction, no body

;;; Macros: do-join-link-first-proofs, do-join-link-second-proofs
;; Reconstructed from Internal Constants:
;; $list21 = ((BINDINGS-VAR PROOF-VAR JOIN-LINK) &BODY BODY) -- arglist
;; $sym22/$sym28 = INDEX gensym, $sym23/$sym29 = PROOF-LIST-VAR gensym
;; $sym24 = CLET, $sym25 = JOIN-LINK-FIRST-PROOF-INDEX, $sym26 = DO-DICTIONARY, $sym27 = DO-LIST
;; $sym30 = JOIN-LINK-SECOND-PROOF-INDEX
;; Confirmed by register-macro-helper calls in setup.
(defmacro do-join-link-first-proofs ((bindings-var proof-var join-link) &body body)
  (with-temp-vars (index proof-list-var)
    `(let ((,index (join-link-first-proof-index ,join-link)))
       (do-dictionary (,bindings-var ,proof-list-var ,index)
         (dolist (,proof-var ,proof-list-var)
           ,@body)))))

(defmacro do-join-link-second-proofs ((bindings-var proof-var join-link) &body body)
  (with-temp-vars (index proof-list-var)
    `(let ((,index (join-link-second-proof-index ,join-link)))
       (do-dictionary (,bindings-var ,proof-list-var ,index)
         (dolist (,proof-var ,proof-list-var)
           ,@body)))))

(defun join-link-join-vars (join-link)
  (j-link-data-join-vars (problem-link-data join-link)))

(defun join-link-first-proof-index (join-link)
  (j-link-data-first-proof-index (problem-link-data join-link)))

(defun join-link-second-proof-index (join-link)
  (j-link-data-second-proof-index (problem-link-data join-link)))

(defun join-link-first-mapped-problem (join-link)
  (first (problem-link-supporting-mapped-problems join-link)))

(defun join-link-second-mapped-problem (join-link)
  (second (problem-link-supporting-mapped-problems join-link)))

(defun join-link-first-problem (join-link)
  (mapped-problem-problem (join-link-first-mapped-problem join-link)))

(defun join-link-second-problem (join-link)
  (mapped-problem-problem (join-link-second-mapped-problem join-link)))

(defun join-link-trigger-variable-map (join-link trigger-is-first?)
  (mapped-problem-variable-map (join-link-trigger-mapped-problem join-link trigger-is-first?)))

(defun join-link-trigger-mapped-problem (join-link trigger-is-first?)
  (if trigger-is-first?
      (join-link-first-mapped-problem join-link)
      (join-link-second-mapped-problem join-link)))

(defun join-link-sibling-mapped-problem (join-link trigger-is-first?)
  (if trigger-is-first?
      (join-link-second-mapped-problem join-link)
      (join-link-first-mapped-problem join-link)))

(defun join-link-first-proofs-lookup (join-link proof-bindings)
  (let* ((index (join-link-first-proof-index join-link))
         (canonical-proof-bindings (canonicalize-proof-bindings proof-bindings))
         (first-proofs (gethash canonical-proof-bindings index)))
    first-proofs))

(defun join-link-second-proofs-lookup (join-link proof-bindings)
  (let* ((index (join-link-second-proof-index join-link))
         (canonical-proof-bindings (canonicalize-proof-bindings proof-bindings))
         (second-proofs (gethash canonical-proof-bindings index)))
    second-proofs))

(defun join-link-sibling-proofs-lookup (join-link trigger-proof-bindings-wrt-supported trigger-is-first?)
  (if trigger-is-first?
      (join-link-second-proofs-lookup join-link trigger-proof-bindings-wrt-supported)
      (join-link-first-proofs-lookup join-link trigger-proof-bindings-wrt-supported)))

(defun join-link-shared-proof-bindings (join-link trigger-proof-bindings trigger-is-first?)
  (let* ((shared-supported-vars (join-link-join-vars join-link))
         (trigger-to-supported-variable-map (join-link-trigger-variable-map join-link trigger-is-first?))
         (trigger-proof-bindings-wrt-supported (transfer-variable-map-to-bindings-filtered trigger-to-supported-variable-map trigger-proof-bindings))
         (shared-trigger-proof-bindings-wrt-supported (filter-bindings-by-variables trigger-proof-bindings-wrt-supported shared-supported-vars)))
    shared-trigger-proof-bindings-wrt-supported))

(defun join-link-tactic (join-link)
  (let ((supported-problem (problem-link-supported-problem join-link)))
    (do-problem-tactics (join-tactic supported-problem :hl-module *join-module*)
      (when (eq join-link (join-tactic-link join-tactic))
        (return-from join-link-tactic join-tactic)))
    (unless (tactically-unexamined-problem-p supported-problem)
      (error "couldn't find the join tactic for ~s" join-link))
    nil))

(defun add-join-link-first-proof (join-link v-bindings proof)
  "[Cyc] Indexes PROOF by BINDINGS as a first proof in JOIN-LINK"
  (declare (type join-link-p join-link)
           (type proof-p proof))
  (let* ((index (join-link-first-proof-index join-link))
         (canonical-bindings (canonicalize-proof-bindings v-bindings)))
    (dictionary-push index canonical-bindings proof))
  join-link)

;; (defun remove-join-link-first-proof (join-link v-bindings proof) ...) -- active declareFunction, no body

(defun add-join-link-second-proof (join-link v-bindings proof)
  "[Cyc] Indexes PROOF by BINDINGS as a second proof in JOIN-LINK"
  (declare (type join-link-p join-link)
           (type proof-p proof))
  (let* ((index (join-link-second-proof-index join-link))
         (canonical-bindings (canonicalize-proof-bindings v-bindings)))
    (dictionary-push index canonical-bindings proof))
  join-link)

;; (defun remove-join-link-second-proof (join-link v-bindings proof) ...) -- active declareFunction, no body

(defun add-join-link-proof (join-link trigger-proof trigger-is-first?)
  "[Cyc] TRIGGER-PROOF must be a :proven proof, because otherwise it would not have bubbled up to JOIN-LINK."
  (must (proof-proven? trigger-proof) "~a was a rejected proof" trigger-proof)
  (let ((shared-trigger-proof-bindings (join-link-shared-proof-bindings join-link (proof-bindings trigger-proof) trigger-is-first?)))
    (if trigger-is-first?
        (add-join-link-first-proof join-link shared-trigger-proof-bindings trigger-proof)
        (add-join-link-second-proof join-link shared-trigger-proof-bindings trigger-proof)))
  nil)

;; (defun remove-join-link-proof-both-ways (join-link trigger-proof trigger-is-first?) ...) -- active declareFunction, no body
;; (defun remove-join-link-proof (join-link trigger-proof trigger-is-first? shared-trigger-proof-bindings) ...) -- active declareFunction, no body

(defun find-or-create-join-link-supporting-mapped-problems (store dnf-clause first-supporting-problem-spec)
  (let ((first-mapped-problem (find-or-create-problem-from-subclause-spec store dnf-clause first-supporting-problem-spec))
        (second-mapped-problem (find-or-create-problem-without-subclause-spec store dnf-clause first-supporting-problem-spec)))
    (values first-mapped-problem second-mapped-problem)))

(defun first-problem-shared-vars (first-mapped-problem second-mapped-problem)
  "[Cyc] Return listp; the sorted list of variables in FIRST-MAPPED-PROBLEM that also appear (modulo variable maps) in SECOND-MAPPED-PROBLEM."
  (let ((shared-sibling-vars (shared-sibling-vars first-mapped-problem second-mapped-problem)))
    (apply-bindings-backwards (mapped-problem-variable-map first-mapped-problem) shared-sibling-vars)))

(defun second-problem-shared-vars (first-mapped-problem second-mapped-problem)
  "[Cyc] Return listp; the sorted list of variables in SECOND-MAPPED-PROBLEM that also appear (modulo variable maps) in FIRST-MAPPED-PROBLEM."
  (let ((shared-sibling-vars (shared-sibling-vars first-mapped-problem second-mapped-problem)))
    (apply-bindings-backwards (mapped-problem-variable-map second-mapped-problem) shared-sibling-vars)))

(defun shared-sibling-vars (first-mapped-problem second-mapped-problem)
  "[Cyc] Return listp; the sorted list of variables in both FIRST-MAPPED-PROBLEM and SECOND-MAPPED-PROBLEM in the variable space of their common supported problem. Since the values (cdrs) of each variable map are already in the variable space of their common supported problem, we just take the intersection of the values of those two variable maps."
  (let ((shared-vars nil)
        (first-variable-map (mapped-problem-variable-map first-mapped-problem))
        (second-variable-map (mapped-problem-variable-map second-mapped-problem)))
    (dolist (variable-binding first-variable-map)
      (let ((supported-var (variable-binding-value variable-binding)))
        (when (member? supported-var second-variable-map #'eq #'variable-binding-value)
          (push supported-var shared-vars))))
    (sort-hl-variable-list shared-vars)))

(defparameter *join-module* (inference-structural-module :join))

(defun join-tactic-p (object)
  (and (tactic-p object)
       (eq *join-module* (tactic-hl-module object))))

(defun new-join-tactic (join-link first-supporting-problem-spec)
  (let* ((problem (problem-link-supported-problem join-link))
         (data (list join-link first-supporting-problem-spec))
         (tactic (new-tactic problem *join-module* data)))
    (do-problem-relevant-strategies (strategy problem)
      (strategy-note-new-tactic strategy tactic))
    tactic))

(defun join-tactic-link (join-tactic)
  "[Cyc] Return nil or problem-link-p; the link created by JOIN-TACTIC. NIL should only occur if the tactic has been discarded."
  (first (tactic-data join-tactic)))

(defun join-tactic-first-supporting-problem-spec (tactic)
  "[Cyc] Return subclause-spec-p"
  (second (tactic-data tactic)))

(defun join-tactic-first-problem (join-tactic)
  (let ((link (join-tactic-link join-tactic)))
    (when link
      (join-link-first-problem link))))

(defun join-tactic-second-problem (join-tactic)
  (let ((link (join-tactic-link join-tactic)))
    (when link
      (join-link-second-problem link))))

(defun join-tactic-lookahead-problems (join-tactic)
  (let ((first-problem (join-tactic-first-problem join-tactic))
        (second-problem (join-tactic-second-problem join-tactic)))
    (unless (and first-problem second-problem)
      (multiple-value-bind (first-mapped-problem second-mapped-problem)
          (find-or-create-join-tactic-supporting-mapped-problems join-tactic)
        (setf first-problem (mapped-problem-problem first-mapped-problem))
        (setf second-problem (mapped-problem-problem second-mapped-problem))))
    (values first-problem second-problem)))

(defun determine-new-join-tactics (supported-problem dnf-clause)
  (when (binary-clause-p dnf-clause)
    (unless (inference-some-backchain-required-asent-in-clause? dnf-clause)
      (let ((done? nil))
        (let ((index 0))
          (dolist (contextualized-asent (neg-lits dnf-clause))
            (declare (ignore contextualized-asent))
            (unless done?
              (let ((first-supporting-problem-spec (new-single-literal-subclause-spec :neg index)))
                (possibly-determine-new-join-tactic supported-problem first-supporting-problem-spec dnf-clause))
              (setf done? t))
            (incf index)))
        (let ((index 0))
          (dolist (contextualized-asent (pos-lits dnf-clause))
            (declare (ignore contextualized-asent))
            (unless done?
              (let ((first-supporting-problem-spec (new-single-literal-subclause-spec :pos index)))
                (possibly-determine-new-join-tactic supported-problem first-supporting-problem-spec dnf-clause))
              (setf done? t))
            (incf index))))))
  nil)

(defun possibly-determine-new-join-tactic (supported-problem first-supporting-problem-spec dnf-clause)
  "[Cyc] Possibly create a new :JOIN tactic for PROBLEM in which FIRST-SUPPORTING-PROBLEM-SPEC specifies the literals of DNF-CLAUSE which should be the first supporting problem and the remaining literals should be the second supporting problem."
  (declare (type subclause-spec-p first-supporting-problem-spec))
  (let ((store (problem-store supported-problem)))
    (multiple-value-bind (first-mapped-problem second-mapped-problem)
        (find-or-create-join-link-supporting-mapped-problems store dnf-clause first-supporting-problem-spec)
      (let ((join-link (maybe-new-join-link supported-problem first-mapped-problem second-mapped-problem)))
        (new-join-tactic join-link first-supporting-problem-spec)))))

(defun compute-strategic-properties-of-join-tactic (tactic strategy)
  (declare (type join-tactic-p tactic)
           (type strategy-p strategy))
  (let* ((join-link (join-tactic-link tactic))
         (first-mapped-problem (join-link-first-mapped-problem join-link))
         (second-mapped-problem (join-link-second-mapped-problem join-link)))
    (unless (preference-level-p (tactic-preference-level tactic))
      (multiple-value-bind (preference-level justification)
          (compute-join-tactic-preference-level first-mapped-problem second-mapped-problem :tactical)
        (set-tactic-preference-level tactic preference-level justification)))
    (multiple-value-bind (preference-level justification)
        (compute-join-tactic-preference-level first-mapped-problem second-mapped-problem strategy)
      (set-tactic-strategic-preference-level tactic strategy preference-level justification))
    (let ((productivity (compute-join-tactic-productivity first-mapped-problem second-mapped-problem strategy)))
      (set-tactic-strategic-productivity tactic strategy productivity))
    tactic))

(defparameter *join-productivity-scaling-factor* 8
  "[Cyc] A scaling factor by which to reduce the estimated productivities of join tactics. This should really be done by adding an additional cost factor to consider instead of lumping it into productivity.")

(defun compute-join-tactic-productivity (first-mapped-problem second-mapped-problem strategy)
  "[Cyc] The productivity of a :join tactic is the sum of the productivities of its subproblems."
  (declare (type mapped-problem-p first-mapped-problem)
           (type mapped-problem-p second-mapped-problem)
           (type strategy-p strategy))
  (let* ((first-problem (mapped-problem-problem first-mapped-problem))
         (second-problem (mapped-problem-problem second-mapped-problem))
         (first-productivity (memoized-problem-max-removal-productivity first-problem strategy))
         (second-productivity (memoized-problem-max-removal-productivity second-problem strategy))
         (raw-join-productivity (productivity-max first-productivity second-productivity))
         (join-productivity (productivity-divide-number raw-join-productivity *join-productivity-scaling-factor*)))
    join-productivity))

(defun compute-join-tactic-preference-level (first-mapped-problem second-mapped-problem strategic-context)
  "[Cyc] The preference level of a :join tactic is the min of the preference levels of its subproblems."
  (declare (type mapped-problem-p first-mapped-problem)
           (type mapped-problem-p second-mapped-problem)
           (type strategic-context-p strategic-context))
  (let* ((first-problem (mapped-problem-problem first-mapped-problem))
         (first-problem-shared-vars (first-problem-shared-vars first-mapped-problem second-mapped-problem))
         (second-problem (mapped-problem-problem second-mapped-problem))
         (second-problem-shared-vars (second-problem-shared-vars first-mapped-problem second-mapped-problem)))
    (multiple-value-bind (first-preference-level first-justification)
        (memoized-problem-global-preference-level first-problem strategic-context first-problem-shared-vars)
      (multiple-value-bind (second-preference-level second-justification)
          (memoized-problem-global-preference-level second-problem strategic-context second-problem-shared-vars)
        (if (preference-level-< first-preference-level second-preference-level)
            (let ((justification (concatenate 'string "first problem: " first-justification)))
              (values first-preference-level justification))
            (let ((justification (concatenate 'string "second problem: " second-justification)))
              (values second-preference-level justification)))))))

(defun execute-join-tactic (tactic)
  (multiple-value-bind (first-mapped-problem second-mapped-problem)
      (find-or-create-join-tactic-supporting-mapped-problems tactic)
    (let ((join-link (join-tactic-link tactic)))
      (problem-link-open-and-repropagate-supporting-mapped-problem join-link first-mapped-problem)
      (problem-link-open-and-repropagate-supporting-mapped-problem join-link second-mapped-problem)))
  (when (tactic-preferred? tactic :tactical)
    (discard-all-other-possible-structural-conjunctive-tactics tactic))
  (consider-strategic-ramifications-of-tactic-preference-level tactic)
  tactic)

(defun find-or-create-join-tactic-supporting-mapped-problems (tactic)
  (let* ((problem (tactic-problem tactic))
         (query (problem-query problem)))
    (must (singleton? query) "Join tactics like ~a must only apply to singleton problem queries, but ~s was not a singleton" tactic query)
    (let* ((store (problem-store problem))
           (dnf-clause (first query))
           (first-supporting-problem-spec (join-tactic-first-supporting-problem-spec tactic)))
      (find-or-create-join-link-supporting-mapped-problems store dnf-clause first-supporting-problem-spec))))

(defun new-join-proof (join-link subproofs-with-sub-bindings)
  "[Cyc] Return 0 proof-p; return 1 whether the returned proof was newly created."
  (new-conjunctive-proof join-link subproofs-with-sub-bindings))

(defun join-proof-p (object)
  (and (proof-p object)
       (eq :join (proof-type object))))

(defun bubble-up-proof-to-join-link (trigger-subproof variable-map join-link)
  (let ((trigger-is-first? (mapped-proof-is-first? trigger-subproof variable-map join-link)))
    (add-join-link-proof join-link trigger-subproof trigger-is-first?)
    (bubble-up-proof-to-join-link-int trigger-subproof variable-map join-link trigger-is-first?))
  nil)

(defun mapped-proof-is-first? (subproof proof-variable-map join-link)
  (let* ((first-mapped-problem (join-link-first-mapped-problem join-link))
         (first-problem (mapped-problem-problem first-mapped-problem))
         (subproof-supported-problem (proof-supported-problem subproof)))
    (when (eq first-problem subproof-supported-problem)
      (let ((first-variable-map (mapped-problem-variable-map first-mapped-problem)))
        (when (bindings-equal? first-variable-map proof-variable-map)
          (return-from mapped-proof-is-first? t)))))
  nil)

(defun bubble-up-proof-to-join-link-int (trigger-subproof variable-map join-link trigger-is-first?)
  (let* ((proofs nil)
         (trigger-proof-bindings (proof-bindings trigger-subproof))
         (join-bindings (join-link-shared-proof-bindings join-link trigger-proof-bindings trigger-is-first?))
         (sibling-proofs (join-link-sibling-proofs-lookup join-link join-bindings trigger-is-first?)))
    (when sibling-proofs
      (let* ((sibling-mapped-problem (join-link-sibling-mapped-problem join-link trigger-is-first?))
             (sibling-variable-map (mapped-problem-variable-map sibling-mapped-problem))
             (sibling-proofs-with-bindings nil))
        (dolist (sibling-proof sibling-proofs)
          (let ((sibling-sub-proof-bindings (transfer-variable-map-to-bindings sibling-variable-map (proof-bindings sibling-proof))))
            (push (cons sibling-proof sibling-sub-proof-bindings) sibling-proofs-with-bindings)))
        (setf sibling-proofs-with-bindings (nreverse sibling-proofs-with-bindings))
        (let* ((trigger-sub-proof-bindings (transfer-variable-map-to-bindings variable-map trigger-proof-bindings))
               (supporting-mapped-proof-lists-by-supporting-problem
                 (if trigger-is-first?
                     (list (list (cons trigger-subproof trigger-sub-proof-bindings))
                           sibling-proofs-with-bindings)
                     (list sibling-proofs-with-bindings
                           (list (cons trigger-subproof trigger-sub-proof-bindings)))))
               (mapped-subproof-lists (cartesian-product supporting-mapped-proof-lists-by-supporting-problem)))
          (dolist (mapped-subproof-list mapped-subproof-lists)
            (multiple-value-bind (proof new?)
                (new-join-proof join-link mapped-subproof-list)
              (if new?
                  (push proof proofs)
                  (possibly-note-proof-processed trigger-subproof))))))
      (setf proofs (nreverse proofs))
      (dolist (proof proofs)
        (bubble-up-proof proof))))
  nil)

;;; Setup

(toplevel (register-macro-helper 'join-link-first-proof-index 'do-join-link-first-proofs))
(toplevel (register-macro-helper 'join-link-second-proof-index 'do-join-link-second-proofs))
